/* Config.c generated by valac 0.34.4, the Vala compiler
 * generated from Config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define ENTITAS_CONSTANTS_DATADIR "/usr/share"
#define ENTITAS_CONSTANTS_PKGDATADIR "/usr/share/libentitas"
#define ENTITAS_CONSTANTS_GETTEXT_PACKAGE "libentitas"
#define ENTITAS_CONSTANTS_RELEASE_NAME "libentitas"
#define ENTITAS_CONSTANTS_VERSION "0.0.1"



