/* entitas.h generated by valac 0.34.4, the Vala compiler, do not modify */


#ifndef __ENTITAS_H__
#define __ENTITAS_H__

#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib-object.h>
#include <gee.h>

G_BEGIN_DECLS


#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())
#define ENTITAS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ENTITY, EntitasEntity))
#define ENTITAS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_ENTITY, EntitasEntityClass))
#define ENTITAS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ENTITY))
#define ENTITAS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_ENTITY))
#define ENTITAS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_ENTITY, EntitasEntityClass))

typedef struct _EntitasEntity EntitasEntity;
typedef struct _EntitasEntityClass EntitasEntityClass;
typedef struct _EntitasEntityPrivate EntitasEntityPrivate;

#define ENTITAS_TYPE_ICOMPONENT (entitas_icomponent_get_type ())
#define ENTITAS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ICOMPONENT, EntitasIComponent))
#define ENTITAS_IS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ICOMPONENT))
#define ENTITAS_ICOMPONENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_ICOMPONENT, EntitasIComponentIface))

typedef struct _EntitasIComponent EntitasIComponent;
typedef struct _EntitasIComponentIface EntitasIComponentIface;

#define ENTITAS_TYPE_ENTITY_RELEASED (entitas_entity_released_get_type ())
#define ENTITAS_ENTITY_RELEASED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ENTITY_RELEASED, EntitasEntityReleased))
#define ENTITAS_ENTITY_RELEASED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_ENTITY_RELEASED, EntitasEntityReleasedClass))
#define ENTITAS_IS_ENTITY_RELEASED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ENTITY_RELEASED))
#define ENTITAS_IS_ENTITY_RELEASED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_ENTITY_RELEASED))
#define ENTITAS_ENTITY_RELEASED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_ENTITY_RELEASED, EntitasEntityReleasedClass))

typedef struct _EntitasEntityReleased EntitasEntityReleased;
typedef struct _EntitasEntityReleasedClass EntitasEntityReleasedClass;

#define ENTITAS_TYPE_ENTITY_CHANGED (entitas_entity_changed_get_type ())
#define ENTITAS_ENTITY_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ENTITY_CHANGED, EntitasEntityChanged))
#define ENTITAS_ENTITY_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_ENTITY_CHANGED, EntitasEntityChangedClass))
#define ENTITAS_IS_ENTITY_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ENTITY_CHANGED))
#define ENTITAS_IS_ENTITY_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_ENTITY_CHANGED))
#define ENTITAS_ENTITY_CHANGED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_ENTITY_CHANGED, EntitasEntityChangedClass))

typedef struct _EntitasEntityChanged EntitasEntityChanged;
typedef struct _EntitasEntityChangedClass EntitasEntityChangedClass;

#define ENTITAS_TYPE_COMPONENT_REPLACED (entitas_component_replaced_get_type ())
#define ENTITAS_COMPONENT_REPLACED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_COMPONENT_REPLACED, EntitasComponentReplaced))
#define ENTITAS_COMPONENT_REPLACED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_COMPONENT_REPLACED, EntitasComponentReplacedClass))
#define ENTITAS_IS_COMPONENT_REPLACED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_COMPONENT_REPLACED))
#define ENTITAS_IS_COMPONENT_REPLACED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_COMPONENT_REPLACED))
#define ENTITAS_COMPONENT_REPLACED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_COMPONENT_REPLACED, EntitasComponentReplacedClass))

typedef struct _EntitasComponentReplaced EntitasComponentReplaced;
typedef struct _EntitasComponentReplacedClass EntitasComponentReplacedClass;
typedef struct _EntitasComponentReplacedPrivate EntitasComponentReplacedPrivate;

#define ENTITAS_COMPONENT_REPLACED_TYPE_LISTENER (entitas_component_replaced_listener_get_type ())
#define ENTITAS_COMPONENT_REPLACED_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_COMPONENT_REPLACED_TYPE_LISTENER, EntitasComponentReplacedListener))
#define ENTITAS_COMPONENT_REPLACED_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_COMPONENT_REPLACED_TYPE_LISTENER, EntitasComponentReplacedListenerClass))
#define ENTITAS_COMPONENT_REPLACED_IS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_COMPONENT_REPLACED_TYPE_LISTENER))
#define ENTITAS_COMPONENT_REPLACED_IS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_COMPONENT_REPLACED_TYPE_LISTENER))
#define ENTITAS_COMPONENT_REPLACED_LISTENER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_COMPONENT_REPLACED_TYPE_LISTENER, EntitasComponentReplacedListenerClass))

typedef struct _EntitasComponentReplacedListener EntitasComponentReplacedListener;
typedef struct _EntitasComponentReplacedListenerClass EntitasComponentReplacedListenerClass;
typedef struct _EntitasComponentReplacedListenerPrivate EntitasComponentReplacedListenerPrivate;
typedef struct _EntitasEntityChangedPrivate EntitasEntityChangedPrivate;

#define ENTITAS_ENTITY_CHANGED_TYPE_LISTENER (entitas_entity_changed_listener_get_type ())
#define ENTITAS_ENTITY_CHANGED_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, EntitasEntityChangedListener))
#define ENTITAS_ENTITY_CHANGED_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, EntitasEntityChangedListenerClass))
#define ENTITAS_ENTITY_CHANGED_IS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_ENTITY_CHANGED_TYPE_LISTENER))
#define ENTITAS_ENTITY_CHANGED_IS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_ENTITY_CHANGED_TYPE_LISTENER))
#define ENTITAS_ENTITY_CHANGED_LISTENER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, EntitasEntityChangedListenerClass))

typedef struct _EntitasEntityChangedListener EntitasEntityChangedListener;
typedef struct _EntitasEntityChangedListenerClass EntitasEntityChangedListenerClass;
typedef struct _EntitasEntityChangedListenerPrivate EntitasEntityChangedListenerPrivate;
typedef struct _EntitasEntityReleasedPrivate EntitasEntityReleasedPrivate;

#define ENTITAS_ENTITY_RELEASED_TYPE_LISTENER (entitas_entity_released_listener_get_type ())
#define ENTITAS_ENTITY_RELEASED_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_ENTITY_RELEASED_TYPE_LISTENER, EntitasEntityReleasedListener))
#define ENTITAS_ENTITY_RELEASED_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_ENTITY_RELEASED_TYPE_LISTENER, EntitasEntityReleasedListenerClass))
#define ENTITAS_ENTITY_RELEASED_IS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_ENTITY_RELEASED_TYPE_LISTENER))
#define ENTITAS_ENTITY_RELEASED_IS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_ENTITY_RELEASED_TYPE_LISTENER))
#define ENTITAS_ENTITY_RELEASED_LISTENER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_ENTITY_RELEASED_TYPE_LISTENER, EntitasEntityReleasedListenerClass))

typedef struct _EntitasEntityReleasedListener EntitasEntityReleasedListener;
typedef struct _EntitasEntityReleasedListenerClass EntitasEntityReleasedListenerClass;
typedef struct _EntitasEntityReleasedListenerPrivate EntitasEntityReleasedListenerPrivate;

#define ENTITAS_TYPE_GROUP (entitas_group_get_type ())
#define ENTITAS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_GROUP, EntitasGroup))
#define ENTITAS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_GROUP, EntitasGroupClass))
#define ENTITAS_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_GROUP))
#define ENTITAS_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_GROUP))
#define ENTITAS_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_GROUP, EntitasGroupClass))

typedef struct _EntitasGroup EntitasGroup;
typedef struct _EntitasGroupClass EntitasGroupClass;

#define ENTITAS_TYPE_GROUP_CHANGED (entitas_group_changed_get_type ())
#define ENTITAS_GROUP_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_GROUP_CHANGED, EntitasGroupChanged))
#define ENTITAS_GROUP_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_GROUP_CHANGED, EntitasGroupChangedClass))
#define ENTITAS_IS_GROUP_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_GROUP_CHANGED))
#define ENTITAS_IS_GROUP_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_GROUP_CHANGED))
#define ENTITAS_GROUP_CHANGED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_GROUP_CHANGED, EntitasGroupChangedClass))

typedef struct _EntitasGroupChanged EntitasGroupChanged;
typedef struct _EntitasGroupChangedClass EntitasGroupChangedClass;
typedef struct _EntitasGroupChangedPrivate EntitasGroupChangedPrivate;

#define ENTITAS_GROUP_CHANGED_TYPE_LISTENER (entitas_group_changed_listener_get_type ())
#define ENTITAS_GROUP_CHANGED_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_GROUP_CHANGED_TYPE_LISTENER, EntitasGroupChangedListener))
#define ENTITAS_GROUP_CHANGED_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_GROUP_CHANGED_TYPE_LISTENER, EntitasGroupChangedListenerClass))
#define ENTITAS_GROUP_CHANGED_IS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_GROUP_CHANGED_TYPE_LISTENER))
#define ENTITAS_GROUP_CHANGED_IS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_GROUP_CHANGED_TYPE_LISTENER))
#define ENTITAS_GROUP_CHANGED_LISTENER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_GROUP_CHANGED_TYPE_LISTENER, EntitasGroupChangedListenerClass))

typedef struct _EntitasGroupChangedListener EntitasGroupChangedListener;
typedef struct _EntitasGroupChangedListenerClass EntitasGroupChangedListenerClass;
typedef struct _EntitasGroupChangedListenerPrivate EntitasGroupChangedListenerPrivate;

#define ENTITAS_TYPE_GROUP_UPDATED (entitas_group_updated_get_type ())
#define ENTITAS_GROUP_UPDATED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_GROUP_UPDATED, EntitasGroupUpdated))
#define ENTITAS_GROUP_UPDATED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_GROUP_UPDATED, EntitasGroupUpdatedClass))
#define ENTITAS_IS_GROUP_UPDATED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_GROUP_UPDATED))
#define ENTITAS_IS_GROUP_UPDATED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_GROUP_UPDATED))
#define ENTITAS_GROUP_UPDATED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_GROUP_UPDATED, EntitasGroupUpdatedClass))

typedef struct _EntitasGroupUpdated EntitasGroupUpdated;
typedef struct _EntitasGroupUpdatedClass EntitasGroupUpdatedClass;
typedef struct _EntitasGroupUpdatedPrivate EntitasGroupUpdatedPrivate;

#define ENTITAS_GROUP_UPDATED_TYPE_LISTENER (entitas_group_updated_listener_get_type ())
#define ENTITAS_GROUP_UPDATED_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_GROUP_UPDATED_TYPE_LISTENER, EntitasGroupUpdatedListener))
#define ENTITAS_GROUP_UPDATED_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_GROUP_UPDATED_TYPE_LISTENER, EntitasGroupUpdatedListenerClass))
#define ENTITAS_GROUP_UPDATED_IS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_GROUP_UPDATED_TYPE_LISTENER))
#define ENTITAS_GROUP_UPDATED_IS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_GROUP_UPDATED_TYPE_LISTENER))
#define ENTITAS_GROUP_UPDATED_LISTENER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_GROUP_UPDATED_TYPE_LISTENER, EntitasGroupUpdatedListenerClass))

typedef struct _EntitasGroupUpdatedListener EntitasGroupUpdatedListener;
typedef struct _EntitasGroupUpdatedListenerClass EntitasGroupUpdatedListenerClass;
typedef struct _EntitasGroupUpdatedListenerPrivate EntitasGroupUpdatedListenerPrivate;

#define ENTITAS_TYPE_WORLD (entitas_world_get_type ())
#define ENTITAS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_WORLD, EntitasWorld))
#define ENTITAS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_WORLD, EntitasWorldClass))
#define ENTITAS_IS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_WORLD))
#define ENTITAS_IS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_WORLD))
#define ENTITAS_WORLD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_WORLD, EntitasWorldClass))

typedef struct _EntitasWorld EntitasWorld;
typedef struct _EntitasWorldClass EntitasWorldClass;

#define ENTITAS_TYPE_GROUPS_CHANGED (entitas_groups_changed_get_type ())
#define ENTITAS_GROUPS_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_GROUPS_CHANGED, EntitasGroupsChanged))
#define ENTITAS_GROUPS_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_GROUPS_CHANGED, EntitasGroupsChangedClass))
#define ENTITAS_IS_GROUPS_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_GROUPS_CHANGED))
#define ENTITAS_IS_GROUPS_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_GROUPS_CHANGED))
#define ENTITAS_GROUPS_CHANGED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_GROUPS_CHANGED, EntitasGroupsChangedClass))

typedef struct _EntitasGroupsChanged EntitasGroupsChanged;
typedef struct _EntitasGroupsChangedClass EntitasGroupsChangedClass;
typedef struct _EntitasGroupsChangedPrivate EntitasGroupsChangedPrivate;

#define ENTITAS_GROUPS_CHANGED_TYPE_LISTENER (entitas_groups_changed_listener_get_type ())
#define ENTITAS_GROUPS_CHANGED_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, EntitasGroupsChangedListener))
#define ENTITAS_GROUPS_CHANGED_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, EntitasGroupsChangedListenerClass))
#define ENTITAS_GROUPS_CHANGED_IS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_GROUPS_CHANGED_TYPE_LISTENER))
#define ENTITAS_GROUPS_CHANGED_IS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_GROUPS_CHANGED_TYPE_LISTENER))
#define ENTITAS_GROUPS_CHANGED_LISTENER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, EntitasGroupsChangedListenerClass))

typedef struct _EntitasGroupsChangedListener EntitasGroupsChangedListener;
typedef struct _EntitasGroupsChangedListenerClass EntitasGroupsChangedListenerClass;
typedef struct _EntitasGroupsChangedListenerPrivate EntitasGroupsChangedListenerPrivate;

#define ENTITAS_TYPE_WORLD_CHANGED (entitas_world_changed_get_type ())
#define ENTITAS_WORLD_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_WORLD_CHANGED, EntitasWorldChanged))
#define ENTITAS_WORLD_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_WORLD_CHANGED, EntitasWorldChangedClass))
#define ENTITAS_IS_WORLD_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_WORLD_CHANGED))
#define ENTITAS_IS_WORLD_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_WORLD_CHANGED))
#define ENTITAS_WORLD_CHANGED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_WORLD_CHANGED, EntitasWorldChangedClass))

typedef struct _EntitasWorldChanged EntitasWorldChanged;
typedef struct _EntitasWorldChangedClass EntitasWorldChangedClass;
typedef struct _EntitasWorldChangedPrivate EntitasWorldChangedPrivate;

#define ENTITAS_WORLD_CHANGED_TYPE_LISTENER (entitas_world_changed_listener_get_type ())
#define ENTITAS_WORLD_CHANGED_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_WORLD_CHANGED_TYPE_LISTENER, EntitasWorldChangedListener))
#define ENTITAS_WORLD_CHANGED_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_WORLD_CHANGED_TYPE_LISTENER, EntitasWorldChangedListenerClass))
#define ENTITAS_WORLD_CHANGED_IS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_WORLD_CHANGED_TYPE_LISTENER))
#define ENTITAS_WORLD_CHANGED_IS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_WORLD_CHANGED_TYPE_LISTENER))
#define ENTITAS_WORLD_CHANGED_LISTENER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_WORLD_CHANGED_TYPE_LISTENER, EntitasWorldChangedListenerClass))

typedef struct _EntitasWorldChangedListener EntitasWorldChangedListener;
typedef struct _EntitasWorldChangedListenerClass EntitasWorldChangedListenerClass;
typedef struct _EntitasWorldChangedListenerPrivate EntitasWorldChangedListenerPrivate;
typedef struct _EntitasGroupPrivate EntitasGroupPrivate;

#define ENTITAS_TYPE_IMATCHER (entitas_imatcher_get_type ())
#define ENTITAS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IMATCHER, EntitasIMatcher))
#define ENTITAS_IS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IMATCHER))
#define ENTITAS_IMATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IMATCHER, EntitasIMatcherIface))

typedef struct _EntitasIMatcher EntitasIMatcher;
typedef struct _EntitasIMatcherIface EntitasIMatcherIface;

#define ENTITAS_TYPE_ICOMPOUND_MATCHER (entitas_icompound_matcher_get_type ())
#define ENTITAS_ICOMPOUND_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ICOMPOUND_MATCHER, EntitasICompoundMatcher))
#define ENTITAS_IS_ICOMPOUND_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ICOMPOUND_MATCHER))
#define ENTITAS_ICOMPOUND_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_ICOMPOUND_MATCHER, EntitasICompoundMatcherIface))

typedef struct _EntitasICompoundMatcher EntitasICompoundMatcher;
typedef struct _EntitasICompoundMatcherIface EntitasICompoundMatcherIface;

#define ENTITAS_TYPE_INONE_OF_MATCHER (entitas_inone_of_matcher_get_type ())
#define ENTITAS_INONE_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_INONE_OF_MATCHER, EntitasINoneOfMatcher))
#define ENTITAS_IS_INONE_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_INONE_OF_MATCHER))
#define ENTITAS_INONE_OF_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_INONE_OF_MATCHER, EntitasINoneOfMatcherIface))

typedef struct _EntitasINoneOfMatcher EntitasINoneOfMatcher;
typedef struct _EntitasINoneOfMatcherIface EntitasINoneOfMatcherIface;

#define ENTITAS_TYPE_IANY_OF_MATCHER (entitas_iany_of_matcher_get_type ())
#define ENTITAS_IANY_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IANY_OF_MATCHER, EntitasIAnyOfMatcher))
#define ENTITAS_IS_IANY_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IANY_OF_MATCHER))
#define ENTITAS_IANY_OF_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IANY_OF_MATCHER, EntitasIAnyOfMatcherIface))

typedef struct _EntitasIAnyOfMatcher EntitasIAnyOfMatcher;
typedef struct _EntitasIAnyOfMatcherIface EntitasIAnyOfMatcherIface;

#define ENTITAS_TYPE_IALL_OF_MATCHER (entitas_iall_of_matcher_get_type ())
#define ENTITAS_IALL_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IALL_OF_MATCHER, EntitasIAllOfMatcher))
#define ENTITAS_IS_IALL_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IALL_OF_MATCHER))
#define ENTITAS_IALL_OF_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IALL_OF_MATCHER, EntitasIAllOfMatcherIface))

typedef struct _EntitasIAllOfMatcher EntitasIAllOfMatcher;
typedef struct _EntitasIAllOfMatcherIface EntitasIAllOfMatcherIface;

#define ENTITAS_TYPE_ISYSTEM (entitas_isystem_get_type ())
#define ENTITAS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ISYSTEM, EntitasISystem))
#define ENTITAS_IS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ISYSTEM))
#define ENTITAS_ISYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_ISYSTEM, EntitasISystemIface))

typedef struct _EntitasISystem EntitasISystem;
typedef struct _EntitasISystemIface EntitasISystemIface;

#define ENTITAS_TYPE_ISET_WORLD (entitas_iset_world_get_type ())
#define ENTITAS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ISET_WORLD, EntitasISetWorld))
#define ENTITAS_IS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ISET_WORLD))
#define ENTITAS_ISET_WORLD_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_ISET_WORLD, EntitasISetWorldIface))

typedef struct _EntitasISetWorld EntitasISetWorld;
typedef struct _EntitasISetWorldIface EntitasISetWorldIface;

#define ENTITAS_TYPE_IEXECUTE_SYSTEM (entitas_iexecute_system_get_type ())
#define ENTITAS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IEXECUTE_SYSTEM, EntitasIExecuteSystem))
#define ENTITAS_IS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IEXECUTE_SYSTEM))
#define ENTITAS_IEXECUTE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IEXECUTE_SYSTEM, EntitasIExecuteSystemIface))

typedef struct _EntitasIExecuteSystem EntitasIExecuteSystem;
typedef struct _EntitasIExecuteSystemIface EntitasIExecuteSystemIface;

#define ENTITAS_TYPE_IINITIALIZE_SYSTEM (entitas_iinitialize_system_get_type ())
#define ENTITAS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IINITIALIZE_SYSTEM, EntitasIInitializeSystem))
#define ENTITAS_IS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IINITIALIZE_SYSTEM))
#define ENTITAS_IINITIALIZE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IINITIALIZE_SYSTEM, EntitasIInitializeSystemIface))

typedef struct _EntitasIInitializeSystem EntitasIInitializeSystem;
typedef struct _EntitasIInitializeSystemIface EntitasIInitializeSystemIface;

#define ENTITAS_TYPE_GROUP_EVENT_TYPE (entitas_group_event_type_get_type ())

#define ENTITAS_TYPE_MATCHER (entitas_matcher_get_type ())
#define ENTITAS_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_MATCHER, EntitasMatcher))
#define ENTITAS_MATCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_MATCHER, EntitasMatcherClass))
#define ENTITAS_IS_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_MATCHER))
#define ENTITAS_IS_MATCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_MATCHER))
#define ENTITAS_MATCHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_MATCHER, EntitasMatcherClass))

typedef struct _EntitasMatcher EntitasMatcher;
typedef struct _EntitasMatcherClass EntitasMatcherClass;
typedef struct _EntitasMatcherPrivate EntitasMatcherPrivate;
typedef struct _EntitasWorldPrivate EntitasWorldPrivate;

struct _EntitasEntity {
	GObject parent_instance;
	EntitasEntityPrivate * priv;
	gint db_id;
	gint ic;
};

struct _EntitasEntityClass {
	GObjectClass parent_class;
};

struct _EntitasIComponentIface {
	GTypeInterface parent_iface;
};

typedef enum  {
	ENTITAS_ECS_EXCEPTION_EntityIsNotEnabled,
	ENTITAS_ECS_EXCEPTION_EntityAlreadyHasComponent,
	ENTITAS_ECS_EXCEPTION_EntityDoesNotHaveComponent,
	ENTITAS_ECS_EXCEPTION_EntityIsAlreadyReleased,
	ENTITAS_ECS_EXCEPTION_SingleEntity,
	ENTITAS_ECS_EXCEPTION_Matcher,
	ENTITAS_ECS_EXCEPTION_WorldDoesNotContainEntity
} EntitasEcsException;
#define ENTITAS_ECS_EXCEPTION entitas_ecs_exception_quark ()
typedef void (*EntitasOnComponentReplaced) (EntitasEntity* e, gint index, EntitasIComponent* component, EntitasIComponent* replacement, void* user_data);
struct _EntitasComponentReplaced {
	GObject parent_instance;
	EntitasComponentReplacedPrivate * priv;
};

struct _EntitasComponentReplacedClass {
	GObjectClass parent_class;
};

struct _EntitasComponentReplacedListener {
	GObject parent_instance;
	EntitasComponentReplacedListenerPrivate * priv;
};

struct _EntitasComponentReplacedListenerClass {
	GObjectClass parent_class;
};

typedef void (*EntitasOnEntityChanged) (EntitasEntity* e, gint index, EntitasIComponent* component, void* user_data);
struct _EntitasEntityChanged {
	GObject parent_instance;
	EntitasEntityChangedPrivate * priv;
};

struct _EntitasEntityChangedClass {
	GObjectClass parent_class;
};

struct _EntitasEntityChangedListener {
	GObject parent_instance;
	EntitasEntityChangedListenerPrivate * priv;
};

struct _EntitasEntityChangedListenerClass {
	GObjectClass parent_class;
};

typedef void (*EntitasOnEntityReleased) (EntitasEntity* e, void* user_data);
struct _EntitasEntityReleased {
	GObject parent_instance;
	EntitasEntityReleasedPrivate * priv;
};

struct _EntitasEntityReleasedClass {
	GObjectClass parent_class;
};

struct _EntitasEntityReleasedListener {
	GObject parent_instance;
	EntitasEntityReleasedListenerPrivate * priv;
};

struct _EntitasEntityReleasedListenerClass {
	GObjectClass parent_class;
};

typedef void (*EntitasOnGroupChanged) (EntitasGroup* g, EntitasEntity* e, gint i, EntitasIComponent* c, void* user_data);
struct _EntitasGroupChanged {
	GObject parent_instance;
	EntitasGroupChangedPrivate * priv;
};

struct _EntitasGroupChangedClass {
	GObjectClass parent_class;
};

struct _EntitasGroupChangedListener {
	GObject parent_instance;
	EntitasGroupChangedListenerPrivate * priv;
};

struct _EntitasGroupChangedListenerClass {
	GObjectClass parent_class;
};

typedef void (*EntitasOnGroupUpdated) (EntitasGroup* g, EntitasEntity* e, gint i, EntitasIComponent* c, EntitasIComponent* u, void* user_data);
struct _EntitasGroupUpdated {
	GObject parent_instance;
	EntitasGroupUpdatedPrivate * priv;
};

struct _EntitasGroupUpdatedClass {
	GObjectClass parent_class;
};

struct _EntitasGroupUpdatedListener {
	GObject parent_instance;
	EntitasGroupUpdatedListenerPrivate * priv;
};

struct _EntitasGroupUpdatedListenerClass {
	GObjectClass parent_class;
};

typedef void (*EntitasOnGroupsChanged) (EntitasWorld* w, EntitasGroup* g, void* user_data);
struct _EntitasGroupsChanged {
	GObject parent_instance;
	EntitasGroupsChangedPrivate * priv;
};

struct _EntitasGroupsChangedClass {
	GObjectClass parent_class;
};

struct _EntitasGroupsChangedListener {
	GObject parent_instance;
	EntitasGroupsChangedListenerPrivate * priv;
};

struct _EntitasGroupsChangedListenerClass {
	GObjectClass parent_class;
};

typedef void (*EntitasOnWorldChanged) (EntitasWorld* w, EntitasEntity* e, void* user_data);
struct _EntitasWorldChanged {
	GObject parent_instance;
	EntitasWorldChangedPrivate * priv;
};

struct _EntitasWorldChangedClass {
	GObjectClass parent_class;
};

struct _EntitasWorldChangedListener {
	GObject parent_instance;
	EntitasWorldChangedListenerPrivate * priv;
};

struct _EntitasWorldChangedListenerClass {
	GObjectClass parent_class;
};

struct _EntitasGroup {
	GObject parent_instance;
	EntitasGroupPrivate * priv;
};

struct _EntitasGroupClass {
	GObjectClass parent_class;
};

struct _EntitasIMatcherIface {
	GTypeInterface parent_iface;
	gboolean (*matches) (EntitasIMatcher* self, EntitasEntity* entity);
	gchar* (*toString) (EntitasIMatcher* self);
	const gchar* (*get_id) (EntitasIMatcher* self);
	gint* (*get_indices) (EntitasIMatcher* self, int* result_length1);
};

struct _EntitasICompoundMatcherIface {
	GTypeInterface parent_iface;
	gint* (*get_allOfIndices) (EntitasICompoundMatcher* self, int* result_length1);
	gint* (*get_anyOfIndices) (EntitasICompoundMatcher* self, int* result_length1);
	gint* (*get_noneOfIndices) (EntitasICompoundMatcher* self, int* result_length1);
};

struct _EntitasINoneOfMatcherIface {
	GTypeInterface parent_iface;
};

struct _EntitasIAnyOfMatcherIface {
	GTypeInterface parent_iface;
	EntitasINoneOfMatcher* (*noneOf) (EntitasIAnyOfMatcher* self, gint* args, int args_length1);
};

struct _EntitasIAllOfMatcherIface {
	GTypeInterface parent_iface;
	EntitasIAnyOfMatcher* (*anyOf) (EntitasIAllOfMatcher* self, gint* args, int args_length1);
	EntitasINoneOfMatcher* (*noneOf) (EntitasIAllOfMatcher* self, gint* args, int args_length1);
};

struct _EntitasISystemIface {
	GTypeInterface parent_iface;
};

struct _EntitasISetWorldIface {
	GTypeInterface parent_iface;
	void (*setWorld) (EntitasISetWorld* self, EntitasWorld* world);
};

struct _EntitasIExecuteSystemIface {
	GTypeInterface parent_iface;
	void (*execute) (EntitasIExecuteSystem* self);
};

struct _EntitasIInitializeSystemIface {
	GTypeInterface parent_iface;
	void (*initialize) (EntitasIInitializeSystem* self);
};

typedef enum  {
	ENTITAS_GROUP_EVENT_TYPE_OnEntityAdded,
	ENTITAS_GROUP_EVENT_TYPE_OnEntityRemoved,
	ENTITAS_GROUP_EVENT_TYPE_OnEntityAddedOrRemoved
} EntitasGroupEventType;

struct _EntitasMatcher {
	GObject parent_instance;
	EntitasMatcherPrivate * priv;
};

struct _EntitasMatcherClass {
	GObjectClass parent_class;
};

struct _EntitasWorld {
	GObject parent_instance;
	EntitasWorldPrivate * priv;
};

struct _EntitasWorldClass {
	GObjectClass parent_class;
};


#define ENTITAS_CONSTANTS_DATADIR "/usr/share"
#define ENTITAS_CONSTANTS_PKGDATADIR "/usr/share/libentitas"
#define ENTITAS_CONSTANTS_GETTEXT_PACKAGE "libentitas"
#define ENTITAS_CONSTANTS_RELEASE_NAME "libentitas"
#define ENTITAS_CONSTANTS_VERSION "0.0.1"
#define ENTITAS_POOL_SIZE 128
GType entitas_entity_get_type (void) G_GNUC_CONST;
extern gint entitas_entity_size;
extern gboolean entitas_entity_first;
extern gint entitas_entity_maxEntities;
extern gint entitas_entity_incEntities;
extern gint entitas_entity_db_index;
EntitasEntity* entitas_entity_new (gchar** componentsEnum, int componentsEnum_length1, gint totalComponents);
EntitasEntity* entitas_entity_construct (GType object_type, gchar** componentsEnum, int componentsEnum_length1, gint totalComponents);
void entitas_entity_initialize (EntitasEntity* self, const gchar* name, const gchar* id, gint creationIndex);
GType entitas_icomponent_get_type (void) G_GNUC_CONST;
GQuark entitas_ecs_exception_quark (void);
EntitasEntity* entitas_entity_addComponent (EntitasEntity* self, gint index, EntitasIComponent* component, GError** error);
EntitasEntity* entitas_entity_removeComponent (EntitasEntity* self, gint index, GError** error);
EntitasEntity* entitas_entity_replaceComponent (EntitasEntity* self, gint index, EntitasIComponent* component, GError** error);
EntitasIComponent* entitas_entity_getComponent (EntitasEntity* self, gint index, GError** error);
EntitasIComponent** entitas_entity_getComponents (EntitasEntity* self, int* result_length1);
gint* entitas_entity_getComponentIndices (EntitasEntity* self, int* result_length1);
gboolean entitas_entity_hasComponent (EntitasEntity* self, gint index);
gboolean entitas_entity_hasComponents (EntitasEntity* self, gint* indices, int indices_length1);
gboolean entitas_entity_hasAnyComponent (EntitasEntity* self, gint* indices, int indices_length1);
void entitas_entity_removeAllComponents (EntitasEntity* self);
void entitas_entity_destroy (EntitasEntity* self);
gchar* entitas_entity_toString (EntitasEntity* self);
EntitasEntity* entitas_entity_addRef (EntitasEntity* self);
void entitas_entity_release (EntitasEntity* self, GError** error);
gint entitas_entity_get_creationIndex (EntitasEntity* self);
const gchar* entitas_entity_get_name (EntitasEntity* self);
const gchar* entitas_entity_get_id (EntitasEntity* self);
gboolean entitas_entity_get_isEnabled (EntitasEntity* self);
gint entitas_entity_get_refCount (EntitasEntity* self);
GType entitas_entity_released_get_type (void) G_GNUC_CONST;
EntitasEntityReleased* entitas_entity_get_onEntityReleased (EntitasEntity* self);
GType entitas_entity_changed_get_type (void) G_GNUC_CONST;
EntitasEntityChanged* entitas_entity_get_onComponentAdded (EntitasEntity* self);
EntitasEntityChanged* entitas_entity_get_onComponentRemoved (EntitasEntity* self);
GType entitas_component_replaced_get_type (void) G_GNUC_CONST;
EntitasComponentReplaced* entitas_entity_get_onComponentReplaced (EntitasEntity* self);
void entitas_component_replaced_add (EntitasComponentReplaced* self, EntitasOnComponentReplaced event, void* event_target);
void entitas_component_replaced_remove (EntitasComponentReplaced* self, EntitasOnComponentReplaced event, void* event_target);
void entitas_component_replaced_clear (EntitasComponentReplaced* self);
void entitas_component_replaced_dispatch (EntitasComponentReplaced* self, EntitasEntity* e, gint index, EntitasIComponent* component, EntitasIComponent* replacement);
EntitasComponentReplaced* entitas_component_replaced_new (void);
EntitasComponentReplaced* entitas_component_replaced_construct (GType object_type);
GType entitas_component_replaced_listener_get_type (void) G_GNUC_CONST;
EntitasComponentReplacedListener* entitas_component_replaced_listener_new (EntitasOnComponentReplaced event, void* event_target);
EntitasComponentReplacedListener* entitas_component_replaced_listener_construct (GType object_type, EntitasOnComponentReplaced event, void* event_target);
EntitasOnComponentReplaced entitas_component_replaced_listener_get_event (EntitasComponentReplacedListener* self, gpointer* result_target);
void entitas_component_replaced_listener_set_event (EntitasComponentReplacedListener* self, EntitasOnComponentReplaced value, gpointer value_target);
void entitas_entity_changed_add (EntitasEntityChanged* self, EntitasOnEntityChanged event, void* event_target);
void entitas_entity_changed_remove (EntitasEntityChanged* self, EntitasOnEntityChanged event, void* event_target);
void entitas_entity_changed_clear (EntitasEntityChanged* self);
void entitas_entity_changed_dispatch (EntitasEntityChanged* self, EntitasEntity* e, gint index, EntitasIComponent* component);
EntitasEntityChanged* entitas_entity_changed_new (void);
EntitasEntityChanged* entitas_entity_changed_construct (GType object_type);
GType entitas_entity_changed_listener_get_type (void) G_GNUC_CONST;
EntitasEntityChangedListener* entitas_entity_changed_listener_new (EntitasOnEntityChanged event, void* event_target);
EntitasEntityChangedListener* entitas_entity_changed_listener_construct (GType object_type, EntitasOnEntityChanged event, void* event_target);
EntitasOnEntityChanged entitas_entity_changed_listener_get_event (EntitasEntityChangedListener* self, gpointer* result_target);
void entitas_entity_changed_listener_set_event (EntitasEntityChangedListener* self, EntitasOnEntityChanged value, gpointer value_target);
void entitas_entity_released_add (EntitasEntityReleased* self, EntitasOnEntityReleased event, void* event_target);
void entitas_entity_released_remove (EntitasEntityReleased* self, EntitasOnEntityReleased event, void* event_target);
void entitas_entity_released_clear (EntitasEntityReleased* self);
void entitas_entity_released_dispatch (EntitasEntityReleased* self, EntitasEntity* e);
EntitasEntityReleased* entitas_entity_released_new (void);
EntitasEntityReleased* entitas_entity_released_construct (GType object_type);
GType entitas_entity_released_listener_get_type (void) G_GNUC_CONST;
EntitasEntityReleasedListener* entitas_entity_released_listener_new (EntitasOnEntityReleased event, void* event_target);
EntitasEntityReleasedListener* entitas_entity_released_listener_construct (GType object_type, EntitasOnEntityReleased event, void* event_target);
EntitasOnEntityReleased entitas_entity_released_listener_get_event (EntitasEntityReleasedListener* self, gpointer* result_target);
void entitas_entity_released_listener_set_event (EntitasEntityReleasedListener* self, EntitasOnEntityReleased value, gpointer value_target);
GType entitas_group_get_type (void) G_GNUC_CONST;
GType entitas_group_changed_get_type (void) G_GNUC_CONST;
void entitas_group_changed_add (EntitasGroupChanged* self, EntitasOnGroupChanged event, void* event_target);
void entitas_group_changed_remove (EntitasGroupChanged* self, EntitasOnGroupChanged event, void* event_target);
void entitas_group_changed_clear (EntitasGroupChanged* self);
void entitas_group_changed_dispatch (EntitasGroupChanged* self, EntitasGroup* g, EntitasEntity* e, gint i, EntitasIComponent* c);
EntitasGroupChanged* entitas_group_changed_new (void);
EntitasGroupChanged* entitas_group_changed_construct (GType object_type);
GType entitas_group_changed_listener_get_type (void) G_GNUC_CONST;
EntitasGroupChangedListener* entitas_group_changed_listener_new (EntitasOnGroupChanged event, void* event_target);
EntitasGroupChangedListener* entitas_group_changed_listener_construct (GType object_type, EntitasOnGroupChanged event, void* event_target);
EntitasOnGroupChanged entitas_group_changed_listener_get_event (EntitasGroupChangedListener* self, gpointer* result_target);
void entitas_group_changed_listener_set_event (EntitasGroupChangedListener* self, EntitasOnGroupChanged value, gpointer value_target);
GType entitas_group_updated_get_type (void) G_GNUC_CONST;
void entitas_group_updated_add (EntitasGroupUpdated* self, EntitasOnGroupUpdated event, void* event_target);
void entitas_group_updated_remove (EntitasGroupUpdated* self, EntitasOnGroupUpdated event, void* event_target);
void entitas_group_updated_clear (EntitasGroupUpdated* self);
void entitas_group_updated_dispatch (EntitasGroupUpdated* self, EntitasGroup* g, EntitasEntity* e, gint i, EntitasIComponent* c, EntitasIComponent* u);
EntitasGroupUpdated* entitas_group_updated_new (void);
EntitasGroupUpdated* entitas_group_updated_construct (GType object_type);
GType entitas_group_updated_listener_get_type (void) G_GNUC_CONST;
EntitasGroupUpdatedListener* entitas_group_updated_listener_new (EntitasOnGroupUpdated event, void* event_target);
EntitasGroupUpdatedListener* entitas_group_updated_listener_construct (GType object_type, EntitasOnGroupUpdated event, void* event_target);
EntitasOnGroupUpdated entitas_group_updated_listener_get_event (EntitasGroupUpdatedListener* self, gpointer* result_target);
void entitas_group_updated_listener_set_event (EntitasGroupUpdatedListener* self, EntitasOnGroupUpdated value, gpointer value_target);
GType entitas_world_get_type (void) G_GNUC_CONST;
GType entitas_groups_changed_get_type (void) G_GNUC_CONST;
void entitas_groups_changed_add (EntitasGroupsChanged* self, EntitasOnGroupsChanged event, void* event_target);
void entitas_groups_changed_remove (EntitasGroupsChanged* self, EntitasOnGroupsChanged event, void* event_target);
void entitas_groups_changed_clear (EntitasGroupsChanged* self);
void entitas_groups_changed_dispatch (EntitasGroupsChanged* self, EntitasWorld* w, EntitasGroup* g);
EntitasGroupsChanged* entitas_groups_changed_new (void);
EntitasGroupsChanged* entitas_groups_changed_construct (GType object_type);
GType entitas_groups_changed_listener_get_type (void) G_GNUC_CONST;
EntitasGroupsChangedListener* entitas_groups_changed_listener_new (EntitasOnGroupsChanged event, void* event_target);
EntitasGroupsChangedListener* entitas_groups_changed_listener_construct (GType object_type, EntitasOnGroupsChanged event, void* event_target);
EntitasOnGroupsChanged entitas_groups_changed_listener_get_event (EntitasGroupsChangedListener* self, gpointer* result_target);
void entitas_groups_changed_listener_set_event (EntitasGroupsChangedListener* self, EntitasOnGroupsChanged value, gpointer value_target);
GType entitas_world_changed_get_type (void) G_GNUC_CONST;
void entitas_world_changed_add (EntitasWorldChanged* self, EntitasOnWorldChanged event, void* event_target);
void entitas_world_changed_remove (EntitasWorldChanged* self, EntitasOnWorldChanged event, void* event_target);
void entitas_world_changed_clear (EntitasWorldChanged* self);
void entitas_world_changed_dispatch (EntitasWorldChanged* self, EntitasWorld* w, EntitasEntity* e);
EntitasWorldChanged* entitas_world_changed_new (void);
EntitasWorldChanged* entitas_world_changed_construct (GType object_type);
GType entitas_world_changed_listener_get_type (void) G_GNUC_CONST;
EntitasWorldChangedListener* entitas_world_changed_listener_new (EntitasOnWorldChanged event, void* event_target);
EntitasWorldChangedListener* entitas_world_changed_listener_construct (GType object_type, EntitasOnWorldChanged event, void* event_target);
EntitasOnWorldChanged entitas_world_changed_listener_get_event (EntitasWorldChangedListener* self, gpointer* result_target);
void entitas_world_changed_listener_set_event (EntitasWorldChangedListener* self, EntitasOnWorldChanged value, gpointer value_target);
GType entitas_imatcher_get_type (void) G_GNUC_CONST;
EntitasGroup* entitas_group_new (EntitasIMatcher* matcher);
EntitasGroup* entitas_group_construct (GType object_type, EntitasIMatcher* matcher);
void entitas_group_handleEntitySilently (EntitasGroup* self, EntitasEntity* entity, GError** error);
void entitas_group_handleEntity (EntitasGroup* self, EntitasEntity* entity, gint index, EntitasIComponent* component, GError** error);
void entitas_group_updateEntity (EntitasGroup* self, EntitasEntity* entity, gint index, EntitasIComponent* previousComponent, EntitasIComponent* newComponent);
void entitas_group_addEntitySilently (EntitasGroup* self, EntitasEntity* entity);
void entitas_group_addEntity (EntitasGroup* self, EntitasEntity* entity, gint index, EntitasIComponent* component);
void entitas_group_removeEntitySilently (EntitasGroup* self, EntitasEntity* entity, GError** error);
void entitas_group_removeEntity (EntitasGroup* self, EntitasEntity* entity, gint index, EntitasIComponent* component, GError** error);
gboolean entitas_group_containsEntity (EntitasGroup* self, EntitasEntity* entity);
EntitasEntity** entitas_group_getEntities (EntitasGroup* self, int* result_length1);
EntitasEntity* entitas_group_getSingleEntity (EntitasGroup* self, GError** error);
gchar* entitas_group_toString (EntitasGroup* self);
EntitasGroupChanged* entitas_group_get_onEntityAdded (EntitasGroup* self);
EntitasGroupChanged* entitas_group_get_onEntityRemoved (EntitasGroup* self);
EntitasGroupUpdated* entitas_group_get_onEntityUpdated (EntitasGroup* self);
gint entitas_group_get_count (EntitasGroup* self);
EntitasIMatcher* entitas_group_get_matcher (EntitasGroup* self);
gboolean entitas_imatcher_matches (EntitasIMatcher* self, EntitasEntity* entity);
gchar* entitas_imatcher_toString (EntitasIMatcher* self);
const gchar* entitas_imatcher_get_id (EntitasIMatcher* self);
gint* entitas_imatcher_get_indices (EntitasIMatcher* self, int* result_length1);
GType entitas_icompound_matcher_get_type (void) G_GNUC_CONST;
gint* entitas_icompound_matcher_get_allOfIndices (EntitasICompoundMatcher* self, int* result_length1);
gint* entitas_icompound_matcher_get_anyOfIndices (EntitasICompoundMatcher* self, int* result_length1);
gint* entitas_icompound_matcher_get_noneOfIndices (EntitasICompoundMatcher* self, int* result_length1);
GType entitas_inone_of_matcher_get_type (void) G_GNUC_CONST;
GType entitas_iany_of_matcher_get_type (void) G_GNUC_CONST;
EntitasINoneOfMatcher* entitas_iany_of_matcher_noneOf (EntitasIAnyOfMatcher* self, gint* args, int args_length1);
GType entitas_iall_of_matcher_get_type (void) G_GNUC_CONST;
EntitasIAnyOfMatcher* entitas_iall_of_matcher_anyOf (EntitasIAllOfMatcher* self, gint* args, int args_length1);
EntitasINoneOfMatcher* entitas_iall_of_matcher_noneOf (EntitasIAllOfMatcher* self, gint* args, int args_length1);
GType entitas_isystem_get_type (void) G_GNUC_CONST;
GType entitas_iset_world_get_type (void) G_GNUC_CONST;
void entitas_iset_world_setWorld (EntitasISetWorld* self, EntitasWorld* world);
GType entitas_iexecute_system_get_type (void) G_GNUC_CONST;
void entitas_iexecute_system_execute (EntitasIExecuteSystem* self);
GType entitas_iinitialize_system_get_type (void) G_GNUC_CONST;
void entitas_iinitialize_system_initialize (EntitasIInitializeSystem* self);
GType entitas_group_event_type_get_type (void) G_GNUC_CONST;
GType entitas_matcher_get_type (void) G_GNUC_CONST;
extern gint entitas_matcher_uniqueId;
EntitasMatcher* entitas_matcher_new (void);
EntitasMatcher* entitas_matcher_construct (GType object_type);
gint* entitas_matcher_mergeIndices (EntitasMatcher* self, int* result_length1);
gchar* entitas_matcher_componentsToString (gint* indexArray, int indexArray_length1);
gint* entitas_matcher_listToArray (GeeArrayList* l, int* result_length1);
gint* entitas_matcher_distinctIndices (gint* indices, int indices_length1, int* result_length1);
gint* entitas_matcher_merge (EntitasIMatcher** matchers, int matchers_length1, int* result_length1, GError** error);
EntitasIMatcher* entitas_matcher_AllOf (gint* args, int args_length1);
EntitasIMatcher* entitas_matcher_AnyOf (gint* args, int args_length1);
gint* entitas_matcher_get_allOfIndices (EntitasMatcher* self, int* result_length1);
gint* entitas_matcher_get_anyOfIndices (EntitasMatcher* self, int* result_length1);
gint* entitas_matcher_get_noneOfIndices (EntitasMatcher* self, int* result_length1);
#define ENTITAS_VERSION "0.0.1"
EntitasWorld* entitas_world_new (gchar** components, int components_length1, gint startCreationIndex);
EntitasWorld* entitas_world_construct (GType object_type, gchar** components, int components_length1, gint startCreationIndex);
EntitasEntity* entitas_world_createEntity (EntitasWorld* self, const gchar* name);
void entitas_world_destroyEntity (EntitasWorld* self, EntitasEntity* entity, GError** error);
void entitas_world_destroyAllEntities (EntitasWorld* self, GError** error);
gboolean entitas_world_hasEntity (EntitasWorld* self, EntitasEntity* entity);
EntitasEntity** entitas_world_getEntities (EntitasWorld* self, EntitasIMatcher* matcher, int* result_length1);
EntitasWorld* entitas_world_add (EntitasWorld* self, EntitasISystem* system);
EntitasWorld* entitas_world_initialize (EntitasWorld* self);
void entitas_world_execute (EntitasWorld* self);
EntitasGroup* entitas_world_getGroup (EntitasWorld* self, EntitasIMatcher* matcher);
void entitas_world_updateGroupsComponentAddedOrRemoved (EntitasWorld* self, EntitasEntity* entity, gint index, EntitasIComponent* component);
void entitas_world_updateGroupsComponentReplaced (EntitasWorld* self, EntitasEntity* entity, gint index, EntitasIComponent* previousComponent, EntitasIComponent* newComponent);
void entitas_world_onEntityReleased (EntitasWorld* self, EntitasEntity* entity);
gchar** entitas_world_get_components (int* result_length1);
EntitasWorld* entitas_world_get_instance (void);
GRand* entitas_world_get_random (void);
gint entitas_world_get_componentsCount (EntitasWorld* self);
gint entitas_world_get_count (EntitasWorld* self);
gint entitas_world_get_reusableEntitiesCount (EntitasWorld* self);
gint entitas_world_get_retainedEntitiesCount (EntitasWorld* self);
EntitasWorldChanged* entitas_world_get_onEntityCreated (EntitasWorld* self);
EntitasWorldChanged* entitas_world_get_onEntityWillBeDestroyed (EntitasWorld* self);
EntitasWorldChanged* entitas_world_get_onEntityDestroyed (EntitasWorld* self);
EntitasGroupsChanged* entitas_world_get_onGroupCreated (EntitasWorld* self);
const gchar* entitas_world_get_name (EntitasWorld* self);


G_END_DECLS

#endif
