/* Exceptions.c generated by valac 0.34.4, the Vala compiler
 * generated from Exceptions.gs, do not modify */


#include <glib.h>
#include <glib-object.h>


typedef enum  {
	ENTITAS_ECS_EXCEPTION_EntityIsNotEnabled,
	ENTITAS_ECS_EXCEPTION_EntityAlreadyHasComponent,
	ENTITAS_ECS_EXCEPTION_EntityDoesNotHaveComponent,
	ENTITAS_ECS_EXCEPTION_EntityIsAlreadyReleased,
	ENTITAS_ECS_EXCEPTION_SingleEntity,
	ENTITAS_ECS_EXCEPTION_Matcher,
	ENTITAS_ECS_EXCEPTION_WorldDoesNotContainEntity
} EntitasEcsException;
#define ENTITAS_ECS_EXCEPTION entitas_ecs_exception_quark ()


GQuark entitas_ecs_exception_quark (void);


GQuark entitas_ecs_exception_quark (void) {
	return g_quark_from_static_string ("entitas_ecs_exception-quark");
}



