/* Matcher.c generated by valac 0.34.4, the Vala compiler
 * generated from Matcher.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define ENTITAS_TYPE_GROUP_EVENT_TYPE (entitas_group_event_type_get_type ())

#define ENTITAS_TYPE_IMATCHER (entitas_imatcher_get_type ())
#define ENTITAS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IMATCHER, EntitasIMatcher))
#define ENTITAS_IS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IMATCHER))
#define ENTITAS_IMATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IMATCHER, EntitasIMatcherIface))

typedef struct _EntitasIMatcher EntitasIMatcher;
typedef struct _EntitasIMatcherIface EntitasIMatcherIface;

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())
#define ENTITAS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ENTITY, EntitasEntity))
#define ENTITAS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_ENTITY, EntitasEntityClass))
#define ENTITAS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ENTITY))
#define ENTITAS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_ENTITY))
#define ENTITAS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_ENTITY, EntitasEntityClass))

typedef struct _EntitasEntity EntitasEntity;
typedef struct _EntitasEntityClass EntitasEntityClass;

#define ENTITAS_TYPE_IALL_OF_MATCHER (entitas_iall_of_matcher_get_type ())
#define ENTITAS_IALL_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IALL_OF_MATCHER, EntitasIAllOfMatcher))
#define ENTITAS_IS_IALL_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IALL_OF_MATCHER))
#define ENTITAS_IALL_OF_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IALL_OF_MATCHER, EntitasIAllOfMatcherIface))

typedef struct _EntitasIAllOfMatcher EntitasIAllOfMatcher;
typedef struct _EntitasIAllOfMatcherIface EntitasIAllOfMatcherIface;

#define ENTITAS_TYPE_IANY_OF_MATCHER (entitas_iany_of_matcher_get_type ())
#define ENTITAS_IANY_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IANY_OF_MATCHER, EntitasIAnyOfMatcher))
#define ENTITAS_IS_IANY_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IANY_OF_MATCHER))
#define ENTITAS_IANY_OF_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IANY_OF_MATCHER, EntitasIAnyOfMatcherIface))

typedef struct _EntitasIAnyOfMatcher EntitasIAnyOfMatcher;
typedef struct _EntitasIAnyOfMatcherIface EntitasIAnyOfMatcherIface;

#define ENTITAS_TYPE_INONE_OF_MATCHER (entitas_inone_of_matcher_get_type ())
#define ENTITAS_INONE_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_INONE_OF_MATCHER, EntitasINoneOfMatcher))
#define ENTITAS_IS_INONE_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_INONE_OF_MATCHER))
#define ENTITAS_INONE_OF_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_INONE_OF_MATCHER, EntitasINoneOfMatcherIface))

typedef struct _EntitasINoneOfMatcher EntitasINoneOfMatcher;
typedef struct _EntitasINoneOfMatcherIface EntitasINoneOfMatcherIface;

#define ENTITAS_TYPE_MATCHER (entitas_matcher_get_type ())
#define ENTITAS_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_MATCHER, EntitasMatcher))
#define ENTITAS_MATCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_MATCHER, EntitasMatcherClass))
#define ENTITAS_IS_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_MATCHER))
#define ENTITAS_IS_MATCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_MATCHER))
#define ENTITAS_MATCHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_MATCHER, EntitasMatcherClass))

typedef struct _EntitasMatcher EntitasMatcher;
typedef struct _EntitasMatcherClass EntitasMatcherClass;
typedef struct _EntitasMatcherPrivate EntitasMatcherPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

typedef enum  {
	ENTITAS_GROUP_EVENT_TYPE_OnEntityAdded,
	ENTITAS_GROUP_EVENT_TYPE_OnEntityRemoved,
	ENTITAS_GROUP_EVENT_TYPE_OnEntityAddedOrRemoved
} EntitasGroupEventType;

struct _EntitasIMatcherIface {
	GTypeInterface parent_iface;
	gboolean (*matches) (EntitasIMatcher* self, EntitasEntity* entity);
	gchar* (*toString) (EntitasIMatcher* self);
	const gchar* (*get_id) (EntitasIMatcher* self);
	gint* (*get_indices) (EntitasIMatcher* self, int* result_length1);
};

struct _EntitasINoneOfMatcherIface {
	GTypeInterface parent_iface;
};

struct _EntitasIAnyOfMatcherIface {
	GTypeInterface parent_iface;
	EntitasINoneOfMatcher* (*noneOf) (EntitasIAnyOfMatcher* self, gint* args, int args_length1);
};

struct _EntitasIAllOfMatcherIface {
	GTypeInterface parent_iface;
	EntitasIAnyOfMatcher* (*anyOf) (EntitasIAllOfMatcher* self, gint* args, int args_length1);
	EntitasINoneOfMatcher* (*noneOf) (EntitasIAllOfMatcher* self, gint* args, int args_length1);
};

struct _EntitasMatcher {
	GObject parent_instance;
	EntitasMatcherPrivate * priv;
};

struct _EntitasMatcherClass {
	GObjectClass parent_class;
};

struct _EntitasMatcherPrivate {
	gchar* _id;
	gint* _allOfIndices;
	gint _allOfIndices_length1;
	gint __allOfIndices_size_;
	gint* _anyOfIndices;
	gint _anyOfIndices_length1;
	gint __anyOfIndices_size_;
	gint* _noneOfIndices;
	gint _noneOfIndices_length1;
	gint __noneOfIndices_size_;
	gint* _indices;
	gint _indices_length1;
	gint __indices_size_;
	gchar* _toStringCache;
};

typedef enum  {
	ENTITAS_ECS_EXCEPTION_EntityIsNotEnabled,
	ENTITAS_ECS_EXCEPTION_EntityAlreadyHasComponent,
	ENTITAS_ECS_EXCEPTION_EntityDoesNotHaveComponent,
	ENTITAS_ECS_EXCEPTION_EntityIsAlreadyReleased,
	ENTITAS_ECS_EXCEPTION_SingleEntity,
	ENTITAS_ECS_EXCEPTION_Matcher,
	ENTITAS_ECS_EXCEPTION_WorldDoesNotContainEntity
} EntitasEcsException;
#define ENTITAS_ECS_EXCEPTION entitas_ecs_exception_quark ()

static gpointer entitas_matcher_parent_class = NULL;
extern gint entitas_matcher_uniqueId;
gint entitas_matcher_uniqueId = 0;
static EntitasIMatcherIface* entitas_matcher_entitas_imatcher_parent_iface = NULL;
static EntitasIAllOfMatcherIface* entitas_matcher_entitas_iall_of_matcher_parent_iface = NULL;
static EntitasIAnyOfMatcherIface* entitas_matcher_entitas_iany_of_matcher_parent_iface = NULL;
static EntitasINoneOfMatcherIface* entitas_matcher_entitas_inone_of_matcher_parent_iface = NULL;

GType entitas_group_event_type_get_type (void) G_GNUC_CONST;
GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_imatcher_get_type (void) G_GNUC_CONST;
GType entitas_inone_of_matcher_get_type (void) G_GNUC_CONST;
GType entitas_iany_of_matcher_get_type (void) G_GNUC_CONST;
GType entitas_iall_of_matcher_get_type (void) G_GNUC_CONST;
GType entitas_matcher_get_type (void) G_GNUC_CONST;
#define ENTITAS_MATCHER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ENTITAS_TYPE_MATCHER, EntitasMatcherPrivate))
enum  {
	ENTITAS_MATCHER_DUMMY_PROPERTY,
	ENTITAS_MATCHER_ID
};
EntitasMatcher* entitas_matcher_new (void);
EntitasMatcher* entitas_matcher_construct (GType object_type);
static EntitasIAnyOfMatcher* entitas_matcher_real_anyOf (EntitasIAllOfMatcher* base, gint* args, int args_length1);
gint* entitas_matcher_distinctIndices (gint* indices, int indices_length1, int* result_length1);
static EntitasINoneOfMatcher* entitas_matcher_real_noneOf (EntitasIAllOfMatcher* base, gint* args, int args_length1);
static gboolean entitas_matcher_real_matches (EntitasIMatcher* base, EntitasEntity* entity);
gboolean entitas_entity_hasComponents (EntitasEntity* self, gint* indices, int indices_length1);
gboolean entitas_entity_hasAnyComponent (EntitasEntity* self, gint* indices, int indices_length1);
gint* entitas_matcher_mergeIndices (EntitasMatcher* self, int* result_length1);
gint* entitas_matcher_listToArray (GeeArrayList* l, int* result_length1);
static gchar* entitas_matcher_real_toString (EntitasIMatcher* base);
static void _vala_array_add4 (gchar*** array, int* length, int* size, gchar* value);
gchar* entitas_matcher_componentsToString (gint* indexArray, int indexArray_length1);
static void _vala_array_add5 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add6 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add7 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add8 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add9 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add10 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add11 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add12 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add13 (gchar*** array, int* length, int* size, gchar* value);
gchar** entitas_world_get_components (int* result_length1);
static void _vala_array_add14 (gchar*** array, int* length, int* size, gchar* value);
GQuark entitas_ecs_exception_quark (void);
gint* entitas_matcher_merge (EntitasIMatcher** matchers, int matchers_length1, int* result_length1, GError** error);
gint* entitas_imatcher_get_indices (EntitasIMatcher* self, int* result_length1);
gchar* entitas_imatcher_toString (EntitasIMatcher* self);
EntitasIMatcher* entitas_matcher_AllOf (gint* args, int args_length1);
EntitasIMatcher* entitas_matcher_AnyOf (gint* args, int args_length1);
gint* entitas_matcher_get_allOfIndices (EntitasMatcher* self, int* result_length1);
gint* entitas_matcher_get_anyOfIndices (EntitasMatcher* self, int* result_length1);
gint* entitas_matcher_get_noneOfIndices (EntitasMatcher* self, int* result_length1);
static void entitas_matcher_finalize (GObject* obj);
const gchar* entitas_imatcher_get_id (EntitasIMatcher* self);
static void _vala_entitas_matcher_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


/**
     * Event Types
     * @readonly
     * @enum number
     */
GType entitas_group_event_type_get_type (void) {
	static volatile gsize entitas_group_event_type_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_group_event_type_type_id__volatile)) {
		static const GEnumValue values[] = {{ENTITAS_GROUP_EVENT_TYPE_OnEntityAdded, "ENTITAS_GROUP_EVENT_TYPE_OnEntityAdded", "onentityadded"}, {ENTITAS_GROUP_EVENT_TYPE_OnEntityRemoved, "ENTITAS_GROUP_EVENT_TYPE_OnEntityRemoved", "onentityremoved"}, {ENTITAS_GROUP_EVENT_TYPE_OnEntityAddedOrRemoved, "ENTITAS_GROUP_EVENT_TYPE_OnEntityAddedOrRemoved", "onentityaddedorremoved"}, {0, NULL, NULL}};
		GType entitas_group_event_type_type_id;
		entitas_group_event_type_type_id = g_enum_register_static ("EntitasGroupEventType", values);
		g_once_init_leave (&entitas_group_event_type_type_id__volatile, entitas_group_event_type_type_id);
	}
	return entitas_group_event_type_type_id__volatile;
}


EntitasMatcher* entitas_matcher_construct (GType object_type) {
	EntitasMatcher * self = NULL;
	gint _tmp0_ = 0;
	gchar* _tmp1_ = NULL;
	self = (EntitasMatcher*) g_object_new (object_type, NULL);
	_tmp0_ = entitas_matcher_uniqueId;
	entitas_matcher_uniqueId = _tmp0_ + 1;
	_tmp1_ = g_strdup_printf ("%i", _tmp0_);
	_g_free0 (self->priv->_id);
	self->priv->_id = _tmp1_;
	return self;
}


EntitasMatcher* entitas_matcher_new (void) {
	return entitas_matcher_construct (ENTITAS_TYPE_MATCHER);
}


/**
         * Matches anyOf the components/indices specified
         * @params Array<entitas.IMatcher>|Array<number> args
         * @returns entitas.Matcher
         */
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static EntitasIAnyOfMatcher* entitas_matcher_real_anyOf (EntitasIAllOfMatcher* base, gint* args, int args_length1) {
	EntitasMatcher * self;
	EntitasIAnyOfMatcher* result = NULL;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	gint* _tmp2_ = NULL;
	EntitasIAnyOfMatcher* _tmp3_ = NULL;
	self = (EntitasMatcher*) base;
	_tmp0_ = args;
	_tmp0__length1 = args_length1;
	_tmp2_ = entitas_matcher_distinctIndices (_tmp0_, _tmp0__length1, &_tmp1_);
	self->priv->_anyOfIndices = (g_free (self->priv->_anyOfIndices), NULL);
	self->priv->_anyOfIndices = _tmp2_;
	self->priv->_anyOfIndices_length1 = _tmp1_;
	self->priv->__anyOfIndices_size_ = self->priv->_anyOfIndices_length1;
	self->priv->_indices = (g_free (self->priv->_indices), NULL);
	self->priv->_indices = NULL;
	self->priv->_indices_length1 = 0;
	self->priv->__indices_size_ = self->priv->_indices_length1;
	_tmp3_ = _g_object_ref0 ((EntitasIAnyOfMatcher*) self);
	result = _tmp3_;
	return result;
}


/**
         * Matches noneOf the components/indices specified
         * @params Array<entitas.IMatcher>|Array<number> args
         * @returns entitas.Matcher
         */
static EntitasINoneOfMatcher* entitas_matcher_real_noneOf (EntitasIAllOfMatcher* base, gint* args, int args_length1) {
	EntitasMatcher * self;
	EntitasINoneOfMatcher* result = NULL;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	gint* _tmp2_ = NULL;
	EntitasINoneOfMatcher* _tmp3_ = NULL;
	self = (EntitasMatcher*) base;
	_tmp0_ = args;
	_tmp0__length1 = args_length1;
	_tmp2_ = entitas_matcher_distinctIndices (_tmp0_, _tmp0__length1, &_tmp1_);
	self->priv->_noneOfIndices = (g_free (self->priv->_noneOfIndices), NULL);
	self->priv->_noneOfIndices = _tmp2_;
	self->priv->_noneOfIndices_length1 = _tmp1_;
	self->priv->__noneOfIndices_size_ = self->priv->_noneOfIndices_length1;
	self->priv->_indices = (g_free (self->priv->_indices), NULL);
	self->priv->_indices = NULL;
	self->priv->_indices_length1 = 0;
	self->priv->__indices_size_ = self->priv->_indices_length1;
	_tmp3_ = _g_object_ref0 ((EntitasINoneOfMatcher*) self);
	result = _tmp3_;
	return result;
}


/**
         * Check if the entity matches this matcher
         * @param entitas.Entity entity
         * @returns boolean
         */
static gboolean entitas_matcher_real_matches (EntitasIMatcher* base, EntitasEntity* entity) {
	EntitasMatcher * self;
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gboolean matchesAllOf = FALSE;
	gboolean _tmp5_ = FALSE;
	gint* _tmp6_ = NULL;
	gint _tmp6__length1 = 0;
	gboolean matchesAnyOf = FALSE;
	gboolean _tmp10_ = FALSE;
	gint* _tmp11_ = NULL;
	gint _tmp11__length1 = 0;
	gboolean matchesNoneOf = FALSE;
	gboolean _tmp15_ = FALSE;
	gboolean _tmp16_ = FALSE;
	gboolean _tmp17_ = FALSE;
	self = (EntitasMatcher*) base;
	g_return_val_if_fail (entity != NULL, FALSE);
	_tmp1_ = self->priv->_allOfIndices;
	_tmp1__length1 = self->priv->_allOfIndices_length1;
	if (_tmp1_ == NULL) {
		_tmp0_ = TRUE;
	} else {
		EntitasEntity* _tmp2_ = NULL;
		gint* _tmp3_ = NULL;
		gint _tmp3__length1 = 0;
		gboolean _tmp4_ = FALSE;
		_tmp2_ = entity;
		_tmp3_ = self->priv->_allOfIndices;
		_tmp3__length1 = self->priv->_allOfIndices_length1;
		_tmp4_ = entitas_entity_hasComponents (_tmp2_, _tmp3_, _tmp3__length1);
		_tmp0_ = _tmp4_;
	}
	matchesAllOf = _tmp0_;
	_tmp6_ = self->priv->_anyOfIndices;
	_tmp6__length1 = self->priv->_anyOfIndices_length1;
	if (_tmp6_ == NULL) {
		_tmp5_ = TRUE;
	} else {
		EntitasEntity* _tmp7_ = NULL;
		gint* _tmp8_ = NULL;
		gint _tmp8__length1 = 0;
		gboolean _tmp9_ = FALSE;
		_tmp7_ = entity;
		_tmp8_ = self->priv->_anyOfIndices;
		_tmp8__length1 = self->priv->_anyOfIndices_length1;
		_tmp9_ = entitas_entity_hasAnyComponent (_tmp7_, _tmp8_, _tmp8__length1);
		_tmp5_ = _tmp9_;
	}
	matchesAnyOf = _tmp5_;
	_tmp11_ = self->priv->_noneOfIndices;
	_tmp11__length1 = self->priv->_noneOfIndices_length1;
	if (_tmp11_ == NULL) {
		_tmp10_ = TRUE;
	} else {
		EntitasEntity* _tmp12_ = NULL;
		gint* _tmp13_ = NULL;
		gint _tmp13__length1 = 0;
		gboolean _tmp14_ = FALSE;
		_tmp12_ = entity;
		_tmp13_ = self->priv->_noneOfIndices;
		_tmp13__length1 = self->priv->_noneOfIndices_length1;
		_tmp14_ = entitas_entity_hasAnyComponent (_tmp12_, _tmp13_, _tmp13__length1);
		_tmp10_ = !_tmp14_;
	}
	matchesNoneOf = _tmp10_;
	_tmp17_ = matchesAllOf;
	if (_tmp17_) {
		gboolean _tmp18_ = FALSE;
		_tmp18_ = matchesAnyOf;
		_tmp16_ = _tmp18_;
	} else {
		_tmp16_ = FALSE;
	}
	if (_tmp16_) {
		gboolean _tmp19_ = FALSE;
		_tmp19_ = matchesNoneOf;
		_tmp15_ = _tmp19_;
	} else {
		_tmp15_ = FALSE;
	}
	result = _tmp15_;
	return result;
}


/**
         * Merge list of component indices
         * @returns Array<number>
         */
gint* entitas_matcher_mergeIndices (EntitasMatcher* self, int* result_length1) {
	gint* result = NULL;
	GeeArrayList* indicesList = NULL;
	GeeArrayList* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint* _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	gint* _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	GeeArrayList* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	gint* _tmp15_ = NULL;
	gint* _tmp16_ = NULL;
	gint _tmp16__length1 = 0;
	gint _tmp17_ = 0;
	gint* _tmp18_ = NULL;
	gint* _tmp19_ = NULL;
	gint _tmp19__length1 = 0;
	gint* _tmp20_ = NULL;
	gint _tmp20__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = gee_array_list_new (G_TYPE_INT, NULL, NULL, NULL, NULL, NULL);
	indicesList = _tmp0_;
	_tmp1_ = self->priv->_allOfIndices;
	_tmp1__length1 = self->priv->_allOfIndices_length1;
	if (_tmp1_ != NULL) {
		gint* _tmp2_ = NULL;
		gint _tmp2__length1 = 0;
		_tmp2_ = self->priv->_allOfIndices;
		_tmp2__length1 = self->priv->_allOfIndices_length1;
		{
			gint* i_collection = NULL;
			gint i_collection_length1 = 0;
			gint _i_collection_size_ = 0;
			gint i_it = 0;
			i_collection = _tmp2_;
			i_collection_length1 = _tmp2__length1;
			for (i_it = 0; i_it < _tmp2__length1; i_it = i_it + 1) {
				gint i = 0;
				i = i_collection[i_it];
				{
					GeeArrayList* _tmp3_ = NULL;
					gint _tmp4_ = 0;
					_tmp3_ = indicesList;
					_tmp4_ = i;
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp3_, (gpointer) ((gintptr) _tmp4_));
				}
			}
		}
	}
	_tmp5_ = self->priv->_anyOfIndices;
	_tmp5__length1 = self->priv->_anyOfIndices_length1;
	if (_tmp5_ != NULL) {
		gint* _tmp6_ = NULL;
		gint _tmp6__length1 = 0;
		_tmp6_ = self->priv->_anyOfIndices;
		_tmp6__length1 = self->priv->_anyOfIndices_length1;
		{
			gint* i_collection = NULL;
			gint i_collection_length1 = 0;
			gint _i_collection_size_ = 0;
			gint i_it = 0;
			i_collection = _tmp6_;
			i_collection_length1 = _tmp6__length1;
			for (i_it = 0; i_it < _tmp6__length1; i_it = i_it + 1) {
				gint i = 0;
				i = i_collection[i_it];
				{
					GeeArrayList* _tmp7_ = NULL;
					gint _tmp8_ = 0;
					_tmp7_ = indicesList;
					_tmp8_ = i;
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp7_, (gpointer) ((gintptr) _tmp8_));
				}
			}
		}
	}
	_tmp9_ = self->priv->_noneOfIndices;
	_tmp9__length1 = self->priv->_noneOfIndices_length1;
	if (_tmp9_ != NULL) {
		gint* _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		_tmp10_ = self->priv->_noneOfIndices;
		_tmp10__length1 = self->priv->_noneOfIndices_length1;
		{
			gint* i_collection = NULL;
			gint i_collection_length1 = 0;
			gint _i_collection_size_ = 0;
			gint i_it = 0;
			i_collection = _tmp10_;
			i_collection_length1 = _tmp10__length1;
			for (i_it = 0; i_it < _tmp10__length1; i_it = i_it + 1) {
				gint i = 0;
				i = i_collection[i_it];
				{
					GeeArrayList* _tmp11_ = NULL;
					gint _tmp12_ = 0;
					_tmp11_ = indicesList;
					_tmp12_ = i;
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp11_, (gpointer) ((gintptr) _tmp12_));
				}
			}
		}
	}
	_tmp13_ = indicesList;
	_tmp15_ = entitas_matcher_listToArray (_tmp13_, &_tmp14_);
	_tmp16_ = _tmp15_;
	_tmp16__length1 = _tmp14_;
	_tmp18_ = entitas_matcher_distinctIndices (_tmp16_, _tmp14_, &_tmp17_);
	_tmp19_ = _tmp18_;
	_tmp19__length1 = _tmp17_;
	_tmp16_ = (g_free (_tmp16_), NULL);
	_tmp20_ = _tmp19_;
	_tmp20__length1 = _tmp19__length1;
	if (result_length1) {
		*result_length1 = _tmp20__length1;
	}
	result = _tmp20_;
	_g_object_unref0 (indicesList);
	return result;
}


/**
         * toString representation of this matcher
         * @returns string
         */
static void _vala_array_add4 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add5 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add6 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add7 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add8 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add9 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add10 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add11 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add12 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add13 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static gchar* _vala_g_strjoinv (const gchar* separator, gchar** str_array, int str_array_length1) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gchar** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	_tmp0_ = separator;
	if (_tmp0_ == NULL) {
		separator = "";
	}
	_tmp3_ = str_array;
	_tmp3__length1 = str_array_length1;
	if (_tmp3_ != NULL) {
		_tmp2_ = TRUE;
	} else {
		gchar** _tmp4_ = NULL;
		gint _tmp4__length1 = 0;
		_tmp4_ = str_array;
		_tmp4__length1 = str_array_length1;
		_tmp2_ = _tmp4__length1 > 0;
	}
	if (_tmp2_) {
		_tmp1_ = TRUE;
	} else {
		gboolean _tmp5_ = FALSE;
		gchar** _tmp6_ = NULL;
		gint _tmp6__length1 = 0;
		_tmp6_ = str_array;
		_tmp6__length1 = str_array_length1;
		if (_tmp6__length1 == -1) {
			gchar** _tmp7_ = NULL;
			gint _tmp7__length1 = 0;
			const gchar* _tmp8_ = NULL;
			_tmp7_ = str_array;
			_tmp7__length1 = str_array_length1;
			_tmp8_ = _tmp7_[0];
			_tmp5_ = _tmp8_ != NULL;
		} else {
			_tmp5_ = FALSE;
		}
		_tmp1_ = _tmp5_;
	}
	if (_tmp1_) {
		gint i = 0;
		gsize len = 0UL;
		gint _tmp31_ = 0;
		gint _tmp33_ = 0;
		gint _tmp34_ = 0;
		gsize _tmp35_ = 0UL;
		const gchar* _tmp36_ = NULL;
		gint _tmp37_ = 0;
		gint _tmp38_ = 0;
		gint _tmp39_ = 0;
		const gchar* res = NULL;
		gsize _tmp40_ = 0UL;
		void* _tmp41_ = NULL;
		void* ptr = NULL;
		const gchar* _tmp42_ = NULL;
		gchar** _tmp43_ = NULL;
		gint _tmp43__length1 = 0;
		const gchar* _tmp44_ = NULL;
		void* _tmp45_ = NULL;
		const gchar* _tmp62_ = NULL;
		len = (gsize) 1;
		{
			gboolean _tmp9_ = FALSE;
			i = 0;
			_tmp9_ = TRUE;
			while (TRUE) {
				gboolean _tmp11_ = FALSE;
				gboolean _tmp12_ = FALSE;
				gchar** _tmp13_ = NULL;
				gint _tmp13__length1 = 0;
				gint _tmp21_ = 0;
				gchar** _tmp22_ = NULL;
				gint _tmp22__length1 = 0;
				gint _tmp23_ = 0;
				const gchar* _tmp24_ = NULL;
				gsize _tmp30_ = 0UL;
				if (!_tmp9_) {
					gint _tmp10_ = 0;
					_tmp10_ = i;
					i = _tmp10_ + 1;
				}
				_tmp9_ = FALSE;
				_tmp13_ = str_array;
				_tmp13__length1 = str_array_length1;
				if (_tmp13__length1 != -1) {
					gint _tmp14_ = 0;
					gchar** _tmp15_ = NULL;
					gint _tmp15__length1 = 0;
					_tmp14_ = i;
					_tmp15_ = str_array;
					_tmp15__length1 = str_array_length1;
					_tmp12_ = _tmp14_ < _tmp15__length1;
				} else {
					_tmp12_ = FALSE;
				}
				if (_tmp12_) {
					_tmp11_ = TRUE;
				} else {
					gboolean _tmp16_ = FALSE;
					gchar** _tmp17_ = NULL;
					gint _tmp17__length1 = 0;
					_tmp17_ = str_array;
					_tmp17__length1 = str_array_length1;
					if (_tmp17__length1 == -1) {
						gchar** _tmp18_ = NULL;
						gint _tmp18__length1 = 0;
						gint _tmp19_ = 0;
						const gchar* _tmp20_ = NULL;
						_tmp18_ = str_array;
						_tmp18__length1 = str_array_length1;
						_tmp19_ = i;
						_tmp20_ = _tmp18_[_tmp19_];
						_tmp16_ = _tmp20_ != NULL;
					} else {
						_tmp16_ = FALSE;
					}
					_tmp11_ = _tmp16_;
				}
				if (!_tmp11_) {
					break;
				}
				_tmp22_ = str_array;
				_tmp22__length1 = str_array_length1;
				_tmp23_ = i;
				_tmp24_ = _tmp22_[_tmp23_];
				if (_tmp24_ != NULL) {
					gchar** _tmp25_ = NULL;
					gint _tmp25__length1 = 0;
					gint _tmp26_ = 0;
					const gchar* _tmp27_ = NULL;
					gint _tmp28_ = 0;
					gint _tmp29_ = 0;
					_tmp25_ = str_array;
					_tmp25__length1 = str_array_length1;
					_tmp26_ = i;
					_tmp27_ = _tmp25_[_tmp26_];
					_tmp28_ = strlen ((const gchar*) _tmp27_);
					_tmp29_ = _tmp28_;
					_tmp21_ = _tmp29_;
				} else {
					_tmp21_ = 0;
				}
				_tmp30_ = len;
				len = _tmp30_ + _tmp21_;
			}
		}
		_tmp31_ = i;
		if (_tmp31_ == 0) {
			gchar* _tmp32_ = NULL;
			_tmp32_ = g_strdup ("");
			result = _tmp32_;
			return result;
		}
		_tmp33_ = i;
		str_array_length1 = _tmp33_;
		_tmp34_ = str_array_length1;
		_tmp35_ = len;
		_tmp36_ = separator;
		_tmp37_ = strlen ((const gchar*) _tmp36_);
		_tmp38_ = _tmp37_;
		_tmp39_ = i;
		len = _tmp35_ + (_tmp38_ * (_tmp39_ - 1));
		_tmp40_ = len;
		_tmp41_ = g_malloc (_tmp40_);
		res = _tmp41_;
		_tmp42_ = res;
		_tmp43_ = str_array;
		_tmp43__length1 = str_array_length1;
		_tmp44_ = _tmp43_[0];
		_tmp45_ = g_stpcpy ((void*) _tmp42_, (const gchar*) _tmp44_);
		ptr = _tmp45_;
		{
			gboolean _tmp46_ = FALSE;
			i = 1;
			_tmp46_ = TRUE;
			while (TRUE) {
				gint _tmp48_ = 0;
				gchar** _tmp49_ = NULL;
				gint _tmp49__length1 = 0;
				void* _tmp50_ = NULL;
				const gchar* _tmp51_ = NULL;
				void* _tmp52_ = NULL;
				const gchar* _tmp53_ = NULL;
				gchar** _tmp54_ = NULL;
				gint _tmp54__length1 = 0;
				gint _tmp55_ = 0;
				const gchar* _tmp56_ = NULL;
				void* _tmp60_ = NULL;
				void* _tmp61_ = NULL;
				if (!_tmp46_) {
					gint _tmp47_ = 0;
					_tmp47_ = i;
					i = _tmp47_ + 1;
				}
				_tmp46_ = FALSE;
				_tmp48_ = i;
				_tmp49_ = str_array;
				_tmp49__length1 = str_array_length1;
				if (!(_tmp48_ < _tmp49__length1)) {
					break;
				}
				_tmp50_ = ptr;
				_tmp51_ = separator;
				_tmp52_ = g_stpcpy (_tmp50_, (const gchar*) _tmp51_);
				ptr = _tmp52_;
				_tmp54_ = str_array;
				_tmp54__length1 = str_array_length1;
				_tmp55_ = i;
				_tmp56_ = _tmp54_[_tmp55_];
				if (_tmp56_ != NULL) {
					gchar** _tmp57_ = NULL;
					gint _tmp57__length1 = 0;
					gint _tmp58_ = 0;
					const gchar* _tmp59_ = NULL;
					_tmp57_ = str_array;
					_tmp57__length1 = str_array_length1;
					_tmp58_ = i;
					_tmp59_ = _tmp57_[_tmp58_];
					_tmp53_ = (const gchar*) _tmp59_;
				} else {
					_tmp53_ = "";
				}
				_tmp60_ = ptr;
				_tmp61_ = g_stpcpy (_tmp60_, _tmp53_);
				ptr = _tmp61_;
			}
		}
		_tmp62_ = res;
		res = NULL;
		result = (gchar*) _tmp62_;
		return result;
	} else {
		gchar* _tmp63_ = NULL;
		_tmp63_ = g_strdup ("");
		result = _tmp63_;
		return result;
	}
}


static gchar* entitas_matcher_real_toString (EntitasIMatcher* base) {
	EntitasMatcher * self;
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	self = (EntitasMatcher*) base;
	_tmp0_ = self->priv->_toStringCache;
	if (_tmp0_ == NULL) {
		gchar** sb = NULL;
		gchar** _tmp1_ = NULL;
		gint sb_length1 = 0;
		gint _sb_size_ = 0;
		gint* _tmp2_ = NULL;
		gint _tmp2__length1 = 0;
		gint* _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		gint* _tmp21_ = NULL;
		gint _tmp21__length1 = 0;
		gchar** _tmp29_ = NULL;
		gint _tmp29__length1 = 0;
		gchar* _tmp30_ = NULL;
		_tmp1_ = g_new0 (gchar*, 0 + 1);
		sb = _tmp1_;
		sb_length1 = 0;
		_sb_size_ = sb_length1;
		_tmp2_ = self->priv->_allOfIndices;
		_tmp2__length1 = self->priv->_allOfIndices_length1;
		if (_tmp2_ != NULL) {
			gchar** _tmp3_ = NULL;
			gint _tmp3__length1 = 0;
			gchar* _tmp4_ = NULL;
			gchar** _tmp5_ = NULL;
			gint _tmp5__length1 = 0;
			gint* _tmp6_ = NULL;
			gint _tmp6__length1 = 0;
			gchar* _tmp7_ = NULL;
			gchar** _tmp8_ = NULL;
			gint _tmp8__length1 = 0;
			gchar* _tmp9_ = NULL;
			_tmp3_ = sb;
			_tmp3__length1 = sb_length1;
			_tmp4_ = g_strdup ("AllOf(");
			_vala_array_add4 (&sb, &sb_length1, &_sb_size_, _tmp4_);
			_tmp5_ = sb;
			_tmp5__length1 = sb_length1;
			_tmp6_ = self->priv->_allOfIndices;
			_tmp6__length1 = self->priv->_allOfIndices_length1;
			_tmp7_ = entitas_matcher_componentsToString (_tmp6_, _tmp6__length1);
			_vala_array_add5 (&sb, &sb_length1, &_sb_size_, _tmp7_);
			_tmp8_ = sb;
			_tmp8__length1 = sb_length1;
			_tmp9_ = g_strdup (")");
			_vala_array_add6 (&sb, &sb_length1, &_sb_size_, _tmp9_);
		}
		_tmp10_ = self->priv->_anyOfIndices;
		_tmp10__length1 = self->priv->_anyOfIndices_length1;
		if (_tmp10_ != NULL) {
			gint* _tmp11_ = NULL;
			gint _tmp11__length1 = 0;
			gchar** _tmp14_ = NULL;
			gint _tmp14__length1 = 0;
			gchar* _tmp15_ = NULL;
			gchar** _tmp16_ = NULL;
			gint _tmp16__length1 = 0;
			gint* _tmp17_ = NULL;
			gint _tmp17__length1 = 0;
			gchar* _tmp18_ = NULL;
			gchar** _tmp19_ = NULL;
			gint _tmp19__length1 = 0;
			gchar* _tmp20_ = NULL;
			_tmp11_ = self->priv->_allOfIndices;
			_tmp11__length1 = self->priv->_allOfIndices_length1;
			if (_tmp11_ != NULL) {
				gchar** _tmp12_ = NULL;
				gint _tmp12__length1 = 0;
				gchar* _tmp13_ = NULL;
				_tmp12_ = sb;
				_tmp12__length1 = sb_length1;
				_tmp13_ = g_strdup (".");
				_vala_array_add7 (&sb, &sb_length1, &_sb_size_, _tmp13_);
			}
			_tmp14_ = sb;
			_tmp14__length1 = sb_length1;
			_tmp15_ = g_strdup ("AnyOf(");
			_vala_array_add8 (&sb, &sb_length1, &_sb_size_, _tmp15_);
			_tmp16_ = sb;
			_tmp16__length1 = sb_length1;
			_tmp17_ = self->priv->_anyOfIndices;
			_tmp17__length1 = self->priv->_anyOfIndices_length1;
			_tmp18_ = entitas_matcher_componentsToString (_tmp17_, _tmp17__length1);
			_vala_array_add9 (&sb, &sb_length1, &_sb_size_, _tmp18_);
			_tmp19_ = sb;
			_tmp19__length1 = sb_length1;
			_tmp20_ = g_strdup (")");
			_vala_array_add10 (&sb, &sb_length1, &_sb_size_, _tmp20_);
		}
		_tmp21_ = self->priv->_noneOfIndices;
		_tmp21__length1 = self->priv->_noneOfIndices_length1;
		if (_tmp21_ != NULL) {
			gchar** _tmp22_ = NULL;
			gint _tmp22__length1 = 0;
			gchar* _tmp23_ = NULL;
			gchar** _tmp24_ = NULL;
			gint _tmp24__length1 = 0;
			gint* _tmp25_ = NULL;
			gint _tmp25__length1 = 0;
			gchar* _tmp26_ = NULL;
			gchar** _tmp27_ = NULL;
			gint _tmp27__length1 = 0;
			gchar* _tmp28_ = NULL;
			_tmp22_ = sb;
			_tmp22__length1 = sb_length1;
			_tmp23_ = g_strdup (".NoneOf(");
			_vala_array_add11 (&sb, &sb_length1, &_sb_size_, _tmp23_);
			_tmp24_ = sb;
			_tmp24__length1 = sb_length1;
			_tmp25_ = self->priv->_noneOfIndices;
			_tmp25__length1 = self->priv->_noneOfIndices_length1;
			_tmp26_ = entitas_matcher_componentsToString (_tmp25_, _tmp25__length1);
			_vala_array_add12 (&sb, &sb_length1, &_sb_size_, _tmp26_);
			_tmp27_ = sb;
			_tmp27__length1 = sb_length1;
			_tmp28_ = g_strdup (")");
			_vala_array_add13 (&sb, &sb_length1, &_sb_size_, _tmp28_);
		}
		_tmp29_ = sb;
		_tmp29__length1 = sb_length1;
		_tmp30_ = _vala_g_strjoinv ("", _tmp29_, _tmp29__length1);
		_g_free0 (self->priv->_toStringCache);
		self->priv->_toStringCache = _tmp30_;
		sb = (_vala_array_free (sb, sb_length1, (GDestroyNotify) g_free), NULL);
	}
	_tmp31_ = self->priv->_toStringCache;
	_tmp32_ = g_strdup (_tmp31_);
	result = _tmp32_;
	return result;
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		GRegex* regex = NULL;
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		GRegex* _tmp3_ = NULL;
		GRegex* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GRegex* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch2_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp6_ = regex;
		_tmp7_ = replacement;
		_tmp8_ = g_regex_replace_literal (_tmp6_, self, (gssize) -1, 0, _tmp7_, 0, &_inner_error_);
		_tmp5_ = _tmp8_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch2_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp9_ = _tmp5_;
		_tmp5_ = NULL;
		result = _tmp9_;
		_g_free0 (_tmp5_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally2;
	__catch2_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally2:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static void _vala_array_add14 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


gchar* entitas_matcher_componentsToString (gint* indexArray, int indexArray_length1) {
	gchar* result = NULL;
	gchar** sb = NULL;
	gchar** _tmp0_ = NULL;
	gint sb_length1 = 0;
	gint _sb_size_ = 0;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gchar** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	gchar* _tmp9_ = NULL;
	_tmp0_ = g_new0 (gchar*, 0 + 1);
	sb = _tmp0_;
	sb_length1 = 0;
	_sb_size_ = sb_length1;
	_tmp1_ = indexArray;
	_tmp1__length1 = indexArray_length1;
	{
		gint* index_collection = NULL;
		gint index_collection_length1 = 0;
		gint _index_collection_size_ = 0;
		gint index_it = 0;
		index_collection = _tmp1_;
		index_collection_length1 = _tmp1__length1;
		for (index_it = 0; index_it < _tmp1__length1; index_it = index_it + 1) {
			gint index = 0;
			index = index_collection[index_it];
			{
				gchar** _tmp2_ = NULL;
				gint _tmp2__length1 = 0;
				gchar** _tmp3_ = NULL;
				gint _tmp3__length1 = 0;
				gchar** _tmp4_ = NULL;
				gint _tmp4__length1 = 0;
				gint _tmp5_ = 0;
				const gchar* _tmp6_ = NULL;
				gchar* _tmp7_ = NULL;
				_tmp2_ = sb;
				_tmp2__length1 = sb_length1;
				_tmp3_ = entitas_world_get_components (&_tmp3__length1);
				_tmp4_ = _tmp3_;
				_tmp4__length1 = _tmp3__length1;
				_tmp5_ = index;
				_tmp6_ = _tmp4_[_tmp5_ - 1];
				_tmp7_ = string_replace (_tmp6_, "Component", "");
				_vala_array_add14 (&sb, &sb_length1, &_sb_size_, _tmp7_);
			}
		}
	}
	_tmp8_ = sb;
	_tmp8__length1 = sb_length1;
	_tmp9_ = _vala_g_strjoinv (",", _tmp8_, _tmp8__length1);
	result = _tmp9_;
	sb = (_vala_array_free (sb, sb_length1, (GDestroyNotify) g_free), NULL);
	return result;
}


gint* entitas_matcher_listToArray (GeeArrayList* l, int* result_length1) {
	gint* result = NULL;
	gint* a = NULL;
	GeeArrayList* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint* _tmp3_ = NULL;
	gint a_length1 = 0;
	gint _a_size_ = 0;
	gint* _tmp15_ = NULL;
	gint _tmp15__length1 = 0;
	g_return_val_if_fail (l != NULL, NULL);
	_tmp0_ = l;
	_tmp1_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_new0 (gint, _tmp2_);
	a = _tmp3_;
	a_length1 = _tmp2_;
	_a_size_ = a_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp4_ = FALSE;
			_tmp4_ = TRUE;
			while (TRUE) {
				GeeArrayList* _tmp6_ = NULL;
				gint _tmp7_ = 0;
				gint _tmp8_ = 0;
				gint* _tmp9_ = NULL;
				gint _tmp9__length1 = 0;
				gint _tmp10_ = 0;
				GeeArrayList* _tmp11_ = NULL;
				gint _tmp12_ = 0;
				gpointer _tmp13_ = NULL;
				gint _tmp14_ = 0;
				if (!_tmp4_) {
					gint _tmp5_ = 0;
					_tmp5_ = i;
					i = _tmp5_ + 1;
				}
				_tmp4_ = FALSE;
				_tmp6_ = l;
				_tmp7_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp6_);
				_tmp8_ = _tmp7_;
				if (!(i <= (_tmp8_ - 1))) {
					break;
				}
				_tmp9_ = a;
				_tmp9__length1 = a_length1;
				_tmp10_ = i;
				_tmp11_ = l;
				_tmp12_ = i;
				_tmp13_ = gee_abstract_list_get ((GeeAbstractList*) _tmp11_, _tmp12_);
				_tmp9_[_tmp10_] = (gint) ((gintptr) _tmp13_);
				_tmp14_ = _tmp9_[_tmp10_];
			}
		}
	}
	_tmp15_ = a;
	_tmp15__length1 = a_length1;
	if (result_length1) {
		*result_length1 = _tmp15__length1;
	}
	result = _tmp15_;
	return result;
}


/**
         * Get the set if distinct (non-duplicate) indices from a list
         * @param Array<number> indices
         * @returns Array<number>
         */
gint* entitas_matcher_distinctIndices (gint* indices, int indices_length1, int* result_length1) {
	gint* result = NULL;
	GeeHashMap* indicesSet = NULL;
	GeeHashMap* _tmp0_ = NULL;
	GeeArrayList* _result_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	GeeArrayList* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	gint* _tmp12_ = NULL;
	gint* _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	_tmp0_ = gee_hash_map_new (G_TYPE_INT, NULL, NULL, G_TYPE_BOOLEAN, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	indicesSet = _tmp0_;
	_tmp1_ = gee_array_list_new (G_TYPE_INT, NULL, NULL, NULL, NULL, NULL);
	_result_ = _tmp1_;
	_tmp2_ = indices;
	_tmp2__length1 = indices_length1;
	{
		gint* index_collection = NULL;
		gint index_collection_length1 = 0;
		gint _index_collection_size_ = 0;
		gint index_it = 0;
		index_collection = _tmp2_;
		index_collection_length1 = _tmp2__length1;
		for (index_it = 0; index_it < _tmp2__length1; index_it = index_it + 1) {
			gint index = 0;
			index = index_collection[index_it];
			{
				GeeHashMap* _tmp3_ = NULL;
				gint _tmp4_ = 0;
				gboolean _tmp5_ = FALSE;
				GeeHashMap* _tmp8_ = NULL;
				gint _tmp9_ = 0;
				_tmp3_ = indicesSet;
				_tmp4_ = index;
				_tmp5_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp3_, (gpointer) ((gintptr) _tmp4_));
				if (!_tmp5_) {
					GeeArrayList* _tmp6_ = NULL;
					gint _tmp7_ = 0;
					_tmp6_ = _result_;
					_tmp7_ = index;
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp6_, (gpointer) ((gintptr) _tmp7_));
				}
				_tmp8_ = indicesSet;
				_tmp9_ = index;
				gee_abstract_map_set ((GeeAbstractMap*) _tmp8_, (gpointer) ((gintptr) _tmp9_), (gpointer) ((gintptr) TRUE));
			}
		}
	}
	_tmp10_ = _result_;
	_tmp12_ = entitas_matcher_listToArray (_tmp10_, &_tmp11_);
	_tmp13_ = _tmp12_;
	_tmp13__length1 = _tmp11_;
	if (result_length1) {
		*result_length1 = _tmp13__length1;
	}
	result = _tmp13_;
	_g_object_unref0 (_result_);
	_g_object_unref0 (indicesSet);
	return result;
}


/**
         * Merge all the indices of a set of Matchers
         * @param Array<IMatcher> matchers
         * @returns Array<number>
         */
gint* entitas_matcher_merge (EntitasIMatcher** matchers, int matchers_length1, int* result_length1, GError** error) {
	gint* result = NULL;
	GeeArrayList* indices = NULL;
	GeeArrayList* _tmp0_ = NULL;
	EntitasIMatcher** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	GeeArrayList* _tmp16_ = NULL;
	gint _tmp17_ = 0;
	gint* _tmp18_ = NULL;
	gint* _tmp19_ = NULL;
	gint _tmp19__length1 = 0;
	GError * _inner_error_ = NULL;
	_tmp0_ = gee_array_list_new (G_TYPE_INT, NULL, NULL, NULL, NULL, NULL);
	indices = _tmp0_;
	_tmp1_ = matchers;
	_tmp1__length1 = matchers_length1;
	{
		EntitasIMatcher** matcher_collection = NULL;
		gint matcher_collection_length1 = 0;
		gint _matcher_collection_size_ = 0;
		gint matcher_it = 0;
		matcher_collection = _tmp1_;
		matcher_collection_length1 = _tmp1__length1;
		for (matcher_it = 0; matcher_it < _tmp1__length1; matcher_it = matcher_it + 1) {
			EntitasIMatcher* _tmp2_ = NULL;
			EntitasIMatcher* matcher = NULL;
			_tmp2_ = _g_object_ref0 (matcher_collection[matcher_it]);
			matcher = _tmp2_;
			{
				EntitasIMatcher* _tmp3_ = NULL;
				gint* _tmp4_ = NULL;
				gint _tmp4__length1 = 0;
				gint* _tmp5_ = NULL;
				gint _tmp5__length1 = 0;
				GeeArrayList* _tmp11_ = NULL;
				EntitasIMatcher* _tmp12_ = NULL;
				gint* _tmp13_ = NULL;
				gint _tmp13__length1 = 0;
				gint* _tmp14_ = NULL;
				gint _tmp14__length1 = 0;
				gint _tmp15_ = 0;
				_tmp3_ = matcher;
				_tmp4_ = entitas_imatcher_get_indices (_tmp3_, &_tmp4__length1);
				_tmp5_ = _tmp4_;
				_tmp5__length1 = _tmp4__length1;
				if (_tmp5__length1 != 1) {
					EntitasIMatcher* _tmp6_ = NULL;
					gchar* _tmp7_ = NULL;
					gchar* _tmp8_ = NULL;
					GError* _tmp9_ = NULL;
					GError* _tmp10_ = NULL;
					_tmp6_ = matcher;
					_tmp7_ = entitas_imatcher_toString (_tmp6_);
					_tmp8_ = _tmp7_;
					_tmp9_ = g_error_new_literal (ENTITAS_ECS_EXCEPTION, ENTITAS_ECS_EXCEPTION_Matcher, _tmp8_);
					_tmp10_ = _tmp9_;
					_g_free0 (_tmp8_);
					_inner_error_ = _tmp10_;
					if (_inner_error_->domain == ENTITAS_ECS_EXCEPTION) {
						g_propagate_error (error, _inner_error_);
						_g_object_unref0 (matcher);
						_g_object_unref0 (indices);
						return NULL;
					} else {
						_g_object_unref0 (matcher);
						_g_object_unref0 (indices);
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return NULL;
					}
				}
				_tmp11_ = indices;
				_tmp12_ = matcher;
				_tmp13_ = entitas_imatcher_get_indices (_tmp12_, &_tmp13__length1);
				_tmp14_ = _tmp13_;
				_tmp14__length1 = _tmp13__length1;
				_tmp15_ = _tmp14_[0];
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp11_, (gpointer) ((gintptr) _tmp15_));
				_g_object_unref0 (matcher);
			}
		}
	}
	_tmp16_ = indices;
	_tmp18_ = entitas_matcher_listToArray (_tmp16_, &_tmp17_);
	_tmp19_ = _tmp18_;
	_tmp19__length1 = _tmp17_;
	if (result_length1) {
		*result_length1 = _tmp19__length1;
	}
	result = _tmp19_;
	_g_object_unref0 (indices);
	return result;
}


/**
         * Matches allOf the components/indices specified
         * @params Array<entitas.IMatcher>|Array<number> args
         * @returns entitas.Matcher
         */
EntitasIMatcher* entitas_matcher_AllOf (gint* args, int args_length1) {
	EntitasIMatcher* result = NULL;
	EntitasMatcher* matcher = NULL;
	EntitasMatcher* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
	gint* _tmp3_ = NULL;
	_tmp0_ = entitas_matcher_new ();
	matcher = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp3_ = entitas_matcher_distinctIndices (_tmp1_, _tmp1__length1, &_tmp2_);
	matcher->priv->_allOfIndices = (g_free (matcher->priv->_allOfIndices), NULL);
	matcher->priv->_allOfIndices = _tmp3_;
	matcher->priv->_allOfIndices_length1 = _tmp2_;
	matcher->priv->__allOfIndices_size_ = matcher->priv->_allOfIndices_length1;
	result = (EntitasIMatcher*) matcher;
	return result;
}


/**
         * Matches anyOf the components/indices specified
         * @params Array<entitas.IMatcher>|Array<number> args
         * @returns entitas.Matcher
         */
EntitasIMatcher* entitas_matcher_AnyOf (gint* args, int args_length1) {
	EntitasIMatcher* result = NULL;
	EntitasMatcher* matcher = NULL;
	EntitasMatcher* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
	gint* _tmp3_ = NULL;
	_tmp0_ = entitas_matcher_new ();
	matcher = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp3_ = entitas_matcher_distinctIndices (_tmp1_, _tmp1__length1, &_tmp2_);
	matcher->priv->_anyOfIndices = (g_free (matcher->priv->_anyOfIndices), NULL);
	matcher->priv->_anyOfIndices = _tmp3_;
	matcher->priv->_anyOfIndices_length1 = _tmp2_;
	matcher->priv->__anyOfIndices_size_ = matcher->priv->_anyOfIndices_length1;
	result = (EntitasIMatcher*) matcher;
	return result;
}


static const gchar* entitas_matcher_real_get_id (EntitasIMatcher* base) {
	const gchar* result;
	EntitasMatcher* self;
	const gchar* _tmp0_ = NULL;
	self = (EntitasMatcher*) base;
	_tmp0_ = self->priv->_id;
	result = _tmp0_;
	return result;
}


static gint* entitas_matcher_real_get_indices (EntitasIMatcher* base, int* result_length1) {
	gint* result;
	EntitasMatcher* self;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint* _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	gint* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	self = (EntitasMatcher*) base;
	_tmp0_ = self->priv->_indices;
	_tmp0__length1 = self->priv->_indices_length1;
	if (_tmp0_ == NULL) {
		gint _tmp1_ = 0;
		gint* _tmp2_ = NULL;
		_tmp2_ = entitas_matcher_mergeIndices (self, &_tmp1_);
		self->priv->_indices = (g_free (self->priv->_indices), NULL);
		self->priv->_indices = _tmp2_;
		self->priv->_indices_length1 = _tmp1_;
		self->priv->__indices_size_ = self->priv->_indices_length1;
	}
	_tmp3_ = self->priv->_indices;
	_tmp3__length1 = self->priv->_indices_length1;
	_tmp4_ = _tmp3_;
	_tmp4__length1 = _tmp3__length1;
	if (result_length1) {
		*result_length1 = _tmp4__length1;
	}
	result = _tmp4_;
	return result;
}


gint* entitas_matcher_get_allOfIndices (EntitasMatcher* self, int* result_length1) {
	gint* result;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_allOfIndices;
	_tmp0__length1 = self->priv->_allOfIndices_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


gint* entitas_matcher_get_anyOfIndices (EntitasMatcher* self, int* result_length1) {
	gint* result;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_anyOfIndices;
	_tmp0__length1 = self->priv->_anyOfIndices_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


gint* entitas_matcher_get_noneOfIndices (EntitasMatcher* self, int* result_length1) {
	gint* result;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_noneOfIndices;
	_tmp0__length1 = self->priv->_noneOfIndices_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static void entitas_matcher_class_init (EntitasMatcherClass * klass) {
	entitas_matcher_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (EntitasMatcherPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_entitas_matcher_get_property;
	G_OBJECT_CLASS (klass)->finalize = entitas_matcher_finalize;
	/**
	         * Get the matcher id
	         * @type number
	         * @name entitas.Matcher#id */
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENTITAS_MATCHER_ID, g_param_spec_string ("id", "id", "id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void entitas_matcher_entitas_imatcher_interface_init (EntitasIMatcherIface * iface) {
	entitas_matcher_entitas_imatcher_parent_iface = g_type_interface_peek_parent (iface);
	iface->matches = (gboolean (*)(EntitasIMatcher*, EntitasEntity*)) entitas_matcher_real_matches;
	iface->toString = (gchar* (*)(EntitasIMatcher*)) entitas_matcher_real_toString;
	iface->get_id = entitas_matcher_real_get_id;
	iface->get_indices = entitas_matcher_real_get_indices;
}


static void entitas_matcher_entitas_iall_of_matcher_interface_init (EntitasIAllOfMatcherIface * iface) {
	entitas_matcher_entitas_iall_of_matcher_parent_iface = g_type_interface_peek_parent (iface);
	iface->anyOf = (EntitasIAnyOfMatcher* (*)(EntitasIAllOfMatcher*, gint*, int)) entitas_matcher_real_anyOf;
	iface->noneOf = (EntitasINoneOfMatcher* (*)(EntitasIAllOfMatcher*, gint*, int)) entitas_matcher_real_noneOf;
}


static void entitas_matcher_entitas_iany_of_matcher_interface_init (EntitasIAnyOfMatcherIface * iface) {
	entitas_matcher_entitas_iany_of_matcher_parent_iface = g_type_interface_peek_parent (iface);
}


static void entitas_matcher_entitas_inone_of_matcher_interface_init (EntitasINoneOfMatcherIface * iface) {
	entitas_matcher_entitas_inone_of_matcher_parent_iface = g_type_interface_peek_parent (iface);
}


static void entitas_matcher_instance_init (EntitasMatcher * self) {
	self->priv = ENTITAS_MATCHER_GET_PRIVATE (self);
}


static void entitas_matcher_finalize (GObject* obj) {
	EntitasMatcher * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENTITAS_TYPE_MATCHER, EntitasMatcher);
	_g_free0 (self->priv->_id);
	self->priv->_allOfIndices = (g_free (self->priv->_allOfIndices), NULL);
	self->priv->_anyOfIndices = (g_free (self->priv->_anyOfIndices), NULL);
	self->priv->_noneOfIndices = (g_free (self->priv->_noneOfIndices), NULL);
	self->priv->_indices = (g_free (self->priv->_indices), NULL);
	_g_free0 (self->priv->_toStringCache);
	G_OBJECT_CLASS (entitas_matcher_parent_class)->finalize (obj);
}


GType entitas_matcher_get_type (void) {
	static volatile gsize entitas_matcher_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_matcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasMatcherClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) entitas_matcher_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EntitasMatcher), 0, (GInstanceInitFunc) entitas_matcher_instance_init, NULL };
		static const GInterfaceInfo entitas_imatcher_info = { (GInterfaceInitFunc) entitas_matcher_entitas_imatcher_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iall_of_matcher_info = { (GInterfaceInitFunc) entitas_matcher_entitas_iall_of_matcher_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_iany_of_matcher_info = { (GInterfaceInitFunc) entitas_matcher_entitas_iany_of_matcher_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo entitas_inone_of_matcher_info = { (GInterfaceInitFunc) entitas_matcher_entitas_inone_of_matcher_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType entitas_matcher_type_id;
		entitas_matcher_type_id = g_type_register_static (G_TYPE_OBJECT, "EntitasMatcher", &g_define_type_info, 0);
		g_type_add_interface_static (entitas_matcher_type_id, ENTITAS_TYPE_IMATCHER, &entitas_imatcher_info);
		g_type_add_interface_static (entitas_matcher_type_id, ENTITAS_TYPE_IALL_OF_MATCHER, &entitas_iall_of_matcher_info);
		g_type_add_interface_static (entitas_matcher_type_id, ENTITAS_TYPE_IANY_OF_MATCHER, &entitas_iany_of_matcher_info);
		g_type_add_interface_static (entitas_matcher_type_id, ENTITAS_TYPE_INONE_OF_MATCHER, &entitas_inone_of_matcher_info);
		g_once_init_leave (&entitas_matcher_type_id__volatile, entitas_matcher_type_id);
	}
	return entitas_matcher_type_id__volatile;
}


static void _vala_entitas_matcher_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	EntitasMatcher * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENTITAS_TYPE_MATCHER, EntitasMatcher);
	switch (property_id) {
		case ENTITAS_MATCHER_ID:
		g_value_set_string (value, entitas_imatcher_get_id ((EntitasIMatcher*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



