/* World.c generated by valac 0.34.4, the Vala compiler
 * generated from World.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define ENTITAS_TYPE_WORLD (entitas_world_get_type ())
#define ENTITAS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_WORLD, EntitasWorld))
#define ENTITAS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_WORLD, EntitasWorldClass))
#define ENTITAS_IS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_WORLD))
#define ENTITAS_IS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_WORLD))
#define ENTITAS_WORLD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_WORLD, EntitasWorldClass))

typedef struct _EntitasWorld EntitasWorld;
typedef struct _EntitasWorldClass EntitasWorldClass;
typedef struct _EntitasWorldPrivate EntitasWorldPrivate;

#define ENTITAS_TYPE_WORLD_CHANGED (entitas_world_changed_get_type ())
#define ENTITAS_WORLD_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_WORLD_CHANGED, EntitasWorldChanged))
#define ENTITAS_WORLD_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_WORLD_CHANGED, EntitasWorldChangedClass))
#define ENTITAS_IS_WORLD_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_WORLD_CHANGED))
#define ENTITAS_IS_WORLD_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_WORLD_CHANGED))
#define ENTITAS_WORLD_CHANGED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_WORLD_CHANGED, EntitasWorldChangedClass))

typedef struct _EntitasWorldChanged EntitasWorldChanged;
typedef struct _EntitasWorldChangedClass EntitasWorldChangedClass;

#define ENTITAS_TYPE_GROUPS_CHANGED (entitas_groups_changed_get_type ())
#define ENTITAS_GROUPS_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_GROUPS_CHANGED, EntitasGroupsChanged))
#define ENTITAS_GROUPS_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_GROUPS_CHANGED, EntitasGroupsChangedClass))
#define ENTITAS_IS_GROUPS_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_GROUPS_CHANGED))
#define ENTITAS_IS_GROUPS_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_GROUPS_CHANGED))
#define ENTITAS_GROUPS_CHANGED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_GROUPS_CHANGED, EntitasGroupsChangedClass))

typedef struct _EntitasGroupsChanged EntitasGroupsChanged;
typedef struct _EntitasGroupsChangedClass EntitasGroupsChangedClass;

#define ENTITAS_TYPE_GROUP (entitas_group_get_type ())
#define ENTITAS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_GROUP, EntitasGroup))
#define ENTITAS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_GROUP, EntitasGroupClass))
#define ENTITAS_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_GROUP))
#define ENTITAS_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_GROUP))
#define ENTITAS_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_GROUP, EntitasGroupClass))

typedef struct _EntitasGroup EntitasGroup;
typedef struct _EntitasGroupClass EntitasGroupClass;

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())
#define ENTITAS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ENTITY, EntitasEntity))
#define ENTITAS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_ENTITY, EntitasEntityClass))
#define ENTITAS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ENTITY))
#define ENTITAS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_ENTITY))
#define ENTITAS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_ENTITY, EntitasEntityClass))

typedef struct _EntitasEntity EntitasEntity;
typedef struct _EntitasEntityClass EntitasEntityClass;

#define ENTITAS_TYPE_IINITIALIZE_SYSTEM (entitas_iinitialize_system_get_type ())
#define ENTITAS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IINITIALIZE_SYSTEM, EntitasIInitializeSystem))
#define ENTITAS_IS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IINITIALIZE_SYSTEM))
#define ENTITAS_IINITIALIZE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IINITIALIZE_SYSTEM, EntitasIInitializeSystemIface))

typedef struct _EntitasIInitializeSystem EntitasIInitializeSystem;
typedef struct _EntitasIInitializeSystemIface EntitasIInitializeSystemIface;

#define ENTITAS_TYPE_IEXECUTE_SYSTEM (entitas_iexecute_system_get_type ())
#define ENTITAS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IEXECUTE_SYSTEM, EntitasIExecuteSystem))
#define ENTITAS_IS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IEXECUTE_SYSTEM))
#define ENTITAS_IEXECUTE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IEXECUTE_SYSTEM, EntitasIExecuteSystemIface))

typedef struct _EntitasIExecuteSystem EntitasIExecuteSystem;
typedef struct _EntitasIExecuteSystemIface EntitasIExecuteSystemIface;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define __g_queue_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_queue_free__g_object_unref0_ (var), NULL)))
#define _g_rand_free0(var) ((var == NULL) ? NULL : (var = (g_rand_free (var), NULL)))

#define ENTITAS_TYPE_ENTITY_CHANGED (entitas_entity_changed_get_type ())
#define ENTITAS_ENTITY_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ENTITY_CHANGED, EntitasEntityChanged))
#define ENTITAS_ENTITY_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_ENTITY_CHANGED, EntitasEntityChangedClass))
#define ENTITAS_IS_ENTITY_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ENTITY_CHANGED))
#define ENTITAS_IS_ENTITY_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_ENTITY_CHANGED))
#define ENTITAS_ENTITY_CHANGED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_ENTITY_CHANGED, EntitasEntityChangedClass))

typedef struct _EntitasEntityChanged EntitasEntityChanged;
typedef struct _EntitasEntityChangedClass EntitasEntityChangedClass;

#define ENTITAS_TYPE_ICOMPONENT (entitas_icomponent_get_type ())
#define ENTITAS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ICOMPONENT, EntitasIComponent))
#define ENTITAS_IS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ICOMPONENT))
#define ENTITAS_ICOMPONENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_ICOMPONENT, EntitasIComponentIface))

typedef struct _EntitasIComponent EntitasIComponent;
typedef struct _EntitasIComponentIface EntitasIComponentIface;

#define ENTITAS_TYPE_COMPONENT_REPLACED (entitas_component_replaced_get_type ())
#define ENTITAS_COMPONENT_REPLACED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_COMPONENT_REPLACED, EntitasComponentReplaced))
#define ENTITAS_COMPONENT_REPLACED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_COMPONENT_REPLACED, EntitasComponentReplacedClass))
#define ENTITAS_IS_COMPONENT_REPLACED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_COMPONENT_REPLACED))
#define ENTITAS_IS_COMPONENT_REPLACED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_COMPONENT_REPLACED))
#define ENTITAS_COMPONENT_REPLACED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_COMPONENT_REPLACED, EntitasComponentReplacedClass))

typedef struct _EntitasComponentReplaced EntitasComponentReplaced;
typedef struct _EntitasComponentReplacedClass EntitasComponentReplacedClass;

#define ENTITAS_TYPE_ENTITY_RELEASED (entitas_entity_released_get_type ())
#define ENTITAS_ENTITY_RELEASED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ENTITY_RELEASED, EntitasEntityReleased))
#define ENTITAS_ENTITY_RELEASED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_ENTITY_RELEASED, EntitasEntityReleasedClass))
#define ENTITAS_IS_ENTITY_RELEASED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ENTITY_RELEASED))
#define ENTITAS_IS_ENTITY_RELEASED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_ENTITY_RELEASED))
#define ENTITAS_ENTITY_RELEASED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_ENTITY_RELEASED, EntitasEntityReleasedClass))

typedef struct _EntitasEntityReleased EntitasEntityReleased;
typedef struct _EntitasEntityReleasedClass EntitasEntityReleasedClass;

#define ENTITAS_TYPE_IMATCHER (entitas_imatcher_get_type ())
#define ENTITAS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IMATCHER, EntitasIMatcher))
#define ENTITAS_IS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IMATCHER))
#define ENTITAS_IMATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IMATCHER, EntitasIMatcherIface))

typedef struct _EntitasIMatcher EntitasIMatcher;
typedef struct _EntitasIMatcherIface EntitasIMatcherIface;

#define ENTITAS_TYPE_ISYSTEM (entitas_isystem_get_type ())
#define ENTITAS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ISYSTEM, EntitasISystem))
#define ENTITAS_IS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ISYSTEM))
#define ENTITAS_ISYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_ISYSTEM, EntitasISystemIface))

typedef struct _EntitasISystem EntitasISystem;
typedef struct _EntitasISystemIface EntitasISystemIface;

#define ENTITAS_TYPE_ISET_WORLD (entitas_iset_world_get_type ())
#define ENTITAS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ISET_WORLD, EntitasISetWorld))
#define ENTITAS_IS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ISET_WORLD))
#define ENTITAS_ISET_WORLD_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_ISET_WORLD, EntitasISetWorldIface))

typedef struct _EntitasISetWorld EntitasISetWorld;
typedef struct _EntitasISetWorldIface EntitasISetWorldIface;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _EntitasWorld {
	GObject parent_instance;
	EntitasWorldPrivate * priv;
};

struct _EntitasWorldClass {
	GObjectClass parent_class;
};

struct _EntitasIInitializeSystemIface {
	GTypeInterface parent_iface;
	void (*initialize) (EntitasIInitializeSystem* self);
};

struct _EntitasIExecuteSystemIface {
	GTypeInterface parent_iface;
	void (*execute) (EntitasIExecuteSystem* self);
};

struct _EntitasWorldPrivate {
	EntitasWorldChanged* _onEntityCreated;
	EntitasWorldChanged* _onEntityWillBeDestroyed;
	EntitasWorldChanged* _onEntityDestroyed;
	EntitasGroupsChanged* _onGroupCreated;
	gchar* _name;
	gint _totalComponents;
	gint _creationIndex;
	GeeHashMap* _groups;
	GeeHashMap* _entities;
	GeeHashMap* _retainedEntities;
	GQueue* _reusableEntities;
	GeeArrayList** _groupsForIndex;
	gint _groupsForIndex_length1;
	gint __groupsForIndex_size_;
	gchar** _componentsEnum;
	gint _componentsEnum_length1;
	gint __componentsEnum_size_;
	EntitasEntity** _entitiesCache;
	gint _entitiesCache_length1;
	gint __entitiesCache_size_;
	EntitasIInitializeSystem** _initializeSystems;
	gint _initializeSystems_length1;
	gint __initializeSystems_size_;
	EntitasIExecuteSystem** _executeSystems;
	gint _executeSystems_length1;
	gint __executeSystems_size_;
	gchar** _hex;
	gint _hex_length1;
	gint __hex_size_;
};

struct _EntitasIComponentIface {
	GTypeInterface parent_iface;
};

typedef void (*EntitasOnEntityChanged) (EntitasEntity* e, gint index, EntitasIComponent* component, void* user_data);
typedef void (*EntitasOnComponentReplaced) (EntitasEntity* e, gint index, EntitasIComponent* component, EntitasIComponent* replacement, void* user_data);
typedef void (*EntitasOnEntityReleased) (EntitasEntity* e, void* user_data);
typedef enum  {
	ENTITAS_ECS_EXCEPTION_EntityIsNotEnabled,
	ENTITAS_ECS_EXCEPTION_EntityAlreadyHasComponent,
	ENTITAS_ECS_EXCEPTION_EntityDoesNotHaveComponent,
	ENTITAS_ECS_EXCEPTION_EntityIsAlreadyReleased,
	ENTITAS_ECS_EXCEPTION_SingleEntity,
	ENTITAS_ECS_EXCEPTION_Matcher,
	ENTITAS_ECS_EXCEPTION_WorldDoesNotContainEntity
} EntitasEcsException;
#define ENTITAS_ECS_EXCEPTION entitas_ecs_exception_quark ()
struct _EntitasIMatcherIface {
	GTypeInterface parent_iface;
	gboolean (*matches) (EntitasIMatcher* self, EntitasEntity* entity);
	gchar* (*toString) (EntitasIMatcher* self);
	const gchar* (*get_id) (EntitasIMatcher* self);
	gint* (*get_indices) (EntitasIMatcher* self, int* result_length1);
};

struct _EntitasISystemIface {
	GTypeInterface parent_iface;
};

struct _EntitasISetWorldIface {
	GTypeInterface parent_iface;
	void (*setWorld) (EntitasISetWorld* self, EntitasWorld* world);
};


static gpointer entitas_world_parent_class = NULL;
static gchar** entitas_world__components;
static gint entitas_world__components_length1;
static gchar** entitas_world__components = NULL;
static gint entitas_world__components_length1 = 0;
static gint _entitas_world__components_size_ = 0;
static EntitasWorld* entitas_world__instance;
static EntitasWorld* entitas_world__instance = NULL;
static GRand* entitas_world__random;
static GRand* entitas_world__random = NULL;

GType entitas_world_get_type (void) G_GNUC_CONST;
GType entitas_world_changed_get_type (void) G_GNUC_CONST;
GType entitas_groups_changed_get_type (void) G_GNUC_CONST;
GType entitas_group_get_type (void) G_GNUC_CONST;
GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_iinitialize_system_get_type (void) G_GNUC_CONST;
GType entitas_iexecute_system_get_type (void) G_GNUC_CONST;
#define ENTITAS_WORLD_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ENTITAS_TYPE_WORLD, EntitasWorldPrivate))
enum  {
	ENTITAS_WORLD_DUMMY_PROPERTY,
	ENTITAS_WORLD_COMPONENTS_COUNT,
	ENTITAS_WORLD_COUNT,
	ENTITAS_WORLD_REUSABLE_ENTITIES_COUNT,
	ENTITAS_WORLD_RETAINED_ENTITIES_COUNT,
	ENTITAS_WORLD_ON_ENTITY_CREATED,
	ENTITAS_WORLD_ON_ENTITY_WILL_BE_DESTROYED,
	ENTITAS_WORLD_ON_ENTITY_DESTROYED,
	ENTITAS_WORLD_ON_GROUP_CREATED,
	ENTITAS_WORLD_NAME
};
static void _g_object_unref0_ (gpointer var);
static void _g_queue_free__g_object_unref0_ (GQueue* self);
EntitasWorld* entitas_world_new (gchar** components, int components_length1, gint startCreationIndex);
EntitasWorld* entitas_world_construct (GType object_type, gchar** components, int components_length1, gint startCreationIndex);
static gchar** _vala_array_dup6 (gchar** self, int length);
EntitasGroupsChanged* entitas_groups_changed_new (void);
EntitasGroupsChanged* entitas_groups_changed_construct (GType object_type);
EntitasWorldChanged* entitas_world_changed_new (void);
EntitasWorldChanged* entitas_world_changed_construct (GType object_type);
static gchar** _vala_array_dup7 (gchar** self, int length);
EntitasEntity* entitas_world_createEntity (EntitasWorld* self, const gchar* name);
EntitasEntity* entitas_entity_new (gchar** componentsEnum, int componentsEnum_length1, gint totalComponents);
EntitasEntity* entitas_entity_construct (GType object_type, gchar** componentsEnum, int componentsEnum_length1, gint totalComponents);
void entitas_entity_initialize (EntitasEntity* self, const gchar* name, const gchar* id, gint creationIndex);
static gchar* entitas_world_uidgen (EntitasWorld* self);
const gchar* entitas_entity_get_id (EntitasEntity* self);
GType entitas_entity_changed_get_type (void) G_GNUC_CONST;
EntitasEntityChanged* entitas_entity_get_onComponentAdded (EntitasEntity* self);
GType entitas_icomponent_get_type (void) G_GNUC_CONST;
void entitas_entity_changed_add (EntitasEntityChanged* self, EntitasOnEntityChanged event, void* event_target);
void entitas_world_updateGroupsComponentAddedOrRemoved (EntitasWorld* self, EntitasEntity* entity, gint index, EntitasIComponent* component);
static void _entitas_world_updateGroupsComponentAddedOrRemoved_entitas_on_entity_changed (EntitasEntity* e, gint index, EntitasIComponent* component, gpointer self);
EntitasEntityChanged* entitas_entity_get_onComponentRemoved (EntitasEntity* self);
GType entitas_component_replaced_get_type (void) G_GNUC_CONST;
EntitasComponentReplaced* entitas_entity_get_onComponentReplaced (EntitasEntity* self);
void entitas_component_replaced_add (EntitasComponentReplaced* self, EntitasOnComponentReplaced event, void* event_target);
void entitas_world_updateGroupsComponentReplaced (EntitasWorld* self, EntitasEntity* entity, gint index, EntitasIComponent* previousComponent, EntitasIComponent* newComponent);
static void _entitas_world_updateGroupsComponentReplaced_entitas_on_component_replaced (EntitasEntity* e, gint index, EntitasIComponent* component, EntitasIComponent* replacement, gpointer self);
GType entitas_entity_released_get_type (void) G_GNUC_CONST;
EntitasEntityReleased* entitas_entity_get_onEntityReleased (EntitasEntity* self);
void entitas_entity_released_add (EntitasEntityReleased* self, EntitasOnEntityReleased event, void* event_target);
void entitas_world_onEntityReleased (EntitasWorld* self, EntitasEntity* entity);
static void _entitas_world_onEntityReleased_entitas_on_entity_released (EntitasEntity* e, gpointer self);
EntitasWorldChanged* entitas_world_get_onEntityCreated (EntitasWorld* self);
void entitas_world_changed_dispatch (EntitasWorldChanged* self, EntitasWorld* w, EntitasEntity* e);
GQuark entitas_ecs_exception_quark (void);
void entitas_world_destroyEntity (EntitasWorld* self, EntitasEntity* entity, GError** error);
void entitas_entity_destroy (EntitasEntity* self);
gint entitas_entity_get_refCount (EntitasEntity* self);
void entitas_entity_released_remove (EntitasEntityReleased* self, EntitasOnEntityReleased event, void* event_target);
void entitas_entity_release (EntitasEntity* self, GError** error);
void entitas_world_destroyAllEntities (EntitasWorld* self, GError** error);
GType entitas_imatcher_get_type (void) G_GNUC_CONST;
EntitasEntity** entitas_world_getEntities (EntitasWorld* self, EntitasIMatcher* matcher, int* result_length1);
gboolean entitas_world_hasEntity (EntitasWorld* self, EntitasEntity* entity);
EntitasGroup* entitas_world_getGroup (EntitasWorld* self, EntitasIMatcher* matcher);
EntitasEntity** entitas_group_getEntities (EntitasGroup* self, int* result_length1);
static void _vala_array_add15 (EntitasEntity*** array, int* length, int* size, EntitasEntity* value);
static EntitasEntity** _vala_array_dup8 (EntitasEntity** self, int length);
GType entitas_isystem_get_type (void) G_GNUC_CONST;
EntitasWorld* entitas_world_add (EntitasWorld* self, EntitasISystem* system);
GType entitas_iset_world_get_type (void) G_GNUC_CONST;
void entitas_iset_world_setWorld (EntitasISetWorld* self, EntitasWorld* world);
static void _vala_array_add16 (EntitasIInitializeSystem*** array, int* length, int* size, EntitasIInitializeSystem* value);
static void _vala_array_add17 (EntitasIExecuteSystem*** array, int* length, int* size, EntitasIExecuteSystem* value);
EntitasWorld* entitas_world_initialize (EntitasWorld* self);
void entitas_iinitialize_system_initialize (EntitasIInitializeSystem* self);
void entitas_world_execute (EntitasWorld* self);
void entitas_iexecute_system_execute (EntitasIExecuteSystem* self);
const gchar* entitas_imatcher_get_id (EntitasIMatcher* self);
EntitasGroup* entitas_group_new (EntitasIMatcher* matcher);
EntitasGroup* entitas_group_construct (GType object_type, EntitasIMatcher* matcher);
void entitas_group_handleEntitySilently (EntitasGroup* self, EntitasEntity* entity, GError** error);
gint* entitas_imatcher_get_indices (EntitasIMatcher* self, int* result_length1);
void entitas_groups_changed_dispatch (EntitasGroupsChanged* self, EntitasWorld* w, EntitasGroup* g);
void entitas_group_handleEntity (EntitasGroup* self, EntitasEntity* entity, gint index, EntitasIComponent* component, GError** error);
void entitas_group_updateEntity (EntitasGroup* self, EntitasEntity* entity, gint index, EntitasIComponent* previousComponent, EntitasIComponent* newComponent);
gboolean entitas_entity_get_isEnabled (EntitasEntity* self);
GRand* entitas_world_get_random (void);
gchar** entitas_world_get_components (int* result_length1);
EntitasWorld* entitas_world_get_instance (void);
gint entitas_world_get_componentsCount (EntitasWorld* self);
gint entitas_world_get_count (EntitasWorld* self);
gint entitas_world_get_reusableEntitiesCount (EntitasWorld* self);
gint entitas_world_get_retainedEntitiesCount (EntitasWorld* self);
EntitasWorldChanged* entitas_world_get_onEntityWillBeDestroyed (EntitasWorld* self);
EntitasWorldChanged* entitas_world_get_onEntityDestroyed (EntitasWorld* self);
EntitasGroupsChanged* entitas_world_get_onGroupCreated (EntitasWorld* self);
const gchar* entitas_world_get_name (EntitasWorld* self);
static void entitas_world_finalize (GObject* obj);
static void _vala_entitas_world_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_queue_free__g_object_unref0_ (GQueue* self) {
	g_queue_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_queue_free (self);
}


/**
         * @constructor
         * @param Object components
         * @param number totalComponents
         * @param number startCreationIndex
         */
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gchar** _vala_array_dup6 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_ = NULL;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static gchar** _vala_array_dup7 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_ = NULL;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


EntitasWorld* entitas_world_construct (GType object_type, gchar** components, int components_length1, gint startCreationIndex) {
	EntitasWorld * self = NULL;
	GRand* _tmp0_ = NULL;
	EntitasWorld* _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	gchar** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	EntitasGroupsChanged* _tmp4_ = NULL;
	EntitasWorldChanged* _tmp5_ = NULL;
	EntitasWorldChanged* _tmp6_ = NULL;
	EntitasWorldChanged* _tmp7_ = NULL;
	gchar** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	gchar** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	gchar** _tmp10_ = NULL;
	gint _tmp10__length1 = 0;
	gint _tmp11_ = 0;
	gchar** _tmp12_ = NULL;
	gint _tmp12__length1 = 0;
	GeeArrayList** _tmp13_ = NULL;
	GQueue* _tmp14_ = NULL;
	GeeHashMap* _tmp15_ = NULL;
	EntitasEntity** _tmp16_ = NULL;
	GeeHashMap* _tmp17_ = NULL;
	GeeHashMap* _tmp18_ = NULL;
	EntitasIInitializeSystem** _tmp19_ = NULL;
	EntitasIExecuteSystem** _tmp20_ = NULL;
	self = (EntitasWorld*) g_object_new (object_type, NULL);
	_tmp0_ = g_rand_new ();
	_g_rand_free0 (entitas_world__random);
	entitas_world__random = _tmp0_;
	_tmp1_ = _g_object_ref0 (self);
	_g_object_unref0 (entitas_world__instance);
	entitas_world__instance = _tmp1_;
	_tmp2_ = components;
	_tmp2__length1 = components_length1;
	_tmp3_ = (_tmp2_ != NULL) ? _vala_array_dup6 (_tmp2_, _tmp2__length1) : ((gpointer) _tmp2_);
	_tmp3__length1 = _tmp2__length1;
	entitas_world__components = (_vala_array_free (entitas_world__components, entitas_world__components_length1, (GDestroyNotify) g_free), NULL);
	entitas_world__components = _tmp3_;
	entitas_world__components_length1 = _tmp3__length1;
	_entitas_world__components_size_ = entitas_world__components_length1;
	_tmp4_ = entitas_groups_changed_new ();
	_g_object_unref0 (self->priv->_onGroupCreated);
	self->priv->_onGroupCreated = _tmp4_;
	_tmp5_ = entitas_world_changed_new ();
	_g_object_unref0 (self->priv->_onEntityCreated);
	self->priv->_onEntityCreated = _tmp5_;
	_tmp6_ = entitas_world_changed_new ();
	_g_object_unref0 (self->priv->_onEntityDestroyed);
	self->priv->_onEntityDestroyed = _tmp6_;
	_tmp7_ = entitas_world_changed_new ();
	_g_object_unref0 (self->priv->_onEntityWillBeDestroyed);
	self->priv->_onEntityWillBeDestroyed = _tmp7_;
	_tmp8_ = components;
	_tmp8__length1 = components_length1;
	_tmp9_ = (_tmp8_ != NULL) ? _vala_array_dup7 (_tmp8_, _tmp8__length1) : ((gpointer) _tmp8_);
	_tmp9__length1 = _tmp8__length1;
	self->priv->_componentsEnum = (_vala_array_free (self->priv->_componentsEnum, self->priv->_componentsEnum_length1, (GDestroyNotify) g_free), NULL);
	self->priv->_componentsEnum = _tmp9_;
	self->priv->_componentsEnum_length1 = _tmp9__length1;
	self->priv->__componentsEnum_size_ = self->priv->_componentsEnum_length1;
	_tmp10_ = components;
	_tmp10__length1 = components_length1;
	self->priv->_totalComponents = _tmp10__length1;
	_tmp11_ = startCreationIndex;
	self->priv->_creationIndex = _tmp11_;
	_tmp12_ = components;
	_tmp12__length1 = components_length1;
	_tmp13_ = g_new0 (GeeArrayList*, _tmp12__length1 + 1);
	self->priv->_groupsForIndex = (_vala_array_free (self->priv->_groupsForIndex, self->priv->_groupsForIndex_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->_groupsForIndex = _tmp13_;
	self->priv->_groupsForIndex_length1 = _tmp12__length1;
	self->priv->__groupsForIndex_size_ = self->priv->_groupsForIndex_length1;
	_tmp14_ = g_queue_new ();
	__g_queue_free__g_object_unref0_0 (self->priv->_reusableEntities);
	self->priv->_reusableEntities = _tmp14_;
	_tmp15_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, ENTITAS_TYPE_ENTITY, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->_retainedEntities);
	self->priv->_retainedEntities = _tmp15_;
	_tmp16_ = g_new0 (EntitasEntity*, 0 + 1);
	self->priv->_entitiesCache = (_vala_array_free (self->priv->_entitiesCache, self->priv->_entitiesCache_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->_entitiesCache = _tmp16_;
	self->priv->_entitiesCache_length1 = 0;
	self->priv->__entitiesCache_size_ = self->priv->_entitiesCache_length1;
	_tmp17_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, ENTITAS_TYPE_ENTITY, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->_entities);
	self->priv->_entities = _tmp17_;
	_tmp18_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, ENTITAS_TYPE_GROUP, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->_groups);
	self->priv->_groups = _tmp18_;
	_tmp19_ = g_new0 (EntitasIInitializeSystem*, 0 + 1);
	self->priv->_initializeSystems = (_vala_array_free (self->priv->_initializeSystems, self->priv->_initializeSystems_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->_initializeSystems = _tmp19_;
	self->priv->_initializeSystems_length1 = 0;
	self->priv->__initializeSystems_size_ = self->priv->_initializeSystems_length1;
	_tmp20_ = g_new0 (EntitasIExecuteSystem*, 0 + 1);
	self->priv->_executeSystems = (_vala_array_free (self->priv->_executeSystems, self->priv->_executeSystems_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->_executeSystems = _tmp20_;
	self->priv->_executeSystems_length1 = 0;
	self->priv->__executeSystems_size_ = self->priv->_executeSystems_length1;
	return self;
}


EntitasWorld* entitas_world_new (gchar** components, int components_length1, gint startCreationIndex) {
	return entitas_world_construct (ENTITAS_TYPE_WORLD, components, components_length1, startCreationIndex);
}


/**
         * Create a new entity
         * @param string name
         * @returns entitas.Entity
         */
static void _entitas_world_updateGroupsComponentAddedOrRemoved_entitas_on_entity_changed (EntitasEntity* e, gint index, EntitasIComponent* component, gpointer self) {
	entitas_world_updateGroupsComponentAddedOrRemoved ((EntitasWorld*) self, e, index, component);
}


static void _entitas_world_updateGroupsComponentReplaced_entitas_on_component_replaced (EntitasEntity* e, gint index, EntitasIComponent* component, EntitasIComponent* replacement, gpointer self) {
	entitas_world_updateGroupsComponentReplaced ((EntitasWorld*) self, e, index, component, replacement);
}


static void _entitas_world_onEntityReleased_entitas_on_entity_released (EntitasEntity* e, gpointer self) {
	entitas_world_onEntityReleased ((EntitasWorld*) self, e);
}


EntitasEntity* entitas_world_createEntity (EntitasWorld* self, const gchar* name) {
	EntitasEntity* result = NULL;
	EntitasEntity* _tmp0_ = NULL;
	GQueue* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
	EntitasEntity* entity = NULL;
	EntitasEntity* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gint _tmp12_ = 0;
	GeeHashMap* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	EntitasEntity** _tmp16_ = NULL;
	EntitasEntityChanged* _tmp17_ = NULL;
	EntitasEntityChanged* _tmp18_ = NULL;
	EntitasEntityChanged* _tmp19_ = NULL;
	EntitasEntityChanged* _tmp20_ = NULL;
	EntitasComponentReplaced* _tmp21_ = NULL;
	EntitasComponentReplaced* _tmp22_ = NULL;
	EntitasEntityReleased* _tmp23_ = NULL;
	EntitasEntityReleased* _tmp24_ = NULL;
	EntitasWorldChanged* _tmp25_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	_tmp1_ = self->priv->_reusableEntities;
	_tmp2_ = _tmp1_->length;
	if (_tmp2_ > ((guint) 0)) {
		GQueue* _tmp3_ = NULL;
		gpointer _tmp4_ = NULL;
		_tmp3_ = self->priv->_reusableEntities;
		_tmp4_ = g_queue_pop_head (_tmp3_);
		_g_object_unref0 (_tmp0_);
		_tmp0_ = (EntitasEntity*) _tmp4_;
	} else {
		gchar** _tmp5_ = NULL;
		gint _tmp5__length1 = 0;
		gint _tmp6_ = 0;
		EntitasEntity* _tmp7_ = NULL;
		_tmp5_ = self->priv->_componentsEnum;
		_tmp5__length1 = self->priv->_componentsEnum_length1;
		_tmp6_ = self->priv->_totalComponents;
		_tmp7_ = entitas_entity_new (_tmp5_, _tmp5__length1, _tmp6_);
		_g_object_unref0 (_tmp0_);
		_tmp0_ = _tmp7_;
	}
	_tmp8_ = _g_object_ref0 (_tmp0_);
	entity = _tmp8_;
	_tmp9_ = name;
	_tmp10_ = entitas_world_uidgen (self);
	_tmp11_ = _tmp10_;
	_tmp12_ = self->priv->_creationIndex;
	self->priv->_creationIndex = _tmp12_ + 1;
	entitas_entity_initialize (entity, _tmp9_, _tmp11_, _tmp12_);
	_g_free0 (_tmp11_);
	_tmp13_ = self->priv->_entities;
	_tmp14_ = entitas_entity_get_id (entity);
	_tmp15_ = _tmp14_;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp13_, _tmp15_, entity);
	_tmp16_ = g_new0 (EntitasEntity*, 0 + 1);
	self->priv->_entitiesCache = (_vala_array_free (self->priv->_entitiesCache, self->priv->_entitiesCache_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->_entitiesCache = _tmp16_;
	self->priv->_entitiesCache_length1 = 0;
	self->priv->__entitiesCache_size_ = self->priv->_entitiesCache_length1;
	_tmp17_ = entitas_entity_get_onComponentAdded (entity);
	_tmp18_ = _tmp17_;
	entitas_entity_changed_add (_tmp18_, _entitas_world_updateGroupsComponentAddedOrRemoved_entitas_on_entity_changed, self);
	_tmp19_ = entitas_entity_get_onComponentRemoved (entity);
	_tmp20_ = _tmp19_;
	entitas_entity_changed_add (_tmp20_, _entitas_world_updateGroupsComponentAddedOrRemoved_entitas_on_entity_changed, self);
	_tmp21_ = entitas_entity_get_onComponentReplaced (entity);
	_tmp22_ = _tmp21_;
	entitas_component_replaced_add (_tmp22_, _entitas_world_updateGroupsComponentReplaced_entitas_on_component_replaced, self);
	_tmp23_ = entitas_entity_get_onEntityReleased (entity);
	_tmp24_ = _tmp23_;
	entitas_entity_released_add (_tmp24_, _entitas_world_onEntityReleased_entitas_on_entity_released, self);
	_tmp25_ = self->priv->_onEntityCreated;
	entitas_world_changed_dispatch (_tmp25_, self, entity);
	result = entity;
	_g_object_unref0 (_tmp0_);
	return result;
}


/**
         * Destroy an entity
         * @param entitas.Entity entity
         */
void entitas_world_destroyEntity (EntitasWorld* self, EntitasEntity* entity, GError** error) {
	GeeHashMap* _tmp0_ = NULL;
	EntitasEntity* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	GeeHashMap* _tmp6_ = NULL;
	EntitasEntity* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	EntitasEntity** _tmp10_ = NULL;
	EntitasWorldChanged* _tmp11_ = NULL;
	EntitasEntity* _tmp12_ = NULL;
	EntitasEntity* _tmp13_ = NULL;
	EntitasWorldChanged* _tmp14_ = NULL;
	EntitasEntity* _tmp15_ = NULL;
	EntitasEntity* _tmp16_ = NULL;
	gint _tmp17_ = 0;
	gint _tmp18_ = 0;
	EntitasEntity* _tmp30_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (entity != NULL);
	_tmp0_ = self->priv->_entities;
	_tmp1_ = entity;
	_tmp2_ = entitas_entity_get_id (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp0_, _tmp3_);
	if (!_tmp4_) {
		GError* _tmp5_ = NULL;
		_tmp5_ = g_error_new_literal (ENTITAS_ECS_EXCEPTION, ENTITAS_ECS_EXCEPTION_WorldDoesNotContainEntity, "Could not destroy entity!");
		_inner_error_ = _tmp5_;
		if (_inner_error_->domain == ENTITAS_ECS_EXCEPTION) {
			g_propagate_error (error, _inner_error_);
			return;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_tmp6_ = self->priv->_entities;
	_tmp7_ = entity;
	_tmp8_ = entitas_entity_get_id (_tmp7_);
	_tmp9_ = _tmp8_;
	gee_abstract_map_unset ((GeeAbstractMap*) _tmp6_, _tmp9_, NULL);
	_tmp10_ = g_new0 (EntitasEntity*, 0 + 1);
	self->priv->_entitiesCache = (_vala_array_free (self->priv->_entitiesCache, self->priv->_entitiesCache_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->_entitiesCache = _tmp10_;
	self->priv->_entitiesCache_length1 = 0;
	self->priv->__entitiesCache_size_ = self->priv->_entitiesCache_length1;
	_tmp11_ = self->priv->_onEntityWillBeDestroyed;
	_tmp12_ = entity;
	entitas_world_changed_dispatch (_tmp11_, self, _tmp12_);
	_tmp13_ = entity;
	entitas_entity_destroy (_tmp13_);
	_tmp14_ = self->priv->_onEntityDestroyed;
	_tmp15_ = entity;
	entitas_world_changed_dispatch (_tmp14_, self, _tmp15_);
	_tmp16_ = entity;
	_tmp17_ = entitas_entity_get_refCount (_tmp16_);
	_tmp18_ = _tmp17_;
	if (_tmp18_ == 1) {
		EntitasEntity* _tmp19_ = NULL;
		EntitasEntityReleased* _tmp20_ = NULL;
		EntitasEntityReleased* _tmp21_ = NULL;
		GQueue* _tmp22_ = NULL;
		EntitasEntity* _tmp23_ = NULL;
		EntitasEntity* _tmp24_ = NULL;
		_tmp19_ = entity;
		_tmp20_ = entitas_entity_get_onEntityReleased (_tmp19_);
		_tmp21_ = _tmp20_;
		entitas_entity_released_remove (_tmp21_, _entitas_world_onEntityReleased_entitas_on_entity_released, self);
		_tmp22_ = self->priv->_reusableEntities;
		_tmp23_ = entity;
		_tmp24_ = _g_object_ref0 (_tmp23_);
		g_queue_push_head (_tmp22_, _tmp24_);
	} else {
		GeeHashMap* _tmp25_ = NULL;
		EntitasEntity* _tmp26_ = NULL;
		const gchar* _tmp27_ = NULL;
		const gchar* _tmp28_ = NULL;
		EntitasEntity* _tmp29_ = NULL;
		_tmp25_ = self->priv->_retainedEntities;
		_tmp26_ = entity;
		_tmp27_ = entitas_entity_get_id (_tmp26_);
		_tmp28_ = _tmp27_;
		_tmp29_ = entity;
		gee_abstract_map_set ((GeeAbstractMap*) _tmp25_, _tmp28_, _tmp29_);
	}
	_tmp30_ = entity;
	entitas_entity_release (_tmp30_, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		if (_inner_error_->domain == ENTITAS_ECS_EXCEPTION) {
			g_propagate_error (error, _inner_error_);
			return;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
}


/**
         * Destroy All Entities
         */
void entitas_world_destroyAllEntities (EntitasWorld* self, GError** error) {
	EntitasEntity** entities = NULL;
	gint _tmp0_ = 0;
	EntitasEntity** _tmp1_ = NULL;
	gint entities_length1 = 0;
	gint _entities_size_ = 0;
	EntitasEntity** _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp1_ = entitas_world_getEntities (self, NULL, &_tmp0_);
	entities = _tmp1_;
	entities_length1 = _tmp0_;
	_entities_size_ = entities_length1;
	_tmp2_ = entities;
	_tmp2__length1 = entities_length1;
	{
		EntitasEntity** entity_collection = NULL;
		gint entity_collection_length1 = 0;
		gint _entity_collection_size_ = 0;
		gint entity_it = 0;
		entity_collection = _tmp2_;
		entity_collection_length1 = _tmp2__length1;
		for (entity_it = 0; entity_it < _tmp2__length1; entity_it = entity_it + 1) {
			EntitasEntity* _tmp3_ = NULL;
			EntitasEntity* entity = NULL;
			_tmp3_ = _g_object_ref0 (entity_collection[entity_it]);
			entity = _tmp3_;
			{
				EntitasEntity* _tmp4_ = NULL;
				_tmp4_ = entity;
				entitas_world_destroyEntity (self, _tmp4_, &_inner_error_);
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					if (_inner_error_->domain == ENTITAS_ECS_EXCEPTION) {
						g_propagate_error (error, _inner_error_);
						_g_object_unref0 (entity);
						entities = (_vala_array_free (entities, entities_length1, (GDestroyNotify) g_object_unref), NULL);
						return;
					} else {
						_g_object_unref0 (entity);
						entities = (_vala_array_free (entities, entities_length1, (GDestroyNotify) g_object_unref), NULL);
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
				}
				_g_object_unref0 (entity);
			}
		}
	}
	entities = (_vala_array_free (entities, entities_length1, (GDestroyNotify) g_object_unref), NULL);
}


/**
         * Check if pool has this entity
         *
         * @param entitas.Entity entity
         * @returns boolean
         */
gboolean entitas_world_hasEntity (EntitasWorld* self, EntitasEntity* entity) {
	gboolean result = FALSE;
	GeeHashMap* _tmp0_ = NULL;
	EntitasEntity* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (entity != NULL, FALSE);
	_tmp0_ = self->priv->_entities;
	_tmp1_ = entity;
	_tmp2_ = entitas_entity_get_id (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp0_, _tmp3_);
	result = _tmp4_;
	return result;
}


/**
         * Gets all of the entities
         *
         * @returns Array<entitas.Entity>
         */
static void _vala_array_add15 (EntitasEntity*** array, int* length, int* size, EntitasEntity* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (EntitasEntity*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static EntitasEntity** _vala_array_dup8 (EntitasEntity** self, int length) {
	EntitasEntity** result;
	int i;
	result = g_new0 (EntitasEntity*, length + 1);
	for (i = 0; i < length; i++) {
		EntitasEntity* _tmp0_ = NULL;
		_tmp0_ = _g_object_ref0 (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


EntitasEntity** entitas_world_getEntities (EntitasWorld* self, EntitasIMatcher* matcher, int* result_length1) {
	EntitasEntity** result = NULL;
	EntitasIMatcher* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = matcher;
	if (_tmp0_ != NULL) {
		EntitasIMatcher* _tmp1_ = NULL;
		EntitasGroup* _tmp2_ = NULL;
		EntitasGroup* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		EntitasEntity** _tmp5_ = NULL;
		EntitasEntity** _tmp6_ = NULL;
		gint _tmp6__length1 = 0;
		EntitasEntity** _tmp7_ = NULL;
		gint _tmp7__length1 = 0;
		_tmp1_ = matcher;
		_tmp2_ = entitas_world_getGroup (self, _tmp1_);
		_tmp3_ = _tmp2_;
		_tmp5_ = entitas_group_getEntities (_tmp3_, &_tmp4_);
		_tmp6_ = _tmp5_;
		_tmp6__length1 = _tmp4_;
		_g_object_unref0 (_tmp3_);
		_tmp7_ = _tmp6_;
		_tmp7__length1 = _tmp6__length1;
		if (result_length1) {
			*result_length1 = _tmp7__length1;
		}
		result = _tmp7_;
		return result;
	} else {
		EntitasEntity** _tmp8_ = NULL;
		gint _tmp8__length1 = 0;
		EntitasEntity** _tmp24_ = NULL;
		gint _tmp24__length1 = 0;
		EntitasEntity** _tmp25_ = NULL;
		gint _tmp25__length1 = 0;
		EntitasEntity** _tmp26_ = NULL;
		gint _tmp26__length1 = 0;
		_tmp8_ = self->priv->_entitiesCache;
		_tmp8__length1 = self->priv->_entitiesCache_length1;
		if (_tmp8__length1 == 0) {
			EntitasEntity** _tmp9_ = NULL;
			gint _tmp9__length1 = 0;
			EntitasEntity** _tmp10_ = NULL;
			_tmp9_ = self->priv->_entitiesCache;
			_tmp9__length1 = self->priv->_entitiesCache_length1;
			_tmp10_ = g_new0 (EntitasEntity*, _tmp9__length1 + 1);
			self->priv->_entitiesCache = (_vala_array_free (self->priv->_entitiesCache, self->priv->_entitiesCache_length1, (GDestroyNotify) g_object_unref), NULL);
			self->priv->_entitiesCache = _tmp10_;
			self->priv->_entitiesCache_length1 = _tmp9__length1;
			self->priv->__entitiesCache_size_ = self->priv->_entitiesCache_length1;
			{
				GeeIterator* _e_it = NULL;
				GeeHashMap* _tmp11_ = NULL;
				GeeCollection* _tmp12_ = NULL;
				GeeCollection* _tmp13_ = NULL;
				GeeCollection* _tmp14_ = NULL;
				GeeIterator* _tmp15_ = NULL;
				GeeIterator* _tmp16_ = NULL;
				_tmp11_ = self->priv->_entities;
				_tmp12_ = gee_abstract_map_get_values ((GeeMap*) _tmp11_);
				_tmp13_ = _tmp12_;
				_tmp14_ = _tmp13_;
				_tmp15_ = gee_iterable_iterator ((GeeIterable*) _tmp14_);
				_tmp16_ = _tmp15_;
				_g_object_unref0 (_tmp14_);
				_e_it = _tmp16_;
				while (TRUE) {
					GeeIterator* _tmp17_ = NULL;
					gboolean _tmp18_ = FALSE;
					EntitasEntity* e = NULL;
					GeeIterator* _tmp19_ = NULL;
					gpointer _tmp20_ = NULL;
					EntitasEntity** _tmp21_ = NULL;
					gint _tmp21__length1 = 0;
					EntitasEntity* _tmp22_ = NULL;
					EntitasEntity* _tmp23_ = NULL;
					_tmp17_ = _e_it;
					_tmp18_ = gee_iterator_next (_tmp17_);
					if (!_tmp18_) {
						break;
					}
					_tmp19_ = _e_it;
					_tmp20_ = gee_iterator_get (_tmp19_);
					e = (EntitasEntity*) _tmp20_;
					_tmp21_ = self->priv->_entitiesCache;
					_tmp21__length1 = self->priv->_entitiesCache_length1;
					_tmp22_ = e;
					_tmp23_ = _g_object_ref0 (_tmp22_);
					_vala_array_add15 (&self->priv->_entitiesCache, &self->priv->_entitiesCache_length1, &self->priv->__entitiesCache_size_, _tmp23_);
					_g_object_unref0 (e);
				}
				_g_object_unref0 (_e_it);
			}
		}
		_tmp24_ = self->priv->_entitiesCache;
		_tmp24__length1 = self->priv->_entitiesCache_length1;
		_tmp25_ = (_tmp24_ != NULL) ? _vala_array_dup8 (_tmp24_, _tmp24__length1) : ((gpointer) _tmp24_);
		_tmp25__length1 = _tmp24__length1;
		_tmp26_ = _tmp25_;
		_tmp26__length1 = _tmp25__length1;
		if (result_length1) {
			*result_length1 = _tmp26__length1;
		}
		result = _tmp26_;
		return result;
	}
}


/**
         * add System
         * @param entitas.ISystem|Function
         * @returns entitas.ISystem
         */
static void _vala_array_add16 (EntitasIInitializeSystem*** array, int* length, int* size, EntitasIInitializeSystem* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (EntitasIInitializeSystem*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add17 (EntitasIExecuteSystem*** array, int* length, int* size, EntitasIExecuteSystem* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (EntitasIExecuteSystem*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


EntitasWorld* entitas_world_add (EntitasWorld* self, EntitasISystem* system) {
	EntitasWorld* result = NULL;
	EntitasISystem* _tmp0_ = NULL;
	EntitasISystem* _tmp2_ = NULL;
	EntitasISystem* _tmp6_ = NULL;
	EntitasWorld* _tmp10_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (system != NULL, NULL);
	_tmp0_ = system;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, ENTITAS_TYPE_ISET_WORLD)) {
		EntitasISystem* _tmp1_ = NULL;
		_tmp1_ = system;
		entitas_iset_world_setWorld (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, ENTITAS_TYPE_ISET_WORLD, EntitasISetWorld), self);
	}
	_tmp2_ = system;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, ENTITAS_TYPE_IINITIALIZE_SYSTEM)) {
		EntitasIInitializeSystem** _tmp3_ = NULL;
		gint _tmp3__length1 = 0;
		EntitasISystem* _tmp4_ = NULL;
		EntitasIInitializeSystem* _tmp5_ = NULL;
		_tmp3_ = self->priv->_initializeSystems;
		_tmp3__length1 = self->priv->_initializeSystems_length1;
		_tmp4_ = system;
		_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, ENTITAS_TYPE_IINITIALIZE_SYSTEM, EntitasIInitializeSystem));
		_vala_array_add16 (&self->priv->_initializeSystems, &self->priv->_initializeSystems_length1, &self->priv->__initializeSystems_size_, _tmp5_);
	}
	_tmp6_ = system;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp6_, ENTITAS_TYPE_IEXECUTE_SYSTEM)) {
		EntitasIExecuteSystem** _tmp7_ = NULL;
		gint _tmp7__length1 = 0;
		EntitasISystem* _tmp8_ = NULL;
		EntitasIExecuteSystem* _tmp9_ = NULL;
		_tmp7_ = self->priv->_executeSystems;
		_tmp7__length1 = self->priv->_executeSystems_length1;
		_tmp8_ = system;
		_tmp9_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, ENTITAS_TYPE_IEXECUTE_SYSTEM, EntitasIExecuteSystem));
		_vala_array_add17 (&self->priv->_executeSystems, &self->priv->_executeSystems_length1, &self->priv->__executeSystems_size_, _tmp9_);
	}
	_tmp10_ = _g_object_ref0 (self);
	result = _tmp10_;
	return result;
}


/**
         * Initialize Systems
         */
EntitasWorld* entitas_world_initialize (EntitasWorld* self) {
	EntitasWorld* result = NULL;
	EntitasIInitializeSystem** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	EntitasWorld* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_initializeSystems;
	_tmp0__length1 = self->priv->_initializeSystems_length1;
	{
		EntitasIInitializeSystem** sys_collection = NULL;
		gint sys_collection_length1 = 0;
		gint _sys_collection_size_ = 0;
		gint sys_it = 0;
		sys_collection = _tmp0_;
		sys_collection_length1 = _tmp0__length1;
		for (sys_it = 0; sys_it < _tmp0__length1; sys_it = sys_it + 1) {
			EntitasIInitializeSystem* _tmp1_ = NULL;
			EntitasIInitializeSystem* sys = NULL;
			_tmp1_ = _g_object_ref0 (sys_collection[sys_it]);
			sys = _tmp1_;
			{
				EntitasIInitializeSystem* _tmp2_ = NULL;
				_tmp2_ = sys;
				entitas_iinitialize_system_initialize (_tmp2_);
				_g_object_unref0 (sys);
			}
		}
	}
	_tmp3_ = _g_object_ref0 (self);
	result = _tmp3_;
	return result;
}


/**
         * Execute sustems
         */
void entitas_world_execute (EntitasWorld* self) {
	EntitasIExecuteSystem** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_executeSystems;
	_tmp0__length1 = self->priv->_executeSystems_length1;
	{
		EntitasIExecuteSystem** sys_collection = NULL;
		gint sys_collection_length1 = 0;
		gint _sys_collection_size_ = 0;
		gint sys_it = 0;
		sys_collection = _tmp0_;
		sys_collection_length1 = _tmp0__length1;
		for (sys_it = 0; sys_it < _tmp0__length1; sys_it = sys_it + 1) {
			EntitasIExecuteSystem* _tmp1_ = NULL;
			EntitasIExecuteSystem* sys = NULL;
			_tmp1_ = _g_object_ref0 (sys_collection[sys_it]);
			sys = _tmp1_;
			{
				EntitasIExecuteSystem* _tmp2_ = NULL;
				_tmp2_ = sys;
				entitas_iexecute_system_execute (_tmp2_);
				_g_object_unref0 (sys);
			}
		}
	}
}


/**
         * Gets all of the entities that match
         *
         * @param entias.IMatcher matcher
         * @returns entitas.Group
         */
EntitasGroup* entitas_world_getGroup (EntitasWorld* self, EntitasIMatcher* matcher) {
	EntitasGroup* result = NULL;
	EntitasGroup* group = NULL;
	GeeHashMap* _tmp0_ = NULL;
	EntitasIMatcher* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (matcher != NULL, NULL);
	_tmp0_ = self->priv->_groups;
	_tmp1_ = matcher;
	_tmp2_ = entitas_imatcher_get_id (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp0_, _tmp3_);
	if (_tmp4_) {
		GeeHashMap* _tmp5_ = NULL;
		EntitasIMatcher* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		gpointer _tmp9_ = NULL;
		_tmp5_ = self->priv->_groups;
		_tmp6_ = matcher;
		_tmp7_ = entitas_imatcher_get_id (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp5_, _tmp8_);
		_g_object_unref0 (group);
		group = (EntitasGroup*) _tmp9_;
	} else {
		EntitasIMatcher* _tmp10_ = NULL;
		EntitasGroup* _tmp11_ = NULL;
		EntitasEntity** entities = NULL;
		gint _tmp12_ = 0;
		EntitasEntity** _tmp13_ = NULL;
		gint entities_length1 = 0;
		gint _entities_size_ = 0;
		GeeHashMap* _tmp18_ = NULL;
		EntitasIMatcher* _tmp19_ = NULL;
		const gchar* _tmp20_ = NULL;
		const gchar* _tmp21_ = NULL;
		EntitasGroup* _tmp22_ = NULL;
		EntitasIMatcher* _tmp23_ = NULL;
		gint* _tmp24_ = NULL;
		gint _tmp24__length1 = 0;
		gint* _tmp25_ = NULL;
		gint _tmp25__length1 = 0;
		EntitasGroupsChanged* _tmp37_ = NULL;
		EntitasGroup* _tmp38_ = NULL;
		_tmp10_ = matcher;
		_tmp11_ = entitas_group_new (_tmp10_);
		_g_object_unref0 (group);
		group = _tmp11_;
		_tmp13_ = entitas_world_getEntities (self, NULL, &_tmp12_);
		entities = _tmp13_;
		entities_length1 = _tmp12_;
		_entities_size_ = entities_length1;
		{
			EntitasEntity** _tmp14_ = NULL;
			gint _tmp14__length1 = 0;
			_tmp14_ = entities;
			_tmp14__length1 = entities_length1;
			{
				EntitasEntity** entity_collection = NULL;
				gint entity_collection_length1 = 0;
				gint _entity_collection_size_ = 0;
				gint entity_it = 0;
				entity_collection = _tmp14_;
				entity_collection_length1 = _tmp14__length1;
				for (entity_it = 0; entity_it < _tmp14__length1; entity_it = entity_it + 1) {
					EntitasEntity* _tmp15_ = NULL;
					EntitasEntity* entity = NULL;
					_tmp15_ = _g_object_ref0 (entity_collection[entity_it]);
					entity = _tmp15_;
					{
						EntitasGroup* _tmp16_ = NULL;
						EntitasEntity* _tmp17_ = NULL;
						_tmp16_ = group;
						_tmp17_ = entity;
						entitas_group_handleEntitySilently (_tmp16_, _tmp17_, &_inner_error_);
						if (G_UNLIKELY (_inner_error_ != NULL)) {
							_g_object_unref0 (entity);
							goto __catch3_g_error;
						}
						_g_object_unref0 (entity);
					}
				}
			}
		}
		goto __finally3;
		__catch3_g_error:
		{
			GError* e = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_vala_assert (FALSE, "false");
			_g_error_free0 (e);
		}
		__finally3:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			entities = (_vala_array_free (entities, entities_length1, (GDestroyNotify) g_object_unref), NULL);
			_g_object_unref0 (group);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp18_ = self->priv->_groups;
		_tmp19_ = matcher;
		_tmp20_ = entitas_imatcher_get_id (_tmp19_);
		_tmp21_ = _tmp20_;
		_tmp22_ = group;
		gee_abstract_map_set ((GeeAbstractMap*) _tmp18_, _tmp21_, _tmp22_);
		_tmp23_ = matcher;
		_tmp24_ = entitas_imatcher_get_indices (_tmp23_, &_tmp24__length1);
		_tmp25_ = _tmp24_;
		_tmp25__length1 = _tmp24__length1;
		{
			gint* index_collection = NULL;
			gint index_collection_length1 = 0;
			gint _index_collection_size_ = 0;
			gint index_it = 0;
			index_collection = _tmp25_;
			index_collection_length1 = _tmp25__length1;
			for (index_it = 0; index_it < _tmp25__length1; index_it = index_it + 1) {
				gint index = 0;
				index = index_collection[index_it];
				{
					GeeArrayList** _tmp26_ = NULL;
					gint _tmp26__length1 = 0;
					gint _tmp27_ = 0;
					GeeArrayList* _tmp28_ = NULL;
					GeeArrayList** _tmp33_ = NULL;
					gint _tmp33__length1 = 0;
					gint _tmp34_ = 0;
					GeeArrayList* _tmp35_ = NULL;
					EntitasGroup* _tmp36_ = NULL;
					_tmp26_ = self->priv->_groupsForIndex;
					_tmp26__length1 = self->priv->_groupsForIndex_length1;
					_tmp27_ = index;
					_tmp28_ = _tmp26_[_tmp27_];
					if (_tmp28_ == NULL) {
						GeeArrayList** _tmp29_ = NULL;
						gint _tmp29__length1 = 0;
						gint _tmp30_ = 0;
						GeeArrayList* _tmp31_ = NULL;
						GeeArrayList* _tmp32_ = NULL;
						_tmp29_ = self->priv->_groupsForIndex;
						_tmp29__length1 = self->priv->_groupsForIndex_length1;
						_tmp30_ = index;
						_tmp31_ = gee_array_list_new (ENTITAS_TYPE_GROUP, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
						_g_object_unref0 (_tmp29_[_tmp30_]);
						_tmp29_[_tmp30_] = _tmp31_;
						_tmp32_ = _tmp29_[_tmp30_];
					}
					_tmp33_ = self->priv->_groupsForIndex;
					_tmp33__length1 = self->priv->_groupsForIndex_length1;
					_tmp34_ = index;
					_tmp35_ = _tmp33_[_tmp34_];
					_tmp36_ = group;
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp35_, _tmp36_);
				}
			}
		}
		_tmp37_ = self->priv->_onGroupCreated;
		_tmp38_ = group;
		entitas_groups_changed_dispatch (_tmp37_, self, _tmp38_);
		entities = (_vala_array_free (entities, entities_length1, (GDestroyNotify) g_object_unref), NULL);
	}
	result = group;
	return result;
}


/**
         * @param entitas.Entity entity
         * @param number index
         * @param entitas.IComponent component
         */
void entitas_world_updateGroupsComponentAddedOrRemoved (EntitasWorld* self, EntitasEntity* entity, gint index, EntitasIComponent* component) {
	gint _tmp0_ = 0;
	GeeArrayList** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (entity != NULL);
	g_return_if_fail (component != NULL);
	_tmp0_ = index;
	_tmp1_ = self->priv->_groupsForIndex;
	_tmp1__length1 = self->priv->_groupsForIndex_length1;
	if ((_tmp0_ + 1) <= _tmp1__length1) {
		GeeArrayList* groups = NULL;
		GeeArrayList** _tmp2_ = NULL;
		gint _tmp2__length1 = 0;
		gint _tmp3_ = 0;
		GeeArrayList* _tmp4_ = NULL;
		GeeArrayList* _tmp5_ = NULL;
		GeeArrayList* _tmp6_ = NULL;
		_tmp2_ = self->priv->_groupsForIndex;
		_tmp2__length1 = self->priv->_groupsForIndex_length1;
		_tmp3_ = index;
		_tmp4_ = _tmp2_[_tmp3_];
		_tmp5_ = _g_object_ref0 (_tmp4_);
		groups = _tmp5_;
		_tmp6_ = groups;
		if (_tmp6_ != NULL) {
			{
				{
					GeeArrayList* _group_list = NULL;
					GeeArrayList* _tmp7_ = NULL;
					GeeArrayList* _tmp8_ = NULL;
					gint _group_size = 0;
					GeeArrayList* _tmp9_ = NULL;
					gint _tmp10_ = 0;
					gint _tmp11_ = 0;
					gint _group_index = 0;
					_tmp7_ = groups;
					_tmp8_ = _g_object_ref0 (_tmp7_);
					_group_list = _tmp8_;
					_tmp9_ = _group_list;
					_tmp10_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp9_);
					_tmp11_ = _tmp10_;
					_group_size = _tmp11_;
					_group_index = -1;
					while (TRUE) {
						gint _tmp12_ = 0;
						gint _tmp13_ = 0;
						gint _tmp14_ = 0;
						EntitasGroup* group = NULL;
						GeeArrayList* _tmp15_ = NULL;
						gint _tmp16_ = 0;
						gpointer _tmp17_ = NULL;
						EntitasGroup* _tmp18_ = NULL;
						EntitasEntity* _tmp19_ = NULL;
						gint _tmp20_ = 0;
						EntitasIComponent* _tmp21_ = NULL;
						_tmp12_ = _group_index;
						_group_index = _tmp12_ + 1;
						_tmp13_ = _group_index;
						_tmp14_ = _group_size;
						if (!(_tmp13_ < _tmp14_)) {
							break;
						}
						_tmp15_ = _group_list;
						_tmp16_ = _group_index;
						_tmp17_ = gee_abstract_list_get ((GeeAbstractList*) _tmp15_, _tmp16_);
						group = (EntitasGroup*) _tmp17_;
						_tmp18_ = group;
						_tmp19_ = entity;
						_tmp20_ = index;
						_tmp21_ = component;
						entitas_group_handleEntity (_tmp18_, _tmp19_, _tmp20_, _tmp21_, &_inner_error_);
						if (G_UNLIKELY (_inner_error_ != NULL)) {
							_g_object_unref0 (group);
							_g_object_unref0 (_group_list);
							goto __catch4_g_error;
						}
						_g_object_unref0 (group);
					}
					_g_object_unref0 (_group_list);
				}
			}
			goto __finally4;
			__catch4_g_error:
			{
				GError* e = NULL;
				e = _inner_error_;
				_inner_error_ = NULL;
				_vala_assert (FALSE, "false");
				_g_error_free0 (e);
			}
			__finally4:
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_object_unref0 (groups);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
		}
		_g_object_unref0 (groups);
	}
}


/**
         * @param entitas.Entity entity
         * @param number index
         * @param entitas.IComponent previousComponent
         * @param entitas.IComponent newComponent
         */
void entitas_world_updateGroupsComponentReplaced (EntitasWorld* self, EntitasEntity* entity, gint index, EntitasIComponent* previousComponent, EntitasIComponent* newComponent) {
	gint _tmp0_ = 0;
	GeeArrayList** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (entity != NULL);
	g_return_if_fail (previousComponent != NULL);
	g_return_if_fail (newComponent != NULL);
	_tmp0_ = index;
	_tmp1_ = self->priv->_groupsForIndex;
	_tmp1__length1 = self->priv->_groupsForIndex_length1;
	if ((_tmp0_ + 1) <= _tmp1__length1) {
		GeeArrayList* groups = NULL;
		GeeArrayList** _tmp2_ = NULL;
		gint _tmp2__length1 = 0;
		gint _tmp3_ = 0;
		GeeArrayList* _tmp4_ = NULL;
		GeeArrayList* _tmp5_ = NULL;
		GeeArrayList* _tmp6_ = NULL;
		_tmp2_ = self->priv->_groupsForIndex;
		_tmp2__length1 = self->priv->_groupsForIndex_length1;
		_tmp3_ = index;
		_tmp4_ = _tmp2_[_tmp3_];
		_tmp5_ = _g_object_ref0 (_tmp4_);
		groups = _tmp5_;
		_tmp6_ = groups;
		if (_tmp6_ != NULL) {
			{
				GeeArrayList* _group_list = NULL;
				GeeArrayList* _tmp7_ = NULL;
				GeeArrayList* _tmp8_ = NULL;
				gint _group_size = 0;
				GeeArrayList* _tmp9_ = NULL;
				gint _tmp10_ = 0;
				gint _tmp11_ = 0;
				gint _group_index = 0;
				_tmp7_ = groups;
				_tmp8_ = _g_object_ref0 (_tmp7_);
				_group_list = _tmp8_;
				_tmp9_ = _group_list;
				_tmp10_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp9_);
				_tmp11_ = _tmp10_;
				_group_size = _tmp11_;
				_group_index = -1;
				while (TRUE) {
					gint _tmp12_ = 0;
					gint _tmp13_ = 0;
					gint _tmp14_ = 0;
					EntitasGroup* group = NULL;
					GeeArrayList* _tmp15_ = NULL;
					gint _tmp16_ = 0;
					gpointer _tmp17_ = NULL;
					EntitasGroup* _tmp18_ = NULL;
					EntitasEntity* _tmp19_ = NULL;
					gint _tmp20_ = 0;
					EntitasIComponent* _tmp21_ = NULL;
					EntitasIComponent* _tmp22_ = NULL;
					_tmp12_ = _group_index;
					_group_index = _tmp12_ + 1;
					_tmp13_ = _group_index;
					_tmp14_ = _group_size;
					if (!(_tmp13_ < _tmp14_)) {
						break;
					}
					_tmp15_ = _group_list;
					_tmp16_ = _group_index;
					_tmp17_ = gee_abstract_list_get ((GeeAbstractList*) _tmp15_, _tmp16_);
					group = (EntitasGroup*) _tmp17_;
					_tmp18_ = group;
					_tmp19_ = entity;
					_tmp20_ = index;
					_tmp21_ = previousComponent;
					_tmp22_ = newComponent;
					entitas_group_updateEntity (_tmp18_, _tmp19_, _tmp20_, _tmp21_, _tmp22_);
					_g_object_unref0 (group);
				}
				_g_object_unref0 (_group_list);
			}
		}
		_g_object_unref0 (groups);
	}
}


/**
         * @param entitas.Entity entity
         */
void entitas_world_onEntityReleased (EntitasWorld* self, EntitasEntity* entity) {
	EntitasEntity* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	EntitasEntity* _tmp3_ = NULL;
	EntitasEntityReleased* _tmp4_ = NULL;
	EntitasEntityReleased* _tmp5_ = NULL;
	GeeHashMap* _tmp6_ = NULL;
	EntitasEntity* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	GQueue* _tmp10_ = NULL;
	EntitasEntity* _tmp11_ = NULL;
	EntitasEntity* _tmp12_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (entity != NULL);
	_tmp0_ = entity;
	_tmp1_ = entitas_entity_get_isEnabled (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		return;
	}
	_tmp3_ = entity;
	_tmp4_ = entitas_entity_get_onEntityReleased (_tmp3_);
	_tmp5_ = _tmp4_;
	entitas_entity_released_remove (_tmp5_, _entitas_world_onEntityReleased_entitas_on_entity_released, self);
	_tmp6_ = self->priv->_retainedEntities;
	_tmp7_ = entity;
	_tmp8_ = entitas_entity_get_id (_tmp7_);
	_tmp9_ = _tmp8_;
	gee_abstract_map_unset ((GeeAbstractMap*) _tmp6_, _tmp9_, NULL);
	_tmp10_ = self->priv->_reusableEntities;
	_tmp11_ = entity;
	_tmp12_ = _g_object_ref0 (_tmp11_);
	g_queue_push_head (_tmp10_, _tmp12_);
}


/**
        * Fast UUID generator, RFC4122 version 4 compliant
        * format xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
        *
        * uid is used as id for entities for better distribution 
        * in hash tables than an incrementing id
        *
        *
        * @author Jeff Ward (jcward.com).
        * @license MIT license
        * @link http://stackoverflow.com/questions/105034/how-to-create-a-guid-uuid-in-javascript/21963136#21963136
        **/
static gchar* entitas_world_uidgen (EntitasWorld* self) {
	gchar* result = NULL;
	gint32 d0 = 0;
	GRand* _tmp0_ = NULL;
	GRand* _tmp1_ = NULL;
	gint32 _tmp2_ = 0;
	gint32 d1 = 0;
	GRand* _tmp3_ = NULL;
	GRand* _tmp4_ = NULL;
	gint32 _tmp5_ = 0;
	gint32 d2 = 0;
	GRand* _tmp6_ = NULL;
	GRand* _tmp7_ = NULL;
	gint32 _tmp8_ = 0;
	gint32 d3 = 0;
	GRand* _tmp9_ = NULL;
	GRand* _tmp10_ = NULL;
	gint32 _tmp11_ = 0;
	gint32 hex00 = 0;
	gint32 hex01 = 0;
	gint32 hex02 = 0;
	gint32 hex03 = 0;
	gint32 hex04 = 0;
	gint32 hex05 = 0;
	gint32 hex06 = 0;
	gint32 hex07 = 0;
	gint32 hex08 = 0;
	gint32 hex09 = 0;
	gint32 hex10 = 0;
	gint32 hex11 = 0;
	gint32 hex12 = 0;
	gint32 hex13 = 0;
	gint32 hex14 = 0;
	GString* sb = NULL;
	GString* _tmp12_ = NULL;
	gchar** _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	const gchar* _tmp14_ = NULL;
	gchar** _tmp15_ = NULL;
	gint _tmp15__length1 = 0;
	const gchar* _tmp16_ = NULL;
	gchar** _tmp17_ = NULL;
	gint _tmp17__length1 = 0;
	const gchar* _tmp18_ = NULL;
	gchar** _tmp19_ = NULL;
	gint _tmp19__length1 = 0;
	const gchar* _tmp20_ = NULL;
	gchar** _tmp21_ = NULL;
	gint _tmp21__length1 = 0;
	const gchar* _tmp22_ = NULL;
	gchar** _tmp23_ = NULL;
	gint _tmp23__length1 = 0;
	const gchar* _tmp24_ = NULL;
	gchar** _tmp25_ = NULL;
	gint _tmp25__length1 = 0;
	const gchar* _tmp26_ = NULL;
	gchar** _tmp27_ = NULL;
	gint _tmp27__length1 = 0;
	const gchar* _tmp28_ = NULL;
	gchar** _tmp29_ = NULL;
	gint _tmp29__length1 = 0;
	const gchar* _tmp30_ = NULL;
	gchar** _tmp31_ = NULL;
	gint _tmp31__length1 = 0;
	const gchar* _tmp32_ = NULL;
	gchar** _tmp33_ = NULL;
	gint _tmp33__length1 = 0;
	const gchar* _tmp34_ = NULL;
	gchar** _tmp35_ = NULL;
	gint _tmp35__length1 = 0;
	const gchar* _tmp36_ = NULL;
	gchar** _tmp37_ = NULL;
	gint _tmp37__length1 = 0;
	const gchar* _tmp38_ = NULL;
	gchar** _tmp39_ = NULL;
	gint _tmp39__length1 = 0;
	const gchar* _tmp40_ = NULL;
	gchar** _tmp41_ = NULL;
	gint _tmp41__length1 = 0;
	const gchar* _tmp42_ = NULL;
	const gchar* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = entitas_world_get_random ();
	_tmp1_ = _tmp0_;
	_tmp2_ = g_rand_int_range (_tmp1_, (gint32) 0, (gint32) 0xffff);
	d0 = _tmp2_;
	_tmp3_ = entitas_world_get_random ();
	_tmp4_ = _tmp3_;
	_tmp5_ = g_rand_int_range (_tmp4_, (gint32) 0, (gint32) 0xffff);
	d1 = _tmp5_;
	_tmp6_ = entitas_world_get_random ();
	_tmp7_ = _tmp6_;
	_tmp8_ = g_rand_int_range (_tmp7_, (gint32) 0, (gint32) 0xffff);
	d2 = _tmp8_;
	_tmp9_ = entitas_world_get_random ();
	_tmp10_ = _tmp9_;
	_tmp11_ = g_rand_int_range (_tmp10_, (gint32) 0, (gint32) 0xffff);
	d3 = _tmp11_;
	hex00 = d0 & 0xff;
	hex01 = (d0 >> 16) & 0xff;
	hex02 = (d0 >> 24) & 0xff;
	hex03 = d1 & 0xff;
	hex04 = (d1 >> 8) & 0xff;
	hex05 = ((d1 >> 16) & 0x0f) | 0x40;
	hex06 = (d1 >> 24) & 0xff;
	hex07 = (d2 & 0x3f) | 0x80;
	hex08 = (d2 >> 8) & 0xff;
	hex09 = (d2 >> 16) & 0xff;
	hex10 = (d2 >> 24) & 0xff;
	hex11 = d3 & 0xff;
	hex12 = (d3 >> 8) & 0xff;
	hex13 = (d3 >> 16) & 0xff;
	hex14 = (d3 >> 24) & 0xff;
	_tmp12_ = g_string_new ("");
	sb = _tmp12_;
	_tmp13_ = self->priv->_hex;
	_tmp13__length1 = self->priv->_hex_length1;
	_tmp14_ = _tmp13_[hex00];
	g_string_append (sb, _tmp14_);
	_tmp15_ = self->priv->_hex;
	_tmp15__length1 = self->priv->_hex_length1;
	_tmp16_ = _tmp15_[hex01];
	g_string_append (sb, _tmp16_);
	_tmp17_ = self->priv->_hex;
	_tmp17__length1 = self->priv->_hex_length1;
	_tmp18_ = _tmp17_[hex02];
	g_string_append (sb, _tmp18_);
	g_string_append (sb, "-");
	_tmp19_ = self->priv->_hex;
	_tmp19__length1 = self->priv->_hex_length1;
	_tmp20_ = _tmp19_[hex03];
	g_string_append (sb, _tmp20_);
	_tmp21_ = self->priv->_hex;
	_tmp21__length1 = self->priv->_hex_length1;
	_tmp22_ = _tmp21_[hex04];
	g_string_append (sb, _tmp22_);
	g_string_append (sb, "-");
	_tmp23_ = self->priv->_hex;
	_tmp23__length1 = self->priv->_hex_length1;
	_tmp24_ = _tmp23_[hex05];
	g_string_append (sb, _tmp24_);
	_tmp25_ = self->priv->_hex;
	_tmp25__length1 = self->priv->_hex_length1;
	_tmp26_ = _tmp25_[hex06];
	g_string_append (sb, _tmp26_);
	g_string_append (sb, "-");
	_tmp27_ = self->priv->_hex;
	_tmp27__length1 = self->priv->_hex_length1;
	_tmp28_ = _tmp27_[hex07];
	g_string_append (sb, _tmp28_);
	_tmp29_ = self->priv->_hex;
	_tmp29__length1 = self->priv->_hex_length1;
	_tmp30_ = _tmp29_[hex08];
	g_string_append (sb, _tmp30_);
	g_string_append (sb, "-");
	_tmp31_ = self->priv->_hex;
	_tmp31__length1 = self->priv->_hex_length1;
	_tmp32_ = _tmp31_[hex09];
	g_string_append (sb, _tmp32_);
	_tmp33_ = self->priv->_hex;
	_tmp33__length1 = self->priv->_hex_length1;
	_tmp34_ = _tmp33_[hex10];
	g_string_append (sb, _tmp34_);
	_tmp35_ = self->priv->_hex;
	_tmp35__length1 = self->priv->_hex_length1;
	_tmp36_ = _tmp35_[hex11];
	g_string_append (sb, _tmp36_);
	_tmp37_ = self->priv->_hex;
	_tmp37__length1 = self->priv->_hex_length1;
	_tmp38_ = _tmp37_[hex12];
	g_string_append (sb, _tmp38_);
	_tmp39_ = self->priv->_hex;
	_tmp39__length1 = self->priv->_hex_length1;
	_tmp40_ = _tmp39_[hex13];
	g_string_append (sb, _tmp40_);
	_tmp41_ = self->priv->_hex;
	_tmp41__length1 = self->priv->_hex_length1;
	_tmp42_ = _tmp41_[hex14];
	g_string_append (sb, _tmp42_);
	_tmp43_ = sb->str;
	_tmp44_ = g_strdup (_tmp43_);
	result = _tmp44_;
	_g_string_free0 (sb);
	return result;
}


gchar** entitas_world_get_components (int* result_length1) {
	gchar** result;
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	_tmp0_ = entitas_world__components;
	_tmp0__length1 = entitas_world__components_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


EntitasWorld* entitas_world_get_instance (void) {
	EntitasWorld* result;
	EntitasWorld* _tmp0_ = NULL;
	_tmp0_ = entitas_world__instance;
	result = _tmp0_;
	return result;
}


GRand* entitas_world_get_random (void) {
	GRand* result;
	GRand* _tmp0_ = NULL;
	_tmp0_ = entitas_world__random;
	result = _tmp0_;
	return result;
}


gint entitas_world_get_componentsCount (EntitasWorld* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_totalComponents;
	result = _tmp0_;
	return result;
}


gint entitas_world_get_count (EntitasWorld* self) {
	gint result;
	GeeHashMap* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_entities;
	_tmp1_ = gee_abstract_map_get_size ((GeeMap*) _tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}


gint entitas_world_get_reusableEntitiesCount (EntitasWorld* self) {
	gint result;
	GQueue* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_reusableEntities;
	_tmp1_ = _tmp0_->length;
	result = (gint) _tmp1_;
	return result;
}


gint entitas_world_get_retainedEntitiesCount (EntitasWorld* self) {
	gint result;
	GeeHashMap* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_retainedEntities;
	_tmp1_ = gee_abstract_map_get_size ((GeeMap*) _tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}


EntitasWorldChanged* entitas_world_get_onEntityCreated (EntitasWorld* self) {
	EntitasWorldChanged* result;
	EntitasWorldChanged* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_onEntityCreated;
	result = _tmp0_;
	return result;
}


EntitasWorldChanged* entitas_world_get_onEntityWillBeDestroyed (EntitasWorld* self) {
	EntitasWorldChanged* result;
	EntitasWorldChanged* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_onEntityWillBeDestroyed;
	result = _tmp0_;
	return result;
}


EntitasWorldChanged* entitas_world_get_onEntityDestroyed (EntitasWorld* self) {
	EntitasWorldChanged* result;
	EntitasWorldChanged* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_onEntityDestroyed;
	result = _tmp0_;
	return result;
}


EntitasGroupsChanged* entitas_world_get_onGroupCreated (EntitasWorld* self) {
	EntitasGroupsChanged* result;
	EntitasGroupsChanged* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_onGroupCreated;
	result = _tmp0_;
	return result;
}


const gchar* entitas_world_get_name (EntitasWorld* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}


static void entitas_world_class_init (EntitasWorldClass * klass) {
	entitas_world_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (EntitasWorldPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_entitas_world_get_property;
	G_OBJECT_CLASS (klass)->finalize = entitas_world_finalize;
	/**
	         * The total number of components in this pool
	         * @type number
	         * @name entitas.World#totalComponents */
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENTITAS_WORLD_COMPONENTS_COUNT, g_param_spec_int ("componentsCount", "componentsCount", "componentsCount", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	/**
	         * Count of active entities
	         * @type number
	         * @name entitas.World#count */
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENTITAS_WORLD_COUNT, g_param_spec_int ("count", "count", "count", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	/**
	         * Count of entities waiting to be recycled
	         * @type number
	         * @name entitas.World#reusableEntitiesCount */
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENTITAS_WORLD_REUSABLE_ENTITIES_COUNT, g_param_spec_int ("reusableEntitiesCount", "reusableEntitiesCount", "reusableEntitiesCount", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	/**
	         * Count of entities that sill have references
	         * @type number
	         * @name entitas.World#retainedEntitiesCount */
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENTITAS_WORLD_RETAINED_ENTITIES_COUNT, g_param_spec_int ("retainedEntitiesCount", "retainedEntitiesCount", "retainedEntitiesCount", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	/**
	         * Subscribe to Entity Created Event
	         * @type entitas.utils.ISignal */
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENTITAS_WORLD_ON_ENTITY_CREATED, g_param_spec_object ("onEntityCreated", "onEntityCreated", "onEntityCreated", ENTITAS_TYPE_WORLD_CHANGED, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	/**
	         * Subscribe to Entity Will Be Destroyed Event
	         * @type entitas.utils.ISignal */
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENTITAS_WORLD_ON_ENTITY_WILL_BE_DESTROYED, g_param_spec_object ("onEntityWillBeDestroyed", "onEntityWillBeDestroyed", "onEntityWillBeDestroyed", ENTITAS_TYPE_WORLD_CHANGED, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	/**
	         * Subscribe to Entity Destroyed Event
	         * @type entitas.utils.ISignal */
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENTITAS_WORLD_ON_ENTITY_DESTROYED, g_param_spec_object ("onEntityDestroyed", "onEntityDestroyed", "onEntityDestroyed", ENTITAS_TYPE_WORLD_CHANGED, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	/**
	         * Subscribe to Group Created Event
	         * @type entitas.utils.ISignal */
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENTITAS_WORLD_ON_GROUP_CREATED, g_param_spec_object ("onGroupCreated", "onGroupCreated", "onGroupCreated", ENTITAS_TYPE_GROUPS_CHANGED, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	/**
	         * Entity name for debugging
	         * @type string */
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENTITAS_WORLD_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void entitas_world_instance_init (EntitasWorld * self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	gchar* _tmp33_ = NULL;
	gchar* _tmp34_ = NULL;
	gchar* _tmp35_ = NULL;
	gchar* _tmp36_ = NULL;
	gchar* _tmp37_ = NULL;
	gchar* _tmp38_ = NULL;
	gchar* _tmp39_ = NULL;
	gchar* _tmp40_ = NULL;
	gchar* _tmp41_ = NULL;
	gchar* _tmp42_ = NULL;
	gchar* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
	gchar* _tmp45_ = NULL;
	gchar* _tmp46_ = NULL;
	gchar* _tmp47_ = NULL;
	gchar* _tmp48_ = NULL;
	gchar* _tmp49_ = NULL;
	gchar* _tmp50_ = NULL;
	gchar* _tmp51_ = NULL;
	gchar* _tmp52_ = NULL;
	gchar* _tmp53_ = NULL;
	gchar* _tmp54_ = NULL;
	gchar* _tmp55_ = NULL;
	gchar* _tmp56_ = NULL;
	gchar* _tmp57_ = NULL;
	gchar* _tmp58_ = NULL;
	gchar* _tmp59_ = NULL;
	gchar* _tmp60_ = NULL;
	gchar* _tmp61_ = NULL;
	gchar* _tmp62_ = NULL;
	gchar* _tmp63_ = NULL;
	gchar* _tmp64_ = NULL;
	gchar* _tmp65_ = NULL;
	gchar* _tmp66_ = NULL;
	gchar* _tmp67_ = NULL;
	gchar* _tmp68_ = NULL;
	gchar* _tmp69_ = NULL;
	gchar* _tmp70_ = NULL;
	gchar* _tmp71_ = NULL;
	gchar* _tmp72_ = NULL;
	gchar* _tmp73_ = NULL;
	gchar* _tmp74_ = NULL;
	gchar* _tmp75_ = NULL;
	gchar* _tmp76_ = NULL;
	gchar* _tmp77_ = NULL;
	gchar* _tmp78_ = NULL;
	gchar* _tmp79_ = NULL;
	gchar* _tmp80_ = NULL;
	gchar* _tmp81_ = NULL;
	gchar* _tmp82_ = NULL;
	gchar* _tmp83_ = NULL;
	gchar* _tmp84_ = NULL;
	gchar* _tmp85_ = NULL;
	gchar* _tmp86_ = NULL;
	gchar* _tmp87_ = NULL;
	gchar* _tmp88_ = NULL;
	gchar* _tmp89_ = NULL;
	gchar* _tmp90_ = NULL;
	gchar* _tmp91_ = NULL;
	gchar* _tmp92_ = NULL;
	gchar* _tmp93_ = NULL;
	gchar* _tmp94_ = NULL;
	gchar* _tmp95_ = NULL;
	gchar* _tmp96_ = NULL;
	gchar* _tmp97_ = NULL;
	gchar* _tmp98_ = NULL;
	gchar* _tmp99_ = NULL;
	gchar* _tmp100_ = NULL;
	gchar* _tmp101_ = NULL;
	gchar* _tmp102_ = NULL;
	gchar* _tmp103_ = NULL;
	gchar* _tmp104_ = NULL;
	gchar* _tmp105_ = NULL;
	gchar* _tmp106_ = NULL;
	gchar* _tmp107_ = NULL;
	gchar* _tmp108_ = NULL;
	gchar* _tmp109_ = NULL;
	gchar* _tmp110_ = NULL;
	gchar* _tmp111_ = NULL;
	gchar* _tmp112_ = NULL;
	gchar* _tmp113_ = NULL;
	gchar* _tmp114_ = NULL;
	gchar* _tmp115_ = NULL;
	gchar* _tmp116_ = NULL;
	gchar* _tmp117_ = NULL;
	gchar* _tmp118_ = NULL;
	gchar* _tmp119_ = NULL;
	gchar* _tmp120_ = NULL;
	gchar* _tmp121_ = NULL;
	gchar* _tmp122_ = NULL;
	gchar* _tmp123_ = NULL;
	gchar* _tmp124_ = NULL;
	gchar* _tmp125_ = NULL;
	gchar* _tmp126_ = NULL;
	gchar* _tmp127_ = NULL;
	gchar* _tmp128_ = NULL;
	gchar* _tmp129_ = NULL;
	gchar* _tmp130_ = NULL;
	gchar* _tmp131_ = NULL;
	gchar* _tmp132_ = NULL;
	gchar* _tmp133_ = NULL;
	gchar* _tmp134_ = NULL;
	gchar* _tmp135_ = NULL;
	gchar* _tmp136_ = NULL;
	gchar* _tmp137_ = NULL;
	gchar* _tmp138_ = NULL;
	gchar* _tmp139_ = NULL;
	gchar* _tmp140_ = NULL;
	gchar* _tmp141_ = NULL;
	gchar* _tmp142_ = NULL;
	gchar* _tmp143_ = NULL;
	gchar* _tmp144_ = NULL;
	gchar* _tmp145_ = NULL;
	gchar* _tmp146_ = NULL;
	gchar* _tmp147_ = NULL;
	gchar* _tmp148_ = NULL;
	gchar* _tmp149_ = NULL;
	gchar* _tmp150_ = NULL;
	gchar* _tmp151_ = NULL;
	gchar* _tmp152_ = NULL;
	gchar* _tmp153_ = NULL;
	gchar* _tmp154_ = NULL;
	gchar* _tmp155_ = NULL;
	gchar* _tmp156_ = NULL;
	gchar* _tmp157_ = NULL;
	gchar* _tmp158_ = NULL;
	gchar* _tmp159_ = NULL;
	gchar* _tmp160_ = NULL;
	gchar* _tmp161_ = NULL;
	gchar* _tmp162_ = NULL;
	gchar* _tmp163_ = NULL;
	gchar* _tmp164_ = NULL;
	gchar* _tmp165_ = NULL;
	gchar* _tmp166_ = NULL;
	gchar* _tmp167_ = NULL;
	gchar* _tmp168_ = NULL;
	gchar* _tmp169_ = NULL;
	gchar* _tmp170_ = NULL;
	gchar* _tmp171_ = NULL;
	gchar* _tmp172_ = NULL;
	gchar* _tmp173_ = NULL;
	gchar* _tmp174_ = NULL;
	gchar* _tmp175_ = NULL;
	gchar* _tmp176_ = NULL;
	gchar* _tmp177_ = NULL;
	gchar* _tmp178_ = NULL;
	gchar* _tmp179_ = NULL;
	gchar* _tmp180_ = NULL;
	gchar* _tmp181_ = NULL;
	gchar* _tmp182_ = NULL;
	gchar* _tmp183_ = NULL;
	gchar* _tmp184_ = NULL;
	gchar* _tmp185_ = NULL;
	gchar* _tmp186_ = NULL;
	gchar* _tmp187_ = NULL;
	gchar* _tmp188_ = NULL;
	gchar* _tmp189_ = NULL;
	gchar* _tmp190_ = NULL;
	gchar* _tmp191_ = NULL;
	gchar* _tmp192_ = NULL;
	gchar* _tmp193_ = NULL;
	gchar* _tmp194_ = NULL;
	gchar* _tmp195_ = NULL;
	gchar* _tmp196_ = NULL;
	gchar* _tmp197_ = NULL;
	gchar* _tmp198_ = NULL;
	gchar* _tmp199_ = NULL;
	gchar* _tmp200_ = NULL;
	gchar* _tmp201_ = NULL;
	gchar* _tmp202_ = NULL;
	gchar* _tmp203_ = NULL;
	gchar* _tmp204_ = NULL;
	gchar* _tmp205_ = NULL;
	gchar* _tmp206_ = NULL;
	gchar* _tmp207_ = NULL;
	gchar* _tmp208_ = NULL;
	gchar* _tmp209_ = NULL;
	gchar* _tmp210_ = NULL;
	gchar* _tmp211_ = NULL;
	gchar* _tmp212_ = NULL;
	gchar* _tmp213_ = NULL;
	gchar* _tmp214_ = NULL;
	gchar* _tmp215_ = NULL;
	gchar* _tmp216_ = NULL;
	gchar* _tmp217_ = NULL;
	gchar* _tmp218_ = NULL;
	gchar* _tmp219_ = NULL;
	gchar* _tmp220_ = NULL;
	gchar* _tmp221_ = NULL;
	gchar* _tmp222_ = NULL;
	gchar* _tmp223_ = NULL;
	gchar* _tmp224_ = NULL;
	gchar* _tmp225_ = NULL;
	gchar* _tmp226_ = NULL;
	gchar* _tmp227_ = NULL;
	gchar* _tmp228_ = NULL;
	gchar* _tmp229_ = NULL;
	gchar* _tmp230_ = NULL;
	gchar* _tmp231_ = NULL;
	gchar* _tmp232_ = NULL;
	gchar* _tmp233_ = NULL;
	gchar* _tmp234_ = NULL;
	gchar* _tmp235_ = NULL;
	gchar* _tmp236_ = NULL;
	gchar* _tmp237_ = NULL;
	gchar* _tmp238_ = NULL;
	gchar* _tmp239_ = NULL;
	gchar* _tmp240_ = NULL;
	gchar* _tmp241_ = NULL;
	gchar* _tmp242_ = NULL;
	gchar* _tmp243_ = NULL;
	gchar* _tmp244_ = NULL;
	gchar* _tmp245_ = NULL;
	gchar* _tmp246_ = NULL;
	gchar* _tmp247_ = NULL;
	gchar* _tmp248_ = NULL;
	gchar* _tmp249_ = NULL;
	gchar* _tmp250_ = NULL;
	gchar* _tmp251_ = NULL;
	gchar* _tmp252_ = NULL;
	gchar* _tmp253_ = NULL;
	gchar* _tmp254_ = NULL;
	gchar* _tmp255_ = NULL;
	gchar** _tmp256_ = NULL;
	self->priv = ENTITAS_WORLD_GET_PRIVATE (self);
	self->priv->_totalComponents = 0;
	self->priv->_creationIndex = 0;
	_tmp0_ = g_strdup ("00");
	_tmp1_ = g_strdup ("01");
	_tmp2_ = g_strdup ("02");
	_tmp3_ = g_strdup ("03");
	_tmp4_ = g_strdup ("04");
	_tmp5_ = g_strdup ("05");
	_tmp6_ = g_strdup ("06");
	_tmp7_ = g_strdup ("07");
	_tmp8_ = g_strdup ("08");
	_tmp9_ = g_strdup ("09");
	_tmp10_ = g_strdup ("0a");
	_tmp11_ = g_strdup ("0b");
	_tmp12_ = g_strdup ("0c");
	_tmp13_ = g_strdup ("0d");
	_tmp14_ = g_strdup ("0e");
	_tmp15_ = g_strdup ("0f");
	_tmp16_ = g_strdup ("10");
	_tmp17_ = g_strdup ("11");
	_tmp18_ = g_strdup ("12");
	_tmp19_ = g_strdup ("13");
	_tmp20_ = g_strdup ("14");
	_tmp21_ = g_strdup ("15");
	_tmp22_ = g_strdup ("16");
	_tmp23_ = g_strdup ("17");
	_tmp24_ = g_strdup ("18");
	_tmp25_ = g_strdup ("19");
	_tmp26_ = g_strdup ("1a");
	_tmp27_ = g_strdup ("1b");
	_tmp28_ = g_strdup ("1c");
	_tmp29_ = g_strdup ("1d");
	_tmp30_ = g_strdup ("1e");
	_tmp31_ = g_strdup ("1f");
	_tmp32_ = g_strdup ("20");
	_tmp33_ = g_strdup ("21");
	_tmp34_ = g_strdup ("22");
	_tmp35_ = g_strdup ("23");
	_tmp36_ = g_strdup ("24");
	_tmp37_ = g_strdup ("25");
	_tmp38_ = g_strdup ("26");
	_tmp39_ = g_strdup ("27");
	_tmp40_ = g_strdup ("28");
	_tmp41_ = g_strdup ("29");
	_tmp42_ = g_strdup ("2a");
	_tmp43_ = g_strdup ("2b");
	_tmp44_ = g_strdup ("2c");
	_tmp45_ = g_strdup ("2d");
	_tmp46_ = g_strdup ("2e");
	_tmp47_ = g_strdup ("2f");
	_tmp48_ = g_strdup ("30");
	_tmp49_ = g_strdup ("31");
	_tmp50_ = g_strdup ("32");
	_tmp51_ = g_strdup ("33");
	_tmp52_ = g_strdup ("34");
	_tmp53_ = g_strdup ("35");
	_tmp54_ = g_strdup ("36");
	_tmp55_ = g_strdup ("37");
	_tmp56_ = g_strdup ("38");
	_tmp57_ = g_strdup ("39");
	_tmp58_ = g_strdup ("3a");
	_tmp59_ = g_strdup ("3b");
	_tmp60_ = g_strdup ("3c");
	_tmp61_ = g_strdup ("3d");
	_tmp62_ = g_strdup ("3e");
	_tmp63_ = g_strdup ("3f");
	_tmp64_ = g_strdup ("40");
	_tmp65_ = g_strdup ("41");
	_tmp66_ = g_strdup ("42");
	_tmp67_ = g_strdup ("43");
	_tmp68_ = g_strdup ("44");
	_tmp69_ = g_strdup ("45");
	_tmp70_ = g_strdup ("46");
	_tmp71_ = g_strdup ("47");
	_tmp72_ = g_strdup ("48");
	_tmp73_ = g_strdup ("49");
	_tmp74_ = g_strdup ("4a");
	_tmp75_ = g_strdup ("4b");
	_tmp76_ = g_strdup ("4c");
	_tmp77_ = g_strdup ("4d");
	_tmp78_ = g_strdup ("4e");
	_tmp79_ = g_strdup ("4f");
	_tmp80_ = g_strdup ("50");
	_tmp81_ = g_strdup ("51");
	_tmp82_ = g_strdup ("52");
	_tmp83_ = g_strdup ("53");
	_tmp84_ = g_strdup ("54");
	_tmp85_ = g_strdup ("55");
	_tmp86_ = g_strdup ("56");
	_tmp87_ = g_strdup ("57");
	_tmp88_ = g_strdup ("58");
	_tmp89_ = g_strdup ("59");
	_tmp90_ = g_strdup ("5a");
	_tmp91_ = g_strdup ("5b");
	_tmp92_ = g_strdup ("5c");
	_tmp93_ = g_strdup ("5d");
	_tmp94_ = g_strdup ("5e");
	_tmp95_ = g_strdup ("5f");
	_tmp96_ = g_strdup ("60");
	_tmp97_ = g_strdup ("61");
	_tmp98_ = g_strdup ("62");
	_tmp99_ = g_strdup ("63");
	_tmp100_ = g_strdup ("64");
	_tmp101_ = g_strdup ("65");
	_tmp102_ = g_strdup ("66");
	_tmp103_ = g_strdup ("67");
	_tmp104_ = g_strdup ("68");
	_tmp105_ = g_strdup ("69");
	_tmp106_ = g_strdup ("6a");
	_tmp107_ = g_strdup ("6b");
	_tmp108_ = g_strdup ("6c");
	_tmp109_ = g_strdup ("6d");
	_tmp110_ = g_strdup ("6e");
	_tmp111_ = g_strdup ("6f");
	_tmp112_ = g_strdup ("70");
	_tmp113_ = g_strdup ("71");
	_tmp114_ = g_strdup ("72");
	_tmp115_ = g_strdup ("73");
	_tmp116_ = g_strdup ("74");
	_tmp117_ = g_strdup ("75");
	_tmp118_ = g_strdup ("76");
	_tmp119_ = g_strdup ("77");
	_tmp120_ = g_strdup ("78");
	_tmp121_ = g_strdup ("79");
	_tmp122_ = g_strdup ("7a");
	_tmp123_ = g_strdup ("7b");
	_tmp124_ = g_strdup ("7c");
	_tmp125_ = g_strdup ("7d");
	_tmp126_ = g_strdup ("7e");
	_tmp127_ = g_strdup ("7f");
	_tmp128_ = g_strdup ("80");
	_tmp129_ = g_strdup ("81");
	_tmp130_ = g_strdup ("82");
	_tmp131_ = g_strdup ("83");
	_tmp132_ = g_strdup ("84");
	_tmp133_ = g_strdup ("85");
	_tmp134_ = g_strdup ("86");
	_tmp135_ = g_strdup ("87");
	_tmp136_ = g_strdup ("88");
	_tmp137_ = g_strdup ("89");
	_tmp138_ = g_strdup ("8a");
	_tmp139_ = g_strdup ("8b");
	_tmp140_ = g_strdup ("8c");
	_tmp141_ = g_strdup ("8d");
	_tmp142_ = g_strdup ("8e");
	_tmp143_ = g_strdup ("8f");
	_tmp144_ = g_strdup ("90");
	_tmp145_ = g_strdup ("91");
	_tmp146_ = g_strdup ("92");
	_tmp147_ = g_strdup ("93");
	_tmp148_ = g_strdup ("94");
	_tmp149_ = g_strdup ("95");
	_tmp150_ = g_strdup ("96");
	_tmp151_ = g_strdup ("97");
	_tmp152_ = g_strdup ("98");
	_tmp153_ = g_strdup ("99");
	_tmp154_ = g_strdup ("9a");
	_tmp155_ = g_strdup ("9b");
	_tmp156_ = g_strdup ("9c");
	_tmp157_ = g_strdup ("9d");
	_tmp158_ = g_strdup ("9e");
	_tmp159_ = g_strdup ("9f");
	_tmp160_ = g_strdup ("a0");
	_tmp161_ = g_strdup ("a1");
	_tmp162_ = g_strdup ("a2");
	_tmp163_ = g_strdup ("a3");
	_tmp164_ = g_strdup ("a4");
	_tmp165_ = g_strdup ("a5");
	_tmp166_ = g_strdup ("a6");
	_tmp167_ = g_strdup ("a7");
	_tmp168_ = g_strdup ("a8");
	_tmp169_ = g_strdup ("a9");
	_tmp170_ = g_strdup ("aa");
	_tmp171_ = g_strdup ("ab");
	_tmp172_ = g_strdup ("ac");
	_tmp173_ = g_strdup ("ad");
	_tmp174_ = g_strdup ("ae");
	_tmp175_ = g_strdup ("af");
	_tmp176_ = g_strdup ("b0");
	_tmp177_ = g_strdup ("b1");
	_tmp178_ = g_strdup ("b2");
	_tmp179_ = g_strdup ("b3");
	_tmp180_ = g_strdup ("b4");
	_tmp181_ = g_strdup ("b5");
	_tmp182_ = g_strdup ("b6");
	_tmp183_ = g_strdup ("b7");
	_tmp184_ = g_strdup ("b8");
	_tmp185_ = g_strdup ("b9");
	_tmp186_ = g_strdup ("ba");
	_tmp187_ = g_strdup ("bb");
	_tmp188_ = g_strdup ("bc");
	_tmp189_ = g_strdup ("bd");
	_tmp190_ = g_strdup ("be");
	_tmp191_ = g_strdup ("bf");
	_tmp192_ = g_strdup ("c0");
	_tmp193_ = g_strdup ("c1");
	_tmp194_ = g_strdup ("c2");
	_tmp195_ = g_strdup ("c3");
	_tmp196_ = g_strdup ("c4");
	_tmp197_ = g_strdup ("c5");
	_tmp198_ = g_strdup ("c6");
	_tmp199_ = g_strdup ("c7");
	_tmp200_ = g_strdup ("c8");
	_tmp201_ = g_strdup ("c9");
	_tmp202_ = g_strdup ("ca");
	_tmp203_ = g_strdup ("cb");
	_tmp204_ = g_strdup ("cc");
	_tmp205_ = g_strdup ("cd");
	_tmp206_ = g_strdup ("ce");
	_tmp207_ = g_strdup ("cf");
	_tmp208_ = g_strdup ("d0");
	_tmp209_ = g_strdup ("d1");
	_tmp210_ = g_strdup ("d2");
	_tmp211_ = g_strdup ("d3");
	_tmp212_ = g_strdup ("d4");
	_tmp213_ = g_strdup ("d5");
	_tmp214_ = g_strdup ("d6");
	_tmp215_ = g_strdup ("d7");
	_tmp216_ = g_strdup ("d8");
	_tmp217_ = g_strdup ("d9");
	_tmp218_ = g_strdup ("da");
	_tmp219_ = g_strdup ("db");
	_tmp220_ = g_strdup ("dc");
	_tmp221_ = g_strdup ("dd");
	_tmp222_ = g_strdup ("de");
	_tmp223_ = g_strdup ("df");
	_tmp224_ = g_strdup ("e0");
	_tmp225_ = g_strdup ("e1");
	_tmp226_ = g_strdup ("e2");
	_tmp227_ = g_strdup ("e3");
	_tmp228_ = g_strdup ("e4");
	_tmp229_ = g_strdup ("e5");
	_tmp230_ = g_strdup ("e6");
	_tmp231_ = g_strdup ("e7");
	_tmp232_ = g_strdup ("e8");
	_tmp233_ = g_strdup ("e9");
	_tmp234_ = g_strdup ("ea");
	_tmp235_ = g_strdup ("eb");
	_tmp236_ = g_strdup ("ec");
	_tmp237_ = g_strdup ("ed");
	_tmp238_ = g_strdup ("ee");
	_tmp239_ = g_strdup ("ef");
	_tmp240_ = g_strdup ("f0");
	_tmp241_ = g_strdup ("f1");
	_tmp242_ = g_strdup ("f2");
	_tmp243_ = g_strdup ("f3");
	_tmp244_ = g_strdup ("f4");
	_tmp245_ = g_strdup ("f5");
	_tmp246_ = g_strdup ("f6");
	_tmp247_ = g_strdup ("f7");
	_tmp248_ = g_strdup ("f8");
	_tmp249_ = g_strdup ("f9");
	_tmp250_ = g_strdup ("fa");
	_tmp251_ = g_strdup ("fb");
	_tmp252_ = g_strdup ("fc");
	_tmp253_ = g_strdup ("fd");
	_tmp254_ = g_strdup ("fe");
	_tmp255_ = g_strdup ("ff");
	_tmp256_ = g_new0 (gchar*, 256 + 1);
	_tmp256_[0] = _tmp0_;
	_tmp256_[1] = _tmp1_;
	_tmp256_[2] = _tmp2_;
	_tmp256_[3] = _tmp3_;
	_tmp256_[4] = _tmp4_;
	_tmp256_[5] = _tmp5_;
	_tmp256_[6] = _tmp6_;
	_tmp256_[7] = _tmp7_;
	_tmp256_[8] = _tmp8_;
	_tmp256_[9] = _tmp9_;
	_tmp256_[10] = _tmp10_;
	_tmp256_[11] = _tmp11_;
	_tmp256_[12] = _tmp12_;
	_tmp256_[13] = _tmp13_;
	_tmp256_[14] = _tmp14_;
	_tmp256_[15] = _tmp15_;
	_tmp256_[16] = _tmp16_;
	_tmp256_[17] = _tmp17_;
	_tmp256_[18] = _tmp18_;
	_tmp256_[19] = _tmp19_;
	_tmp256_[20] = _tmp20_;
	_tmp256_[21] = _tmp21_;
	_tmp256_[22] = _tmp22_;
	_tmp256_[23] = _tmp23_;
	_tmp256_[24] = _tmp24_;
	_tmp256_[25] = _tmp25_;
	_tmp256_[26] = _tmp26_;
	_tmp256_[27] = _tmp27_;
	_tmp256_[28] = _tmp28_;
	_tmp256_[29] = _tmp29_;
	_tmp256_[30] = _tmp30_;
	_tmp256_[31] = _tmp31_;
	_tmp256_[32] = _tmp32_;
	_tmp256_[33] = _tmp33_;
	_tmp256_[34] = _tmp34_;
	_tmp256_[35] = _tmp35_;
	_tmp256_[36] = _tmp36_;
	_tmp256_[37] = _tmp37_;
	_tmp256_[38] = _tmp38_;
	_tmp256_[39] = _tmp39_;
	_tmp256_[40] = _tmp40_;
	_tmp256_[41] = _tmp41_;
	_tmp256_[42] = _tmp42_;
	_tmp256_[43] = _tmp43_;
	_tmp256_[44] = _tmp44_;
	_tmp256_[45] = _tmp45_;
	_tmp256_[46] = _tmp46_;
	_tmp256_[47] = _tmp47_;
	_tmp256_[48] = _tmp48_;
	_tmp256_[49] = _tmp49_;
	_tmp256_[50] = _tmp50_;
	_tmp256_[51] = _tmp51_;
	_tmp256_[52] = _tmp52_;
	_tmp256_[53] = _tmp53_;
	_tmp256_[54] = _tmp54_;
	_tmp256_[55] = _tmp55_;
	_tmp256_[56] = _tmp56_;
	_tmp256_[57] = _tmp57_;
	_tmp256_[58] = _tmp58_;
	_tmp256_[59] = _tmp59_;
	_tmp256_[60] = _tmp60_;
	_tmp256_[61] = _tmp61_;
	_tmp256_[62] = _tmp62_;
	_tmp256_[63] = _tmp63_;
	_tmp256_[64] = _tmp64_;
	_tmp256_[65] = _tmp65_;
	_tmp256_[66] = _tmp66_;
	_tmp256_[67] = _tmp67_;
	_tmp256_[68] = _tmp68_;
	_tmp256_[69] = _tmp69_;
	_tmp256_[70] = _tmp70_;
	_tmp256_[71] = _tmp71_;
	_tmp256_[72] = _tmp72_;
	_tmp256_[73] = _tmp73_;
	_tmp256_[74] = _tmp74_;
	_tmp256_[75] = _tmp75_;
	_tmp256_[76] = _tmp76_;
	_tmp256_[77] = _tmp77_;
	_tmp256_[78] = _tmp78_;
	_tmp256_[79] = _tmp79_;
	_tmp256_[80] = _tmp80_;
	_tmp256_[81] = _tmp81_;
	_tmp256_[82] = _tmp82_;
	_tmp256_[83] = _tmp83_;
	_tmp256_[84] = _tmp84_;
	_tmp256_[85] = _tmp85_;
	_tmp256_[86] = _tmp86_;
	_tmp256_[87] = _tmp87_;
	_tmp256_[88] = _tmp88_;
	_tmp256_[89] = _tmp89_;
	_tmp256_[90] = _tmp90_;
	_tmp256_[91] = _tmp91_;
	_tmp256_[92] = _tmp92_;
	_tmp256_[93] = _tmp93_;
	_tmp256_[94] = _tmp94_;
	_tmp256_[95] = _tmp95_;
	_tmp256_[96] = _tmp96_;
	_tmp256_[97] = _tmp97_;
	_tmp256_[98] = _tmp98_;
	_tmp256_[99] = _tmp99_;
	_tmp256_[100] = _tmp100_;
	_tmp256_[101] = _tmp101_;
	_tmp256_[102] = _tmp102_;
	_tmp256_[103] = _tmp103_;
	_tmp256_[104] = _tmp104_;
	_tmp256_[105] = _tmp105_;
	_tmp256_[106] = _tmp106_;
	_tmp256_[107] = _tmp107_;
	_tmp256_[108] = _tmp108_;
	_tmp256_[109] = _tmp109_;
	_tmp256_[110] = _tmp110_;
	_tmp256_[111] = _tmp111_;
	_tmp256_[112] = _tmp112_;
	_tmp256_[113] = _tmp113_;
	_tmp256_[114] = _tmp114_;
	_tmp256_[115] = _tmp115_;
	_tmp256_[116] = _tmp116_;
	_tmp256_[117] = _tmp117_;
	_tmp256_[118] = _tmp118_;
	_tmp256_[119] = _tmp119_;
	_tmp256_[120] = _tmp120_;
	_tmp256_[121] = _tmp121_;
	_tmp256_[122] = _tmp122_;
	_tmp256_[123] = _tmp123_;
	_tmp256_[124] = _tmp124_;
	_tmp256_[125] = _tmp125_;
	_tmp256_[126] = _tmp126_;
	_tmp256_[127] = _tmp127_;
	_tmp256_[128] = _tmp128_;
	_tmp256_[129] = _tmp129_;
	_tmp256_[130] = _tmp130_;
	_tmp256_[131] = _tmp131_;
	_tmp256_[132] = _tmp132_;
	_tmp256_[133] = _tmp133_;
	_tmp256_[134] = _tmp134_;
	_tmp256_[135] = _tmp135_;
	_tmp256_[136] = _tmp136_;
	_tmp256_[137] = _tmp137_;
	_tmp256_[138] = _tmp138_;
	_tmp256_[139] = _tmp139_;
	_tmp256_[140] = _tmp140_;
	_tmp256_[141] = _tmp141_;
	_tmp256_[142] = _tmp142_;
	_tmp256_[143] = _tmp143_;
	_tmp256_[144] = _tmp144_;
	_tmp256_[145] = _tmp145_;
	_tmp256_[146] = _tmp146_;
	_tmp256_[147] = _tmp147_;
	_tmp256_[148] = _tmp148_;
	_tmp256_[149] = _tmp149_;
	_tmp256_[150] = _tmp150_;
	_tmp256_[151] = _tmp151_;
	_tmp256_[152] = _tmp152_;
	_tmp256_[153] = _tmp153_;
	_tmp256_[154] = _tmp154_;
	_tmp256_[155] = _tmp155_;
	_tmp256_[156] = _tmp156_;
	_tmp256_[157] = _tmp157_;
	_tmp256_[158] = _tmp158_;
	_tmp256_[159] = _tmp159_;
	_tmp256_[160] = _tmp160_;
	_tmp256_[161] = _tmp161_;
	_tmp256_[162] = _tmp162_;
	_tmp256_[163] = _tmp163_;
	_tmp256_[164] = _tmp164_;
	_tmp256_[165] = _tmp165_;
	_tmp256_[166] = _tmp166_;
	_tmp256_[167] = _tmp167_;
	_tmp256_[168] = _tmp168_;
	_tmp256_[169] = _tmp169_;
	_tmp256_[170] = _tmp170_;
	_tmp256_[171] = _tmp171_;
	_tmp256_[172] = _tmp172_;
	_tmp256_[173] = _tmp173_;
	_tmp256_[174] = _tmp174_;
	_tmp256_[175] = _tmp175_;
	_tmp256_[176] = _tmp176_;
	_tmp256_[177] = _tmp177_;
	_tmp256_[178] = _tmp178_;
	_tmp256_[179] = _tmp179_;
	_tmp256_[180] = _tmp180_;
	_tmp256_[181] = _tmp181_;
	_tmp256_[182] = _tmp182_;
	_tmp256_[183] = _tmp183_;
	_tmp256_[184] = _tmp184_;
	_tmp256_[185] = _tmp185_;
	_tmp256_[186] = _tmp186_;
	_tmp256_[187] = _tmp187_;
	_tmp256_[188] = _tmp188_;
	_tmp256_[189] = _tmp189_;
	_tmp256_[190] = _tmp190_;
	_tmp256_[191] = _tmp191_;
	_tmp256_[192] = _tmp192_;
	_tmp256_[193] = _tmp193_;
	_tmp256_[194] = _tmp194_;
	_tmp256_[195] = _tmp195_;
	_tmp256_[196] = _tmp196_;
	_tmp256_[197] = _tmp197_;
	_tmp256_[198] = _tmp198_;
	_tmp256_[199] = _tmp199_;
	_tmp256_[200] = _tmp200_;
	_tmp256_[201] = _tmp201_;
	_tmp256_[202] = _tmp202_;
	_tmp256_[203] = _tmp203_;
	_tmp256_[204] = _tmp204_;
	_tmp256_[205] = _tmp205_;
	_tmp256_[206] = _tmp206_;
	_tmp256_[207] = _tmp207_;
	_tmp256_[208] = _tmp208_;
	_tmp256_[209] = _tmp209_;
	_tmp256_[210] = _tmp210_;
	_tmp256_[211] = _tmp211_;
	_tmp256_[212] = _tmp212_;
	_tmp256_[213] = _tmp213_;
	_tmp256_[214] = _tmp214_;
	_tmp256_[215] = _tmp215_;
	_tmp256_[216] = _tmp216_;
	_tmp256_[217] = _tmp217_;
	_tmp256_[218] = _tmp218_;
	_tmp256_[219] = _tmp219_;
	_tmp256_[220] = _tmp220_;
	_tmp256_[221] = _tmp221_;
	_tmp256_[222] = _tmp222_;
	_tmp256_[223] = _tmp223_;
	_tmp256_[224] = _tmp224_;
	_tmp256_[225] = _tmp225_;
	_tmp256_[226] = _tmp226_;
	_tmp256_[227] = _tmp227_;
	_tmp256_[228] = _tmp228_;
	_tmp256_[229] = _tmp229_;
	_tmp256_[230] = _tmp230_;
	_tmp256_[231] = _tmp231_;
	_tmp256_[232] = _tmp232_;
	_tmp256_[233] = _tmp233_;
	_tmp256_[234] = _tmp234_;
	_tmp256_[235] = _tmp235_;
	_tmp256_[236] = _tmp236_;
	_tmp256_[237] = _tmp237_;
	_tmp256_[238] = _tmp238_;
	_tmp256_[239] = _tmp239_;
	_tmp256_[240] = _tmp240_;
	_tmp256_[241] = _tmp241_;
	_tmp256_[242] = _tmp242_;
	_tmp256_[243] = _tmp243_;
	_tmp256_[244] = _tmp244_;
	_tmp256_[245] = _tmp245_;
	_tmp256_[246] = _tmp246_;
	_tmp256_[247] = _tmp247_;
	_tmp256_[248] = _tmp248_;
	_tmp256_[249] = _tmp249_;
	_tmp256_[250] = _tmp250_;
	_tmp256_[251] = _tmp251_;
	_tmp256_[252] = _tmp252_;
	_tmp256_[253] = _tmp253_;
	_tmp256_[254] = _tmp254_;
	_tmp256_[255] = _tmp255_;
	self->priv->_hex = _tmp256_;
	self->priv->_hex_length1 = 256;
	self->priv->__hex_size_ = self->priv->_hex_length1;
}


static void entitas_world_finalize (GObject* obj) {
	EntitasWorld * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENTITAS_TYPE_WORLD, EntitasWorld);
	_g_object_unref0 (self->priv->_onEntityCreated);
	_g_object_unref0 (self->priv->_onEntityWillBeDestroyed);
	_g_object_unref0 (self->priv->_onEntityDestroyed);
	_g_object_unref0 (self->priv->_onGroupCreated);
	_g_free0 (self->priv->_name);
	_g_object_unref0 (self->priv->_groups);
	_g_object_unref0 (self->priv->_entities);
	_g_object_unref0 (self->priv->_retainedEntities);
	__g_queue_free__g_object_unref0_0 (self->priv->_reusableEntities);
	self->priv->_groupsForIndex = (_vala_array_free (self->priv->_groupsForIndex, self->priv->_groupsForIndex_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->_componentsEnum = (_vala_array_free (self->priv->_componentsEnum, self->priv->_componentsEnum_length1, (GDestroyNotify) g_free), NULL);
	self->priv->_entitiesCache = (_vala_array_free (self->priv->_entitiesCache, self->priv->_entitiesCache_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->_initializeSystems = (_vala_array_free (self->priv->_initializeSystems, self->priv->_initializeSystems_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->_executeSystems = (_vala_array_free (self->priv->_executeSystems, self->priv->_executeSystems_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->_hex = (_vala_array_free (self->priv->_hex, self->priv->_hex_length1, (GDestroyNotify) g_free), NULL);
	G_OBJECT_CLASS (entitas_world_parent_class)->finalize (obj);
}


GType entitas_world_get_type (void) {
	static volatile gsize entitas_world_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_world_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasWorldClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) entitas_world_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EntitasWorld), 0, (GInstanceInitFunc) entitas_world_instance_init, NULL };
		GType entitas_world_type_id;
		entitas_world_type_id = g_type_register_static (G_TYPE_OBJECT, "EntitasWorld", &g_define_type_info, 0);
		g_once_init_leave (&entitas_world_type_id__volatile, entitas_world_type_id);
	}
	return entitas_world_type_id__volatile;
}


static void _vala_entitas_world_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	EntitasWorld * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENTITAS_TYPE_WORLD, EntitasWorld);
	switch (property_id) {
		case ENTITAS_WORLD_COMPONENTS_COUNT:
		g_value_set_int (value, entitas_world_get_componentsCount (self));
		break;
		case ENTITAS_WORLD_COUNT:
		g_value_set_int (value, entitas_world_get_count (self));
		break;
		case ENTITAS_WORLD_REUSABLE_ENTITIES_COUNT:
		g_value_set_int (value, entitas_world_get_reusableEntitiesCount (self));
		break;
		case ENTITAS_WORLD_RETAINED_ENTITIES_COUNT:
		g_value_set_int (value, entitas_world_get_retainedEntitiesCount (self));
		break;
		case ENTITAS_WORLD_ON_ENTITY_CREATED:
		g_value_set_object (value, entitas_world_get_onEntityCreated (self));
		break;
		case ENTITAS_WORLD_ON_ENTITY_WILL_BE_DESTROYED:
		g_value_set_object (value, entitas_world_get_onEntityWillBeDestroyed (self));
		break;
		case ENTITAS_WORLD_ON_ENTITY_DESTROYED:
		g_value_set_object (value, entitas_world_get_onEntityDestroyed (self));
		break;
		case ENTITAS_WORLD_ON_GROUP_CREATED:
		g_value_set_object (value, entitas_world_get_onGroupCreated (self));
		break;
		case ENTITAS_WORLD_NAME:
		g_value_set_string (value, entitas_world_get_name (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



