/* IComponent.c generated by valac 0.34.4, the Vala compiler
 * generated from IComponent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define ENTITAS_TYPE_ICOMPONENT (entitas_icomponent_get_type ())
#define ENTITAS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ICOMPONENT, EntitasIComponent))
#define ENTITAS_IS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ICOMPONENT))
#define ENTITAS_ICOMPONENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_ICOMPONENT, EntitasIComponentIface))

typedef struct _EntitasIComponent EntitasIComponent;
typedef struct _EntitasIComponentIface EntitasIComponentIface;

struct _EntitasIComponentIface {
	GTypeInterface parent_iface;
};



GType entitas_icomponent_get_type (void) G_GNUC_CONST;


static void entitas_icomponent_base_init (EntitasIComponentIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType entitas_icomponent_get_type (void) {
	static volatile gsize entitas_icomponent_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_icomponent_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasIComponentIface), (GBaseInitFunc) entitas_icomponent_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType entitas_icomponent_type_id;
		entitas_icomponent_type_id = g_type_register_static (G_TYPE_INTERFACE, "EntitasIComponent", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (entitas_icomponent_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&entitas_icomponent_type_id__volatile, entitas_icomponent_type_id);
	}
	return entitas_icomponent_type_id__volatile;
}



