/* IMatcher.c generated by valac 0.34.4, the Vala compiler
 * generated from IMatcher.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define ENTITAS_TYPE_IMATCHER (entitas_imatcher_get_type ())
#define ENTITAS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IMATCHER, EntitasIMatcher))
#define ENTITAS_IS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IMATCHER))
#define ENTITAS_IMATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IMATCHER, EntitasIMatcherIface))

typedef struct _EntitasIMatcher EntitasIMatcher;
typedef struct _EntitasIMatcherIface EntitasIMatcherIface;

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())
#define ENTITAS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ENTITY, EntitasEntity))
#define ENTITAS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_ENTITY, EntitasEntityClass))
#define ENTITAS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ENTITY))
#define ENTITAS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_ENTITY))
#define ENTITAS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_ENTITY, EntitasEntityClass))

typedef struct _EntitasEntity EntitasEntity;
typedef struct _EntitasEntityClass EntitasEntityClass;

#define ENTITAS_TYPE_ICOMPOUND_MATCHER (entitas_icompound_matcher_get_type ())
#define ENTITAS_ICOMPOUND_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ICOMPOUND_MATCHER, EntitasICompoundMatcher))
#define ENTITAS_IS_ICOMPOUND_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ICOMPOUND_MATCHER))
#define ENTITAS_ICOMPOUND_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_ICOMPOUND_MATCHER, EntitasICompoundMatcherIface))

typedef struct _EntitasICompoundMatcher EntitasICompoundMatcher;
typedef struct _EntitasICompoundMatcherIface EntitasICompoundMatcherIface;

#define ENTITAS_TYPE_INONE_OF_MATCHER (entitas_inone_of_matcher_get_type ())
#define ENTITAS_INONE_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_INONE_OF_MATCHER, EntitasINoneOfMatcher))
#define ENTITAS_IS_INONE_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_INONE_OF_MATCHER))
#define ENTITAS_INONE_OF_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_INONE_OF_MATCHER, EntitasINoneOfMatcherIface))

typedef struct _EntitasINoneOfMatcher EntitasINoneOfMatcher;
typedef struct _EntitasINoneOfMatcherIface EntitasINoneOfMatcherIface;

#define ENTITAS_TYPE_IANY_OF_MATCHER (entitas_iany_of_matcher_get_type ())
#define ENTITAS_IANY_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IANY_OF_MATCHER, EntitasIAnyOfMatcher))
#define ENTITAS_IS_IANY_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IANY_OF_MATCHER))
#define ENTITAS_IANY_OF_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IANY_OF_MATCHER, EntitasIAnyOfMatcherIface))

typedef struct _EntitasIAnyOfMatcher EntitasIAnyOfMatcher;
typedef struct _EntitasIAnyOfMatcherIface EntitasIAnyOfMatcherIface;

#define ENTITAS_TYPE_IALL_OF_MATCHER (entitas_iall_of_matcher_get_type ())
#define ENTITAS_IALL_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_IALL_OF_MATCHER, EntitasIAllOfMatcher))
#define ENTITAS_IS_IALL_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_IALL_OF_MATCHER))
#define ENTITAS_IALL_OF_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_IALL_OF_MATCHER, EntitasIAllOfMatcherIface))

typedef struct _EntitasIAllOfMatcher EntitasIAllOfMatcher;
typedef struct _EntitasIAllOfMatcherIface EntitasIAllOfMatcherIface;

struct _EntitasIMatcherIface {
	GTypeInterface parent_iface;
	gboolean (*matches) (EntitasIMatcher* self, EntitasEntity* entity);
	gchar* (*toString) (EntitasIMatcher* self);
	const gchar* (*get_id) (EntitasIMatcher* self);
	gint* (*get_indices) (EntitasIMatcher* self, int* result_length1);
};

struct _EntitasICompoundMatcherIface {
	GTypeInterface parent_iface;
	gint* (*get_allOfIndices) (EntitasICompoundMatcher* self, int* result_length1);
	gint* (*get_anyOfIndices) (EntitasICompoundMatcher* self, int* result_length1);
	gint* (*get_noneOfIndices) (EntitasICompoundMatcher* self, int* result_length1);
};

struct _EntitasINoneOfMatcherIface {
	GTypeInterface parent_iface;
};

struct _EntitasIAnyOfMatcherIface {
	GTypeInterface parent_iface;
	EntitasINoneOfMatcher* (*noneOf) (EntitasIAnyOfMatcher* self, gint* args, int args_length1);
};

struct _EntitasIAllOfMatcherIface {
	GTypeInterface parent_iface;
	EntitasIAnyOfMatcher* (*anyOf) (EntitasIAllOfMatcher* self, gint* args, int args_length1);
	EntitasINoneOfMatcher* (*noneOf) (EntitasIAllOfMatcher* self, gint* args, int args_length1);
};



GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_imatcher_get_type (void) G_GNUC_CONST;
gboolean entitas_imatcher_matches (EntitasIMatcher* self, EntitasEntity* entity);
gchar* entitas_imatcher_toString (EntitasIMatcher* self);
const gchar* entitas_imatcher_get_id (EntitasIMatcher* self);
gint* entitas_imatcher_get_indices (EntitasIMatcher* self, int* result_length1);
GType entitas_icompound_matcher_get_type (void) G_GNUC_CONST;
gint* entitas_icompound_matcher_get_allOfIndices (EntitasICompoundMatcher* self, int* result_length1);
gint* entitas_icompound_matcher_get_anyOfIndices (EntitasICompoundMatcher* self, int* result_length1);
gint* entitas_icompound_matcher_get_noneOfIndices (EntitasICompoundMatcher* self, int* result_length1);
GType entitas_inone_of_matcher_get_type (void) G_GNUC_CONST;
GType entitas_iany_of_matcher_get_type (void) G_GNUC_CONST;
EntitasINoneOfMatcher* entitas_iany_of_matcher_noneOf (EntitasIAnyOfMatcher* self, gint* args, int args_length1);
GType entitas_iall_of_matcher_get_type (void) G_GNUC_CONST;
EntitasIAnyOfMatcher* entitas_iall_of_matcher_anyOf (EntitasIAllOfMatcher* self, gint* args, int args_length1);
EntitasINoneOfMatcher* entitas_iall_of_matcher_noneOf (EntitasIAllOfMatcher* self, gint* args, int args_length1);


gboolean entitas_imatcher_matches (EntitasIMatcher* self, EntitasEntity* entity) {
	g_return_val_if_fail (self != NULL, FALSE);
	return ENTITAS_IMATCHER_GET_INTERFACE (self)->matches (self, entity);
}


gchar* entitas_imatcher_toString (EntitasIMatcher* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return ENTITAS_IMATCHER_GET_INTERFACE (self)->toString (self);
}


const gchar* entitas_imatcher_get_id (EntitasIMatcher* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return ENTITAS_IMATCHER_GET_INTERFACE (self)->get_id (self);
}


gint* entitas_imatcher_get_indices (EntitasIMatcher* self, int* result_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return ENTITAS_IMATCHER_GET_INTERFACE (self)->get_indices (self, result_length1);
}


static void entitas_imatcher_base_init (EntitasIMatcherIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
		g_object_interface_install_property (iface, g_param_spec_string ("id", "id", "id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	}
}


GType entitas_imatcher_get_type (void) {
	static volatile gsize entitas_imatcher_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_imatcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasIMatcherIface), (GBaseInitFunc) entitas_imatcher_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType entitas_imatcher_type_id;
		entitas_imatcher_type_id = g_type_register_static (G_TYPE_INTERFACE, "EntitasIMatcher", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (entitas_imatcher_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&entitas_imatcher_type_id__volatile, entitas_imatcher_type_id);
	}
	return entitas_imatcher_type_id__volatile;
}


gint* entitas_icompound_matcher_get_allOfIndices (EntitasICompoundMatcher* self, int* result_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return ENTITAS_ICOMPOUND_MATCHER_GET_INTERFACE (self)->get_allOfIndices (self, result_length1);
}


gint* entitas_icompound_matcher_get_anyOfIndices (EntitasICompoundMatcher* self, int* result_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return ENTITAS_ICOMPOUND_MATCHER_GET_INTERFACE (self)->get_anyOfIndices (self, result_length1);
}


gint* entitas_icompound_matcher_get_noneOfIndices (EntitasICompoundMatcher* self, int* result_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return ENTITAS_ICOMPOUND_MATCHER_GET_INTERFACE (self)->get_noneOfIndices (self, result_length1);
}


static void entitas_icompound_matcher_base_init (EntitasICompoundMatcherIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType entitas_icompound_matcher_get_type (void) {
	static volatile gsize entitas_icompound_matcher_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_icompound_matcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasICompoundMatcherIface), (GBaseInitFunc) entitas_icompound_matcher_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType entitas_icompound_matcher_type_id;
		entitas_icompound_matcher_type_id = g_type_register_static (G_TYPE_INTERFACE, "EntitasICompoundMatcher", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (entitas_icompound_matcher_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&entitas_icompound_matcher_type_id__volatile, entitas_icompound_matcher_type_id);
	}
	return entitas_icompound_matcher_type_id__volatile;
}


static void entitas_inone_of_matcher_base_init (EntitasINoneOfMatcherIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType entitas_inone_of_matcher_get_type (void) {
	static volatile gsize entitas_inone_of_matcher_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_inone_of_matcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasINoneOfMatcherIface), (GBaseInitFunc) entitas_inone_of_matcher_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType entitas_inone_of_matcher_type_id;
		entitas_inone_of_matcher_type_id = g_type_register_static (G_TYPE_INTERFACE, "EntitasINoneOfMatcher", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (entitas_inone_of_matcher_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&entitas_inone_of_matcher_type_id__volatile, entitas_inone_of_matcher_type_id);
	}
	return entitas_inone_of_matcher_type_id__volatile;
}


EntitasINoneOfMatcher* entitas_iany_of_matcher_noneOf (EntitasIAnyOfMatcher* self, gint* args, int args_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return ENTITAS_IANY_OF_MATCHER_GET_INTERFACE (self)->noneOf (self, args, args_length1);
}


static void entitas_iany_of_matcher_base_init (EntitasIAnyOfMatcherIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType entitas_iany_of_matcher_get_type (void) {
	static volatile gsize entitas_iany_of_matcher_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_iany_of_matcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasIAnyOfMatcherIface), (GBaseInitFunc) entitas_iany_of_matcher_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType entitas_iany_of_matcher_type_id;
		entitas_iany_of_matcher_type_id = g_type_register_static (G_TYPE_INTERFACE, "EntitasIAnyOfMatcher", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (entitas_iany_of_matcher_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&entitas_iany_of_matcher_type_id__volatile, entitas_iany_of_matcher_type_id);
	}
	return entitas_iany_of_matcher_type_id__volatile;
}


EntitasIAnyOfMatcher* entitas_iall_of_matcher_anyOf (EntitasIAllOfMatcher* self, gint* args, int args_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return ENTITAS_IALL_OF_MATCHER_GET_INTERFACE (self)->anyOf (self, args, args_length1);
}


EntitasINoneOfMatcher* entitas_iall_of_matcher_noneOf (EntitasIAllOfMatcher* self, gint* args, int args_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return ENTITAS_IALL_OF_MATCHER_GET_INTERFACE (self)->noneOf (self, args, args_length1);
}


static void entitas_iall_of_matcher_base_init (EntitasIAllOfMatcherIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType entitas_iall_of_matcher_get_type (void) {
	static volatile gsize entitas_iall_of_matcher_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_iall_of_matcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasIAllOfMatcherIface), (GBaseInitFunc) entitas_iall_of_matcher_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType entitas_iall_of_matcher_type_id;
		entitas_iall_of_matcher_type_id = g_type_register_static (G_TYPE_INTERFACE, "EntitasIAllOfMatcher", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (entitas_iall_of_matcher_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&entitas_iall_of_matcher_type_id__volatile, entitas_iall_of_matcher_type_id);
	}
	return entitas_iall_of_matcher_type_id__volatile;
}



