/* EntityChanged.c generated by valac 0.34.4, the Vala compiler
 * generated from EntityChanged.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>


#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())
#define ENTITAS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ENTITY, EntitasEntity))
#define ENTITAS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_ENTITY, EntitasEntityClass))
#define ENTITAS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ENTITY))
#define ENTITAS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_ENTITY))
#define ENTITAS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_ENTITY, EntitasEntityClass))

typedef struct _EntitasEntity EntitasEntity;
typedef struct _EntitasEntityClass EntitasEntityClass;

#define ENTITAS_TYPE_ICOMPONENT (entitas_icomponent_get_type ())
#define ENTITAS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ICOMPONENT, EntitasIComponent))
#define ENTITAS_IS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ICOMPONENT))
#define ENTITAS_ICOMPONENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_ICOMPONENT, EntitasIComponentIface))

typedef struct _EntitasIComponent EntitasIComponent;
typedef struct _EntitasIComponentIface EntitasIComponentIface;

#define ENTITAS_TYPE_ENTITY_CHANGED (entitas_entity_changed_get_type ())
#define ENTITAS_ENTITY_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ENTITY_CHANGED, EntitasEntityChanged))
#define ENTITAS_ENTITY_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_ENTITY_CHANGED, EntitasEntityChangedClass))
#define ENTITAS_IS_ENTITY_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ENTITY_CHANGED))
#define ENTITAS_IS_ENTITY_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_ENTITY_CHANGED))
#define ENTITAS_ENTITY_CHANGED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_ENTITY_CHANGED, EntitasEntityChangedClass))

typedef struct _EntitasEntityChanged EntitasEntityChanged;
typedef struct _EntitasEntityChangedClass EntitasEntityChangedClass;
typedef struct _EntitasEntityChangedPrivate EntitasEntityChangedPrivate;

#define ENTITAS_ENTITY_CHANGED_TYPE_LISTENER (entitas_entity_changed_listener_get_type ())
#define ENTITAS_ENTITY_CHANGED_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, EntitasEntityChangedListener))
#define ENTITAS_ENTITY_CHANGED_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, EntitasEntityChangedListenerClass))
#define ENTITAS_ENTITY_CHANGED_IS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_ENTITY_CHANGED_TYPE_LISTENER))
#define ENTITAS_ENTITY_CHANGED_IS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_ENTITY_CHANGED_TYPE_LISTENER))
#define ENTITAS_ENTITY_CHANGED_LISTENER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, EntitasEntityChangedListenerClass))

typedef struct _EntitasEntityChangedListener EntitasEntityChangedListener;
typedef struct _EntitasEntityChangedListenerClass EntitasEntityChangedListenerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _EntitasEntityChangedListenerPrivate EntitasEntityChangedListenerPrivate;

struct _EntitasIComponentIface {
	GTypeInterface parent_iface;
};

typedef void (*EntitasOnEntityChanged) (EntitasEntity* e, gint index, EntitasIComponent* component, void* user_data);
struct _EntitasEntityChanged {
	GObject parent_instance;
	EntitasEntityChangedPrivate * priv;
};

struct _EntitasEntityChangedClass {
	GObjectClass parent_class;
};

struct _EntitasEntityChangedPrivate {
	GeeArrayList* _listeners;
};

struct _EntitasEntityChangedListener {
	GObject parent_instance;
	EntitasEntityChangedListenerPrivate * priv;
};

struct _EntitasEntityChangedListenerClass {
	GObjectClass parent_class;
};

struct _EntitasEntityChangedListenerPrivate {
	EntitasOnEntityChanged _event;
	gpointer _event_target;
};


static gpointer entitas_entity_changed_parent_class = NULL;
static gpointer entitas_entity_changed_listener_parent_class = NULL;

GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_icomponent_get_type (void) G_GNUC_CONST;
GType entitas_entity_changed_get_type (void) G_GNUC_CONST;
GType entitas_entity_changed_listener_get_type (void) G_GNUC_CONST;
#define ENTITAS_ENTITY_CHANGED_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ENTITAS_TYPE_ENTITY_CHANGED, EntitasEntityChangedPrivate))
enum  {
	ENTITAS_ENTITY_CHANGED_DUMMY_PROPERTY
};
void entitas_entity_changed_add (EntitasEntityChanged* self, EntitasOnEntityChanged event, void* event_target);
EntitasEntityChangedListener* entitas_entity_changed_listener_new (EntitasOnEntityChanged event, void* event_target);
EntitasEntityChangedListener* entitas_entity_changed_listener_construct (GType object_type, EntitasOnEntityChanged event, void* event_target);
void entitas_entity_changed_remove (EntitasEntityChanged* self, EntitasOnEntityChanged event, void* event_target);
EntitasOnEntityChanged entitas_entity_changed_listener_get_event (EntitasEntityChangedListener* self, gpointer* result_target);
void entitas_entity_changed_clear (EntitasEntityChanged* self);
void entitas_entity_changed_dispatch (EntitasEntityChanged* self, EntitasEntity* e, gint index, EntitasIComponent* component);
EntitasEntityChanged* entitas_entity_changed_new (void);
EntitasEntityChanged* entitas_entity_changed_construct (GType object_type);
#define ENTITAS_ENTITY_CHANGED_LISTENER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, EntitasEntityChangedListenerPrivate))
enum  {
	ENTITAS_ENTITY_CHANGED_LISTENER_DUMMY_PROPERTY
};
void entitas_entity_changed_listener_set_event (EntitasEntityChangedListener* self, EntitasOnEntityChanged value, gpointer value_target);
static void entitas_entity_changed_listener_finalize (GObject* obj);
static void _vala_entitas_entity_changed_listener_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_entitas_entity_changed_listener_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void entitas_entity_changed_finalize (GObject* obj);


void entitas_entity_changed_add (EntitasEntityChanged* self, EntitasOnEntityChanged event, void* event_target) {
	GeeArrayList* _tmp0_ = NULL;
	EntitasOnEntityChanged _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	EntitasEntityChangedListener* _tmp2_ = NULL;
	EntitasEntityChangedListener* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_listeners;
	_tmp1_ = event;
	_tmp1__target = event_target;
	_tmp2_ = entitas_entity_changed_listener_new (_tmp1_, _tmp1__target);
	_tmp3_ = _tmp2_;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp3_);
	_g_object_unref0 (_tmp3_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void entitas_entity_changed_remove (EntitasEntityChanged* self, EntitasOnEntityChanged event, void* event_target) {
	g_return_if_fail (self != NULL);
	{
		GeeArrayList* _listener_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _listener_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _listener_index = 0;
		_tmp0_ = self->priv->_listeners;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_listener_list = _tmp1_;
		_tmp2_ = _listener_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_listener_size = _tmp4_;
		_listener_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			EntitasEntityChangedListener* listener = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			EntitasEntityChangedListener* _tmp11_ = NULL;
			EntitasOnEntityChanged _tmp12_ = NULL;
			void* _tmp12__target = NULL;
			EntitasOnEntityChanged _tmp13_ = NULL;
			void* _tmp13__target = NULL;
			EntitasOnEntityChanged _tmp14_ = NULL;
			void* _tmp14__target = NULL;
			_tmp5_ = _listener_index;
			_listener_index = _tmp5_ + 1;
			_tmp6_ = _listener_index;
			_tmp7_ = _listener_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _listener_list;
			_tmp9_ = _listener_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			listener = (EntitasEntityChangedListener*) _tmp10_;
			_tmp11_ = listener;
			_tmp12_ = entitas_entity_changed_listener_get_event (_tmp11_, &_tmp12__target);
			_tmp13_ = _tmp12_;
			_tmp13__target = _tmp12__target;
			_tmp14_ = event;
			_tmp14__target = event_target;
			if (_tmp13_ == _tmp14_) {
				GeeArrayList* _tmp15_ = NULL;
				EntitasEntityChangedListener* _tmp16_ = NULL;
				_tmp15_ = self->priv->_listeners;
				_tmp16_ = listener;
				gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp15_, _tmp16_);
				_g_object_unref0 (listener);
				_g_object_unref0 (_listener_list);
				return;
			}
			_g_object_unref0 (listener);
		}
		_g_object_unref0 (_listener_list);
	}
}


void entitas_entity_changed_clear (EntitasEntityChanged* self) {
	GeeArrayList* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gee_array_list_new (ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->_listeners);
	self->priv->_listeners = _tmp0_;
}


void entitas_entity_changed_dispatch (EntitasEntityChanged* self, EntitasEntity* e, gint index, EntitasIComponent* component) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (e != NULL);
	g_return_if_fail (component != NULL);
	{
		GeeArrayList* _listener_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _listener_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _listener_index = 0;
		_tmp0_ = self->priv->_listeners;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_listener_list = _tmp1_;
		_tmp2_ = _listener_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_listener_size = _tmp4_;
		_listener_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			EntitasEntityChangedListener* listener = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			EntitasEntityChangedListener* _tmp11_ = NULL;
			EntitasOnEntityChanged _tmp12_ = NULL;
			void* _tmp12__target = NULL;
			EntitasOnEntityChanged _tmp13_ = NULL;
			void* _tmp13__target = NULL;
			EntitasEntity* _tmp14_ = NULL;
			gint _tmp15_ = 0;
			EntitasIComponent* _tmp16_ = NULL;
			_tmp5_ = _listener_index;
			_listener_index = _tmp5_ + 1;
			_tmp6_ = _listener_index;
			_tmp7_ = _listener_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _listener_list;
			_tmp9_ = _listener_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			listener = (EntitasEntityChangedListener*) _tmp10_;
			_tmp11_ = listener;
			_tmp12_ = entitas_entity_changed_listener_get_event (_tmp11_, &_tmp12__target);
			_tmp13_ = _tmp12_;
			_tmp13__target = _tmp12__target;
			_tmp14_ = e;
			_tmp15_ = index;
			_tmp16_ = component;
			_tmp13_ (_tmp14_, _tmp15_, _tmp16_, _tmp13__target);
			_g_object_unref0 (listener);
		}
		_g_object_unref0 (_listener_list);
	}
}


EntitasEntityChanged* entitas_entity_changed_construct (GType object_type) {
	EntitasEntityChanged * self = NULL;
	self = (EntitasEntityChanged*) g_object_new (object_type, NULL);
	return self;
}


EntitasEntityChanged* entitas_entity_changed_new (void) {
	return entitas_entity_changed_construct (ENTITAS_TYPE_ENTITY_CHANGED);
}


EntitasEntityChangedListener* entitas_entity_changed_listener_construct (GType object_type, EntitasOnEntityChanged event, void* event_target) {
	EntitasEntityChangedListener * self = NULL;
	EntitasOnEntityChanged _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	self = (EntitasEntityChangedListener*) g_object_new (object_type, NULL);
	_tmp0_ = event;
	_tmp0__target = event_target;
	self->priv->_event = _tmp0_;
	self->priv->_event_target = _tmp0__target;
	return self;
}


EntitasEntityChangedListener* entitas_entity_changed_listener_new (EntitasOnEntityChanged event, void* event_target) {
	return entitas_entity_changed_listener_construct (ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, event, event_target);
}


EntitasOnEntityChanged entitas_entity_changed_listener_get_event (EntitasEntityChangedListener* self, gpointer* result_target) {
	EntitasOnEntityChanged result;
	EntitasOnEntityChanged _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	EntitasOnEntityChanged _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_event;
	_tmp0__target = self->priv->_event_target;
	_tmp1_ = _tmp0_;
	_tmp1__target = _tmp0__target;
	*result_target = _tmp1__target;
	result = _tmp1_;
	return result;
}


void entitas_entity_changed_listener_set_event (EntitasEntityChangedListener* self, EntitasOnEntityChanged value, gpointer value_target) {
	EntitasOnEntityChanged _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__target = value_target;
	self->priv->_event = _tmp0_;
	self->priv->_event_target = _tmp0__target;
}


static void entitas_entity_changed_listener_class_init (EntitasEntityChangedListenerClass * klass) {
	entitas_entity_changed_listener_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (EntitasEntityChangedListenerPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_entitas_entity_changed_listener_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_entitas_entity_changed_listener_set_property;
	G_OBJECT_CLASS (klass)->finalize = entitas_entity_changed_listener_finalize;
}


static void entitas_entity_changed_listener_instance_init (EntitasEntityChangedListener * self) {
	self->priv = ENTITAS_ENTITY_CHANGED_LISTENER_GET_PRIVATE (self);
}


static void entitas_entity_changed_listener_finalize (GObject* obj) {
	EntitasEntityChangedListener * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, EntitasEntityChangedListener);
	G_OBJECT_CLASS (entitas_entity_changed_listener_parent_class)->finalize (obj);
}


GType entitas_entity_changed_listener_get_type (void) {
	static volatile gsize entitas_entity_changed_listener_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_entity_changed_listener_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasEntityChangedListenerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) entitas_entity_changed_listener_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EntitasEntityChangedListener), 0, (GInstanceInitFunc) entitas_entity_changed_listener_instance_init, NULL };
		GType entitas_entity_changed_listener_type_id;
		entitas_entity_changed_listener_type_id = g_type_register_static (G_TYPE_OBJECT, "EntitasEntityChangedListener", &g_define_type_info, 0);
		g_once_init_leave (&entitas_entity_changed_listener_type_id__volatile, entitas_entity_changed_listener_type_id);
	}
	return entitas_entity_changed_listener_type_id__volatile;
}


static void _vala_entitas_entity_changed_listener_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	EntitasEntityChangedListener * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, EntitasEntityChangedListener);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_entitas_entity_changed_listener_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	EntitasEntityChangedListener * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, EntitasEntityChangedListener);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void entitas_entity_changed_class_init (EntitasEntityChangedClass * klass) {
	entitas_entity_changed_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (EntitasEntityChangedPrivate));
	G_OBJECT_CLASS (klass)->finalize = entitas_entity_changed_finalize;
}


static void entitas_entity_changed_instance_init (EntitasEntityChanged * self) {
	GeeArrayList* _tmp0_ = NULL;
	self->priv = ENTITAS_ENTITY_CHANGED_GET_PRIVATE (self);
	_tmp0_ = gee_array_list_new (ENTITAS_ENTITY_CHANGED_TYPE_LISTENER, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	self->priv->_listeners = _tmp0_;
}


static void entitas_entity_changed_finalize (GObject* obj) {
	EntitasEntityChanged * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENTITAS_TYPE_ENTITY_CHANGED, EntitasEntityChanged);
	_g_object_unref0 (self->priv->_listeners);
	G_OBJECT_CLASS (entitas_entity_changed_parent_class)->finalize (obj);
}


GType entitas_entity_changed_get_type (void) {
	static volatile gsize entitas_entity_changed_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_entity_changed_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasEntityChangedClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) entitas_entity_changed_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EntitasEntityChanged), 0, (GInstanceInitFunc) entitas_entity_changed_instance_init, NULL };
		GType entitas_entity_changed_type_id;
		entitas_entity_changed_type_id = g_type_register_static (G_TYPE_OBJECT, "EntitasEntityChanged", &g_define_type_info, 0);
		g_once_init_leave (&entitas_entity_changed_type_id__volatile, entitas_entity_changed_type_id);
	}
	return entitas_entity_changed_type_id__volatile;
}



