/* GroupUpdated.c generated by valac 0.34.4, the Vala compiler
 * generated from GroupUpdated.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>


#define ENTITAS_TYPE_GROUP (entitas_group_get_type ())
#define ENTITAS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_GROUP, EntitasGroup))
#define ENTITAS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_GROUP, EntitasGroupClass))
#define ENTITAS_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_GROUP))
#define ENTITAS_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_GROUP))
#define ENTITAS_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_GROUP, EntitasGroupClass))

typedef struct _EntitasGroup EntitasGroup;
typedef struct _EntitasGroupClass EntitasGroupClass;

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())
#define ENTITAS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ENTITY, EntitasEntity))
#define ENTITAS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_ENTITY, EntitasEntityClass))
#define ENTITAS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ENTITY))
#define ENTITAS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_ENTITY))
#define ENTITAS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_ENTITY, EntitasEntityClass))

typedef struct _EntitasEntity EntitasEntity;
typedef struct _EntitasEntityClass EntitasEntityClass;

#define ENTITAS_TYPE_ICOMPONENT (entitas_icomponent_get_type ())
#define ENTITAS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ICOMPONENT, EntitasIComponent))
#define ENTITAS_IS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ICOMPONENT))
#define ENTITAS_ICOMPONENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_ICOMPONENT, EntitasIComponentIface))

typedef struct _EntitasIComponent EntitasIComponent;
typedef struct _EntitasIComponentIface EntitasIComponentIface;

#define ENTITAS_TYPE_GROUP_UPDATED (entitas_group_updated_get_type ())
#define ENTITAS_GROUP_UPDATED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_GROUP_UPDATED, EntitasGroupUpdated))
#define ENTITAS_GROUP_UPDATED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_GROUP_UPDATED, EntitasGroupUpdatedClass))
#define ENTITAS_IS_GROUP_UPDATED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_GROUP_UPDATED))
#define ENTITAS_IS_GROUP_UPDATED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_GROUP_UPDATED))
#define ENTITAS_GROUP_UPDATED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_GROUP_UPDATED, EntitasGroupUpdatedClass))

typedef struct _EntitasGroupUpdated EntitasGroupUpdated;
typedef struct _EntitasGroupUpdatedClass EntitasGroupUpdatedClass;
typedef struct _EntitasGroupUpdatedPrivate EntitasGroupUpdatedPrivate;

#define ENTITAS_GROUP_UPDATED_TYPE_LISTENER (entitas_group_updated_listener_get_type ())
#define ENTITAS_GROUP_UPDATED_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_GROUP_UPDATED_TYPE_LISTENER, EntitasGroupUpdatedListener))
#define ENTITAS_GROUP_UPDATED_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_GROUP_UPDATED_TYPE_LISTENER, EntitasGroupUpdatedListenerClass))
#define ENTITAS_GROUP_UPDATED_IS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_GROUP_UPDATED_TYPE_LISTENER))
#define ENTITAS_GROUP_UPDATED_IS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_GROUP_UPDATED_TYPE_LISTENER))
#define ENTITAS_GROUP_UPDATED_LISTENER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_GROUP_UPDATED_TYPE_LISTENER, EntitasGroupUpdatedListenerClass))

typedef struct _EntitasGroupUpdatedListener EntitasGroupUpdatedListener;
typedef struct _EntitasGroupUpdatedListenerClass EntitasGroupUpdatedListenerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _EntitasGroupUpdatedListenerPrivate EntitasGroupUpdatedListenerPrivate;

struct _EntitasIComponentIface {
	GTypeInterface parent_iface;
};

typedef void (*EntitasOnGroupUpdated) (EntitasGroup* g, EntitasEntity* e, gint i, EntitasIComponent* c, EntitasIComponent* u, void* user_data);
struct _EntitasGroupUpdated {
	GObject parent_instance;
	EntitasGroupUpdatedPrivate * priv;
};

struct _EntitasGroupUpdatedClass {
	GObjectClass parent_class;
};

struct _EntitasGroupUpdatedPrivate {
	GeeArrayList* _listeners;
};

struct _EntitasGroupUpdatedListener {
	GObject parent_instance;
	EntitasGroupUpdatedListenerPrivate * priv;
};

struct _EntitasGroupUpdatedListenerClass {
	GObjectClass parent_class;
};

struct _EntitasGroupUpdatedListenerPrivate {
	EntitasOnGroupUpdated _event;
	gpointer _event_target;
};


static gpointer entitas_group_updated_parent_class = NULL;
static gpointer entitas_group_updated_listener_parent_class = NULL;

GType entitas_group_get_type (void) G_GNUC_CONST;
GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_icomponent_get_type (void) G_GNUC_CONST;
GType entitas_group_updated_get_type (void) G_GNUC_CONST;
GType entitas_group_updated_listener_get_type (void) G_GNUC_CONST;
#define ENTITAS_GROUP_UPDATED_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ENTITAS_TYPE_GROUP_UPDATED, EntitasGroupUpdatedPrivate))
enum  {
	ENTITAS_GROUP_UPDATED_DUMMY_PROPERTY
};
void entitas_group_updated_add (EntitasGroupUpdated* self, EntitasOnGroupUpdated event, void* event_target);
EntitasGroupUpdatedListener* entitas_group_updated_listener_new (EntitasOnGroupUpdated event, void* event_target);
EntitasGroupUpdatedListener* entitas_group_updated_listener_construct (GType object_type, EntitasOnGroupUpdated event, void* event_target);
void entitas_group_updated_remove (EntitasGroupUpdated* self, EntitasOnGroupUpdated event, void* event_target);
EntitasOnGroupUpdated entitas_group_updated_listener_get_event (EntitasGroupUpdatedListener* self, gpointer* result_target);
void entitas_group_updated_clear (EntitasGroupUpdated* self);
void entitas_group_updated_dispatch (EntitasGroupUpdated* self, EntitasGroup* g, EntitasEntity* e, gint i, EntitasIComponent* c, EntitasIComponent* u);
EntitasGroupUpdated* entitas_group_updated_new (void);
EntitasGroupUpdated* entitas_group_updated_construct (GType object_type);
#define ENTITAS_GROUP_UPDATED_LISTENER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ENTITAS_GROUP_UPDATED_TYPE_LISTENER, EntitasGroupUpdatedListenerPrivate))
enum  {
	ENTITAS_GROUP_UPDATED_LISTENER_DUMMY_PROPERTY
};
void entitas_group_updated_listener_set_event (EntitasGroupUpdatedListener* self, EntitasOnGroupUpdated value, gpointer value_target);
static void entitas_group_updated_listener_finalize (GObject* obj);
static void _vala_entitas_group_updated_listener_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_entitas_group_updated_listener_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void entitas_group_updated_finalize (GObject* obj);


void entitas_group_updated_add (EntitasGroupUpdated* self, EntitasOnGroupUpdated event, void* event_target) {
	GeeArrayList* _tmp0_ = NULL;
	EntitasOnGroupUpdated _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	EntitasGroupUpdatedListener* _tmp2_ = NULL;
	EntitasGroupUpdatedListener* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_listeners;
	_tmp1_ = event;
	_tmp1__target = event_target;
	_tmp2_ = entitas_group_updated_listener_new (_tmp1_, _tmp1__target);
	_tmp3_ = _tmp2_;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp3_);
	_g_object_unref0 (_tmp3_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void entitas_group_updated_remove (EntitasGroupUpdated* self, EntitasOnGroupUpdated event, void* event_target) {
	g_return_if_fail (self != NULL);
	{
		GeeArrayList* _listener_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _listener_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _listener_index = 0;
		_tmp0_ = self->priv->_listeners;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_listener_list = _tmp1_;
		_tmp2_ = _listener_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_listener_size = _tmp4_;
		_listener_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			EntitasGroupUpdatedListener* listener = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			EntitasGroupUpdatedListener* _tmp11_ = NULL;
			EntitasOnGroupUpdated _tmp12_ = NULL;
			void* _tmp12__target = NULL;
			EntitasOnGroupUpdated _tmp13_ = NULL;
			void* _tmp13__target = NULL;
			EntitasOnGroupUpdated _tmp14_ = NULL;
			void* _tmp14__target = NULL;
			_tmp5_ = _listener_index;
			_listener_index = _tmp5_ + 1;
			_tmp6_ = _listener_index;
			_tmp7_ = _listener_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _listener_list;
			_tmp9_ = _listener_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			listener = (EntitasGroupUpdatedListener*) _tmp10_;
			_tmp11_ = listener;
			_tmp12_ = entitas_group_updated_listener_get_event (_tmp11_, &_tmp12__target);
			_tmp13_ = _tmp12_;
			_tmp13__target = _tmp12__target;
			_tmp14_ = event;
			_tmp14__target = event_target;
			if (_tmp13_ == _tmp14_) {
				GeeArrayList* _tmp15_ = NULL;
				EntitasGroupUpdatedListener* _tmp16_ = NULL;
				_tmp15_ = self->priv->_listeners;
				_tmp16_ = listener;
				gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp15_, _tmp16_);
				_g_object_unref0 (listener);
				_g_object_unref0 (_listener_list);
				return;
			}
			_g_object_unref0 (listener);
		}
		_g_object_unref0 (_listener_list);
	}
}


void entitas_group_updated_clear (EntitasGroupUpdated* self) {
	GeeArrayList* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gee_array_list_new (ENTITAS_GROUP_UPDATED_TYPE_LISTENER, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->_listeners);
	self->priv->_listeners = _tmp0_;
}


void entitas_group_updated_dispatch (EntitasGroupUpdated* self, EntitasGroup* g, EntitasEntity* e, gint i, EntitasIComponent* c, EntitasIComponent* u) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (g != NULL);
	g_return_if_fail (e != NULL);
	g_return_if_fail (c != NULL);
	g_return_if_fail (u != NULL);
	{
		GeeArrayList* _listener_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _listener_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _listener_index = 0;
		_tmp0_ = self->priv->_listeners;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_listener_list = _tmp1_;
		_tmp2_ = _listener_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_listener_size = _tmp4_;
		_listener_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			EntitasGroupUpdatedListener* listener = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			EntitasGroupUpdatedListener* _tmp11_ = NULL;
			EntitasOnGroupUpdated _tmp12_ = NULL;
			void* _tmp12__target = NULL;
			EntitasOnGroupUpdated _tmp13_ = NULL;
			void* _tmp13__target = NULL;
			EntitasGroup* _tmp14_ = NULL;
			EntitasEntity* _tmp15_ = NULL;
			gint _tmp16_ = 0;
			EntitasIComponent* _tmp17_ = NULL;
			EntitasIComponent* _tmp18_ = NULL;
			_tmp5_ = _listener_index;
			_listener_index = _tmp5_ + 1;
			_tmp6_ = _listener_index;
			_tmp7_ = _listener_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _listener_list;
			_tmp9_ = _listener_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			listener = (EntitasGroupUpdatedListener*) _tmp10_;
			_tmp11_ = listener;
			_tmp12_ = entitas_group_updated_listener_get_event (_tmp11_, &_tmp12__target);
			_tmp13_ = _tmp12_;
			_tmp13__target = _tmp12__target;
			_tmp14_ = g;
			_tmp15_ = e;
			_tmp16_ = i;
			_tmp17_ = c;
			_tmp18_ = u;
			_tmp13_ (_tmp14_, _tmp15_, _tmp16_, _tmp17_, _tmp18_, _tmp13__target);
			_g_object_unref0 (listener);
		}
		_g_object_unref0 (_listener_list);
	}
}


EntitasGroupUpdated* entitas_group_updated_construct (GType object_type) {
	EntitasGroupUpdated * self = NULL;
	self = (EntitasGroupUpdated*) g_object_new (object_type, NULL);
	return self;
}


EntitasGroupUpdated* entitas_group_updated_new (void) {
	return entitas_group_updated_construct (ENTITAS_TYPE_GROUP_UPDATED);
}


EntitasGroupUpdatedListener* entitas_group_updated_listener_construct (GType object_type, EntitasOnGroupUpdated event, void* event_target) {
	EntitasGroupUpdatedListener * self = NULL;
	EntitasOnGroupUpdated _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	self = (EntitasGroupUpdatedListener*) g_object_new (object_type, NULL);
	_tmp0_ = event;
	_tmp0__target = event_target;
	self->priv->_event = _tmp0_;
	self->priv->_event_target = _tmp0__target;
	return self;
}


EntitasGroupUpdatedListener* entitas_group_updated_listener_new (EntitasOnGroupUpdated event, void* event_target) {
	return entitas_group_updated_listener_construct (ENTITAS_GROUP_UPDATED_TYPE_LISTENER, event, event_target);
}


EntitasOnGroupUpdated entitas_group_updated_listener_get_event (EntitasGroupUpdatedListener* self, gpointer* result_target) {
	EntitasOnGroupUpdated result;
	EntitasOnGroupUpdated _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	EntitasOnGroupUpdated _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_event;
	_tmp0__target = self->priv->_event_target;
	_tmp1_ = _tmp0_;
	_tmp1__target = _tmp0__target;
	*result_target = _tmp1__target;
	result = _tmp1_;
	return result;
}


void entitas_group_updated_listener_set_event (EntitasGroupUpdatedListener* self, EntitasOnGroupUpdated value, gpointer value_target) {
	EntitasOnGroupUpdated _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__target = value_target;
	self->priv->_event = _tmp0_;
	self->priv->_event_target = _tmp0__target;
}


static void entitas_group_updated_listener_class_init (EntitasGroupUpdatedListenerClass * klass) {
	entitas_group_updated_listener_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (EntitasGroupUpdatedListenerPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_entitas_group_updated_listener_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_entitas_group_updated_listener_set_property;
	G_OBJECT_CLASS (klass)->finalize = entitas_group_updated_listener_finalize;
}


static void entitas_group_updated_listener_instance_init (EntitasGroupUpdatedListener * self) {
	self->priv = ENTITAS_GROUP_UPDATED_LISTENER_GET_PRIVATE (self);
}


static void entitas_group_updated_listener_finalize (GObject* obj) {
	EntitasGroupUpdatedListener * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENTITAS_GROUP_UPDATED_TYPE_LISTENER, EntitasGroupUpdatedListener);
	G_OBJECT_CLASS (entitas_group_updated_listener_parent_class)->finalize (obj);
}


GType entitas_group_updated_listener_get_type (void) {
	static volatile gsize entitas_group_updated_listener_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_group_updated_listener_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasGroupUpdatedListenerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) entitas_group_updated_listener_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EntitasGroupUpdatedListener), 0, (GInstanceInitFunc) entitas_group_updated_listener_instance_init, NULL };
		GType entitas_group_updated_listener_type_id;
		entitas_group_updated_listener_type_id = g_type_register_static (G_TYPE_OBJECT, "EntitasGroupUpdatedListener", &g_define_type_info, 0);
		g_once_init_leave (&entitas_group_updated_listener_type_id__volatile, entitas_group_updated_listener_type_id);
	}
	return entitas_group_updated_listener_type_id__volatile;
}


static void _vala_entitas_group_updated_listener_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	EntitasGroupUpdatedListener * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENTITAS_GROUP_UPDATED_TYPE_LISTENER, EntitasGroupUpdatedListener);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_entitas_group_updated_listener_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	EntitasGroupUpdatedListener * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENTITAS_GROUP_UPDATED_TYPE_LISTENER, EntitasGroupUpdatedListener);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void entitas_group_updated_class_init (EntitasGroupUpdatedClass * klass) {
	entitas_group_updated_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (EntitasGroupUpdatedPrivate));
	G_OBJECT_CLASS (klass)->finalize = entitas_group_updated_finalize;
}


static void entitas_group_updated_instance_init (EntitasGroupUpdated * self) {
	GeeArrayList* _tmp0_ = NULL;
	self->priv = ENTITAS_GROUP_UPDATED_GET_PRIVATE (self);
	_tmp0_ = gee_array_list_new (ENTITAS_GROUP_UPDATED_TYPE_LISTENER, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	self->priv->_listeners = _tmp0_;
}


static void entitas_group_updated_finalize (GObject* obj) {
	EntitasGroupUpdated * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENTITAS_TYPE_GROUP_UPDATED, EntitasGroupUpdated);
	_g_object_unref0 (self->priv->_listeners);
	G_OBJECT_CLASS (entitas_group_updated_parent_class)->finalize (obj);
}


GType entitas_group_updated_get_type (void) {
	static volatile gsize entitas_group_updated_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_group_updated_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasGroupUpdatedClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) entitas_group_updated_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EntitasGroupUpdated), 0, (GInstanceInitFunc) entitas_group_updated_instance_init, NULL };
		GType entitas_group_updated_type_id;
		entitas_group_updated_type_id = g_type_register_static (G_TYPE_OBJECT, "EntitasGroupUpdated", &g_define_type_info, 0);
		g_once_init_leave (&entitas_group_updated_type_id__volatile, entitas_group_updated_type_id);
	}
	return entitas_group_updated_type_id__volatile;
}



