/* GroupsChanged.c generated by valac 0.34.4, the Vala compiler
 * generated from GroupsChanged.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>


#define ENTITAS_TYPE_WORLD (entitas_world_get_type ())
#define ENTITAS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_WORLD, EntitasWorld))
#define ENTITAS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_WORLD, EntitasWorldClass))
#define ENTITAS_IS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_WORLD))
#define ENTITAS_IS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_WORLD))
#define ENTITAS_WORLD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_WORLD, EntitasWorldClass))

typedef struct _EntitasWorld EntitasWorld;
typedef struct _EntitasWorldClass EntitasWorldClass;

#define ENTITAS_TYPE_GROUP (entitas_group_get_type ())
#define ENTITAS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_GROUP, EntitasGroup))
#define ENTITAS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_GROUP, EntitasGroupClass))
#define ENTITAS_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_GROUP))
#define ENTITAS_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_GROUP))
#define ENTITAS_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_GROUP, EntitasGroupClass))

typedef struct _EntitasGroup EntitasGroup;
typedef struct _EntitasGroupClass EntitasGroupClass;

#define ENTITAS_TYPE_GROUPS_CHANGED (entitas_groups_changed_get_type ())
#define ENTITAS_GROUPS_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_GROUPS_CHANGED, EntitasGroupsChanged))
#define ENTITAS_GROUPS_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_GROUPS_CHANGED, EntitasGroupsChangedClass))
#define ENTITAS_IS_GROUPS_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_GROUPS_CHANGED))
#define ENTITAS_IS_GROUPS_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_GROUPS_CHANGED))
#define ENTITAS_GROUPS_CHANGED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_GROUPS_CHANGED, EntitasGroupsChangedClass))

typedef struct _EntitasGroupsChanged EntitasGroupsChanged;
typedef struct _EntitasGroupsChangedClass EntitasGroupsChangedClass;
typedef struct _EntitasGroupsChangedPrivate EntitasGroupsChangedPrivate;

#define ENTITAS_GROUPS_CHANGED_TYPE_LISTENER (entitas_groups_changed_listener_get_type ())
#define ENTITAS_GROUPS_CHANGED_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, EntitasGroupsChangedListener))
#define ENTITAS_GROUPS_CHANGED_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, EntitasGroupsChangedListenerClass))
#define ENTITAS_GROUPS_CHANGED_IS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_GROUPS_CHANGED_TYPE_LISTENER))
#define ENTITAS_GROUPS_CHANGED_IS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_GROUPS_CHANGED_TYPE_LISTENER))
#define ENTITAS_GROUPS_CHANGED_LISTENER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, EntitasGroupsChangedListenerClass))

typedef struct _EntitasGroupsChangedListener EntitasGroupsChangedListener;
typedef struct _EntitasGroupsChangedListenerClass EntitasGroupsChangedListenerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _EntitasGroupsChangedListenerPrivate EntitasGroupsChangedListenerPrivate;

typedef void (*EntitasOnGroupsChanged) (EntitasWorld* w, EntitasGroup* g, void* user_data);
struct _EntitasGroupsChanged {
	GObject parent_instance;
	EntitasGroupsChangedPrivate * priv;
};

struct _EntitasGroupsChangedClass {
	GObjectClass parent_class;
};

struct _EntitasGroupsChangedPrivate {
	GeeArrayList* _listeners;
};

struct _EntitasGroupsChangedListener {
	GObject parent_instance;
	EntitasGroupsChangedListenerPrivate * priv;
};

struct _EntitasGroupsChangedListenerClass {
	GObjectClass parent_class;
};

struct _EntitasGroupsChangedListenerPrivate {
	EntitasOnGroupsChanged _event;
	gpointer _event_target;
};


static gpointer entitas_groups_changed_parent_class = NULL;
static gpointer entitas_groups_changed_listener_parent_class = NULL;

GType entitas_world_get_type (void) G_GNUC_CONST;
GType entitas_group_get_type (void) G_GNUC_CONST;
GType entitas_groups_changed_get_type (void) G_GNUC_CONST;
GType entitas_groups_changed_listener_get_type (void) G_GNUC_CONST;
#define ENTITAS_GROUPS_CHANGED_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ENTITAS_TYPE_GROUPS_CHANGED, EntitasGroupsChangedPrivate))
enum  {
	ENTITAS_GROUPS_CHANGED_DUMMY_PROPERTY
};
void entitas_groups_changed_add (EntitasGroupsChanged* self, EntitasOnGroupsChanged event, void* event_target);
EntitasGroupsChangedListener* entitas_groups_changed_listener_new (EntitasOnGroupsChanged event, void* event_target);
EntitasGroupsChangedListener* entitas_groups_changed_listener_construct (GType object_type, EntitasOnGroupsChanged event, void* event_target);
void entitas_groups_changed_remove (EntitasGroupsChanged* self, EntitasOnGroupsChanged event, void* event_target);
EntitasOnGroupsChanged entitas_groups_changed_listener_get_event (EntitasGroupsChangedListener* self, gpointer* result_target);
void entitas_groups_changed_clear (EntitasGroupsChanged* self);
void entitas_groups_changed_dispatch (EntitasGroupsChanged* self, EntitasWorld* w, EntitasGroup* g);
EntitasGroupsChanged* entitas_groups_changed_new (void);
EntitasGroupsChanged* entitas_groups_changed_construct (GType object_type);
#define ENTITAS_GROUPS_CHANGED_LISTENER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, EntitasGroupsChangedListenerPrivate))
enum  {
	ENTITAS_GROUPS_CHANGED_LISTENER_DUMMY_PROPERTY
};
void entitas_groups_changed_listener_set_event (EntitasGroupsChangedListener* self, EntitasOnGroupsChanged value, gpointer value_target);
static void entitas_groups_changed_listener_finalize (GObject* obj);
static void _vala_entitas_groups_changed_listener_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_entitas_groups_changed_listener_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void entitas_groups_changed_finalize (GObject* obj);


void entitas_groups_changed_add (EntitasGroupsChanged* self, EntitasOnGroupsChanged event, void* event_target) {
	GeeArrayList* _tmp0_ = NULL;
	EntitasOnGroupsChanged _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	EntitasGroupsChangedListener* _tmp2_ = NULL;
	EntitasGroupsChangedListener* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_listeners;
	_tmp1_ = event;
	_tmp1__target = event_target;
	_tmp2_ = entitas_groups_changed_listener_new (_tmp1_, _tmp1__target);
	_tmp3_ = _tmp2_;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp3_);
	_g_object_unref0 (_tmp3_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void entitas_groups_changed_remove (EntitasGroupsChanged* self, EntitasOnGroupsChanged event, void* event_target) {
	g_return_if_fail (self != NULL);
	{
		GeeArrayList* _listener_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _listener_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _listener_index = 0;
		_tmp0_ = self->priv->_listeners;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_listener_list = _tmp1_;
		_tmp2_ = _listener_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_listener_size = _tmp4_;
		_listener_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			EntitasGroupsChangedListener* listener = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			EntitasGroupsChangedListener* _tmp11_ = NULL;
			EntitasOnGroupsChanged _tmp12_ = NULL;
			void* _tmp12__target = NULL;
			EntitasOnGroupsChanged _tmp13_ = NULL;
			void* _tmp13__target = NULL;
			EntitasOnGroupsChanged _tmp14_ = NULL;
			void* _tmp14__target = NULL;
			_tmp5_ = _listener_index;
			_listener_index = _tmp5_ + 1;
			_tmp6_ = _listener_index;
			_tmp7_ = _listener_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _listener_list;
			_tmp9_ = _listener_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			listener = (EntitasGroupsChangedListener*) _tmp10_;
			_tmp11_ = listener;
			_tmp12_ = entitas_groups_changed_listener_get_event (_tmp11_, &_tmp12__target);
			_tmp13_ = _tmp12_;
			_tmp13__target = _tmp12__target;
			_tmp14_ = event;
			_tmp14__target = event_target;
			if (_tmp13_ == _tmp14_) {
				GeeArrayList* _tmp15_ = NULL;
				EntitasGroupsChangedListener* _tmp16_ = NULL;
				_tmp15_ = self->priv->_listeners;
				_tmp16_ = listener;
				gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp15_, _tmp16_);
				_g_object_unref0 (listener);
				_g_object_unref0 (_listener_list);
				return;
			}
			_g_object_unref0 (listener);
		}
		_g_object_unref0 (_listener_list);
	}
}


void entitas_groups_changed_clear (EntitasGroupsChanged* self) {
	GeeArrayList* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gee_array_list_new (ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->_listeners);
	self->priv->_listeners = _tmp0_;
}


void entitas_groups_changed_dispatch (EntitasGroupsChanged* self, EntitasWorld* w, EntitasGroup* g) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (w != NULL);
	g_return_if_fail (g != NULL);
	{
		GeeArrayList* _listener_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _listener_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _listener_index = 0;
		_tmp0_ = self->priv->_listeners;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_listener_list = _tmp1_;
		_tmp2_ = _listener_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_listener_size = _tmp4_;
		_listener_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			EntitasGroupsChangedListener* listener = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			EntitasGroupsChangedListener* _tmp11_ = NULL;
			EntitasOnGroupsChanged _tmp12_ = NULL;
			void* _tmp12__target = NULL;
			EntitasOnGroupsChanged _tmp13_ = NULL;
			void* _tmp13__target = NULL;
			EntitasWorld* _tmp14_ = NULL;
			EntitasGroup* _tmp15_ = NULL;
			_tmp5_ = _listener_index;
			_listener_index = _tmp5_ + 1;
			_tmp6_ = _listener_index;
			_tmp7_ = _listener_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _listener_list;
			_tmp9_ = _listener_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			listener = (EntitasGroupsChangedListener*) _tmp10_;
			_tmp11_ = listener;
			_tmp12_ = entitas_groups_changed_listener_get_event (_tmp11_, &_tmp12__target);
			_tmp13_ = _tmp12_;
			_tmp13__target = _tmp12__target;
			_tmp14_ = w;
			_tmp15_ = g;
			_tmp13_ (_tmp14_, _tmp15_, _tmp13__target);
			_g_object_unref0 (listener);
		}
		_g_object_unref0 (_listener_list);
	}
}


EntitasGroupsChanged* entitas_groups_changed_construct (GType object_type) {
	EntitasGroupsChanged * self = NULL;
	self = (EntitasGroupsChanged*) g_object_new (object_type, NULL);
	return self;
}


EntitasGroupsChanged* entitas_groups_changed_new (void) {
	return entitas_groups_changed_construct (ENTITAS_TYPE_GROUPS_CHANGED);
}


EntitasGroupsChangedListener* entitas_groups_changed_listener_construct (GType object_type, EntitasOnGroupsChanged event, void* event_target) {
	EntitasGroupsChangedListener * self = NULL;
	EntitasOnGroupsChanged _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	self = (EntitasGroupsChangedListener*) g_object_new (object_type, NULL);
	_tmp0_ = event;
	_tmp0__target = event_target;
	self->priv->_event = _tmp0_;
	self->priv->_event_target = _tmp0__target;
	return self;
}


EntitasGroupsChangedListener* entitas_groups_changed_listener_new (EntitasOnGroupsChanged event, void* event_target) {
	return entitas_groups_changed_listener_construct (ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, event, event_target);
}


EntitasOnGroupsChanged entitas_groups_changed_listener_get_event (EntitasGroupsChangedListener* self, gpointer* result_target) {
	EntitasOnGroupsChanged result;
	EntitasOnGroupsChanged _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	EntitasOnGroupsChanged _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_event;
	_tmp0__target = self->priv->_event_target;
	_tmp1_ = _tmp0_;
	_tmp1__target = _tmp0__target;
	*result_target = _tmp1__target;
	result = _tmp1_;
	return result;
}


void entitas_groups_changed_listener_set_event (EntitasGroupsChangedListener* self, EntitasOnGroupsChanged value, gpointer value_target) {
	EntitasOnGroupsChanged _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__target = value_target;
	self->priv->_event = _tmp0_;
	self->priv->_event_target = _tmp0__target;
}


static void entitas_groups_changed_listener_class_init (EntitasGroupsChangedListenerClass * klass) {
	entitas_groups_changed_listener_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (EntitasGroupsChangedListenerPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_entitas_groups_changed_listener_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_entitas_groups_changed_listener_set_property;
	G_OBJECT_CLASS (klass)->finalize = entitas_groups_changed_listener_finalize;
}


static void entitas_groups_changed_listener_instance_init (EntitasGroupsChangedListener * self) {
	self->priv = ENTITAS_GROUPS_CHANGED_LISTENER_GET_PRIVATE (self);
}


static void entitas_groups_changed_listener_finalize (GObject* obj) {
	EntitasGroupsChangedListener * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, EntitasGroupsChangedListener);
	G_OBJECT_CLASS (entitas_groups_changed_listener_parent_class)->finalize (obj);
}


GType entitas_groups_changed_listener_get_type (void) {
	static volatile gsize entitas_groups_changed_listener_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_groups_changed_listener_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasGroupsChangedListenerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) entitas_groups_changed_listener_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EntitasGroupsChangedListener), 0, (GInstanceInitFunc) entitas_groups_changed_listener_instance_init, NULL };
		GType entitas_groups_changed_listener_type_id;
		entitas_groups_changed_listener_type_id = g_type_register_static (G_TYPE_OBJECT, "EntitasGroupsChangedListener", &g_define_type_info, 0);
		g_once_init_leave (&entitas_groups_changed_listener_type_id__volatile, entitas_groups_changed_listener_type_id);
	}
	return entitas_groups_changed_listener_type_id__volatile;
}


static void _vala_entitas_groups_changed_listener_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	EntitasGroupsChangedListener * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, EntitasGroupsChangedListener);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_entitas_groups_changed_listener_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	EntitasGroupsChangedListener * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, EntitasGroupsChangedListener);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void entitas_groups_changed_class_init (EntitasGroupsChangedClass * klass) {
	entitas_groups_changed_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (EntitasGroupsChangedPrivate));
	G_OBJECT_CLASS (klass)->finalize = entitas_groups_changed_finalize;
}


static void entitas_groups_changed_instance_init (EntitasGroupsChanged * self) {
	GeeArrayList* _tmp0_ = NULL;
	self->priv = ENTITAS_GROUPS_CHANGED_GET_PRIVATE (self);
	_tmp0_ = gee_array_list_new (ENTITAS_GROUPS_CHANGED_TYPE_LISTENER, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	self->priv->_listeners = _tmp0_;
}


static void entitas_groups_changed_finalize (GObject* obj) {
	EntitasGroupsChanged * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENTITAS_TYPE_GROUPS_CHANGED, EntitasGroupsChanged);
	_g_object_unref0 (self->priv->_listeners);
	G_OBJECT_CLASS (entitas_groups_changed_parent_class)->finalize (obj);
}


GType entitas_groups_changed_get_type (void) {
	static volatile gsize entitas_groups_changed_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_groups_changed_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasGroupsChangedClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) entitas_groups_changed_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EntitasGroupsChanged), 0, (GInstanceInitFunc) entitas_groups_changed_instance_init, NULL };
		GType entitas_groups_changed_type_id;
		entitas_groups_changed_type_id = g_type_register_static (G_TYPE_OBJECT, "EntitasGroupsChanged", &g_define_type_info, 0);
		g_once_init_leave (&entitas_groups_changed_type_id__volatile, entitas_groups_changed_type_id);
	}
	return entitas_groups_changed_type_id__volatile;
}



