/* GroupChanged.c generated by valac 0.34.4, the Vala compiler
 * generated from GroupChanged.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>


#define ENTITAS_TYPE_GROUP (entitas_group_get_type ())
#define ENTITAS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_GROUP, EntitasGroup))
#define ENTITAS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_GROUP, EntitasGroupClass))
#define ENTITAS_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_GROUP))
#define ENTITAS_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_GROUP))
#define ENTITAS_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_GROUP, EntitasGroupClass))

typedef struct _EntitasGroup EntitasGroup;
typedef struct _EntitasGroupClass EntitasGroupClass;

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())
#define ENTITAS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ENTITY, EntitasEntity))
#define ENTITAS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_ENTITY, EntitasEntityClass))
#define ENTITAS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ENTITY))
#define ENTITAS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_ENTITY))
#define ENTITAS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_ENTITY, EntitasEntityClass))

typedef struct _EntitasEntity EntitasEntity;
typedef struct _EntitasEntityClass EntitasEntityClass;

#define ENTITAS_TYPE_ICOMPONENT (entitas_icomponent_get_type ())
#define ENTITAS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_ICOMPONENT, EntitasIComponent))
#define ENTITAS_IS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_ICOMPONENT))
#define ENTITAS_ICOMPONENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ENTITAS_TYPE_ICOMPONENT, EntitasIComponentIface))

typedef struct _EntitasIComponent EntitasIComponent;
typedef struct _EntitasIComponentIface EntitasIComponentIface;

#define ENTITAS_TYPE_GROUP_CHANGED (entitas_group_changed_get_type ())
#define ENTITAS_GROUP_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_GROUP_CHANGED, EntitasGroupChanged))
#define ENTITAS_GROUP_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_GROUP_CHANGED, EntitasGroupChangedClass))
#define ENTITAS_IS_GROUP_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_GROUP_CHANGED))
#define ENTITAS_IS_GROUP_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_GROUP_CHANGED))
#define ENTITAS_GROUP_CHANGED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_GROUP_CHANGED, EntitasGroupChangedClass))

typedef struct _EntitasGroupChanged EntitasGroupChanged;
typedef struct _EntitasGroupChangedClass EntitasGroupChangedClass;
typedef struct _EntitasGroupChangedPrivate EntitasGroupChangedPrivate;

#define ENTITAS_GROUP_CHANGED_TYPE_LISTENER (entitas_group_changed_listener_get_type ())
#define ENTITAS_GROUP_CHANGED_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_GROUP_CHANGED_TYPE_LISTENER, EntitasGroupChangedListener))
#define ENTITAS_GROUP_CHANGED_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_GROUP_CHANGED_TYPE_LISTENER, EntitasGroupChangedListenerClass))
#define ENTITAS_GROUP_CHANGED_IS_LISTENER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_GROUP_CHANGED_TYPE_LISTENER))
#define ENTITAS_GROUP_CHANGED_IS_LISTENER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_GROUP_CHANGED_TYPE_LISTENER))
#define ENTITAS_GROUP_CHANGED_LISTENER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_GROUP_CHANGED_TYPE_LISTENER, EntitasGroupChangedListenerClass))

typedef struct _EntitasGroupChangedListener EntitasGroupChangedListener;
typedef struct _EntitasGroupChangedListenerClass EntitasGroupChangedListenerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _EntitasGroupChangedListenerPrivate EntitasGroupChangedListenerPrivate;

struct _EntitasIComponentIface {
	GTypeInterface parent_iface;
};

typedef void (*EntitasOnGroupChanged) (EntitasGroup* g, EntitasEntity* e, gint i, EntitasIComponent* c, void* user_data);
struct _EntitasGroupChanged {
	GObject parent_instance;
	EntitasGroupChangedPrivate * priv;
};

struct _EntitasGroupChangedClass {
	GObjectClass parent_class;
};

struct _EntitasGroupChangedPrivate {
	GeeArrayList* _listeners;
};

struct _EntitasGroupChangedListener {
	GObject parent_instance;
	EntitasGroupChangedListenerPrivate * priv;
};

struct _EntitasGroupChangedListenerClass {
	GObjectClass parent_class;
};

struct _EntitasGroupChangedListenerPrivate {
	EntitasOnGroupChanged _event;
	gpointer _event_target;
};


static gpointer entitas_group_changed_parent_class = NULL;
static gpointer entitas_group_changed_listener_parent_class = NULL;

GType entitas_group_get_type (void) G_GNUC_CONST;
GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_icomponent_get_type (void) G_GNUC_CONST;
GType entitas_group_changed_get_type (void) G_GNUC_CONST;
GType entitas_group_changed_listener_get_type (void) G_GNUC_CONST;
#define ENTITAS_GROUP_CHANGED_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ENTITAS_TYPE_GROUP_CHANGED, EntitasGroupChangedPrivate))
enum  {
	ENTITAS_GROUP_CHANGED_DUMMY_PROPERTY
};
void entitas_group_changed_add (EntitasGroupChanged* self, EntitasOnGroupChanged event, void* event_target);
EntitasGroupChangedListener* entitas_group_changed_listener_new (EntitasOnGroupChanged event, void* event_target);
EntitasGroupChangedListener* entitas_group_changed_listener_construct (GType object_type, EntitasOnGroupChanged event, void* event_target);
void entitas_group_changed_remove (EntitasGroupChanged* self, EntitasOnGroupChanged event, void* event_target);
EntitasOnGroupChanged entitas_group_changed_listener_get_event (EntitasGroupChangedListener* self, gpointer* result_target);
void entitas_group_changed_clear (EntitasGroupChanged* self);
void entitas_group_changed_dispatch (EntitasGroupChanged* self, EntitasGroup* g, EntitasEntity* e, gint i, EntitasIComponent* c);
EntitasGroupChanged* entitas_group_changed_new (void);
EntitasGroupChanged* entitas_group_changed_construct (GType object_type);
#define ENTITAS_GROUP_CHANGED_LISTENER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ENTITAS_GROUP_CHANGED_TYPE_LISTENER, EntitasGroupChangedListenerPrivate))
enum  {
	ENTITAS_GROUP_CHANGED_LISTENER_DUMMY_PROPERTY
};
void entitas_group_changed_listener_set_event (EntitasGroupChangedListener* self, EntitasOnGroupChanged value, gpointer value_target);
static void entitas_group_changed_listener_finalize (GObject* obj);
static void _vala_entitas_group_changed_listener_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_entitas_group_changed_listener_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void entitas_group_changed_finalize (GObject* obj);


void entitas_group_changed_add (EntitasGroupChanged* self, EntitasOnGroupChanged event, void* event_target) {
	GeeArrayList* _tmp0_ = NULL;
	EntitasOnGroupChanged _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	EntitasGroupChangedListener* _tmp2_ = NULL;
	EntitasGroupChangedListener* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_listeners;
	_tmp1_ = event;
	_tmp1__target = event_target;
	_tmp2_ = entitas_group_changed_listener_new (_tmp1_, _tmp1__target);
	_tmp3_ = _tmp2_;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp3_);
	_g_object_unref0 (_tmp3_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void entitas_group_changed_remove (EntitasGroupChanged* self, EntitasOnGroupChanged event, void* event_target) {
	g_return_if_fail (self != NULL);
	{
		GeeArrayList* _listener_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _listener_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _listener_index = 0;
		_tmp0_ = self->priv->_listeners;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_listener_list = _tmp1_;
		_tmp2_ = _listener_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_listener_size = _tmp4_;
		_listener_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			EntitasGroupChangedListener* listener = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			EntitasGroupChangedListener* _tmp11_ = NULL;
			EntitasOnGroupChanged _tmp12_ = NULL;
			void* _tmp12__target = NULL;
			EntitasOnGroupChanged _tmp13_ = NULL;
			void* _tmp13__target = NULL;
			EntitasOnGroupChanged _tmp14_ = NULL;
			void* _tmp14__target = NULL;
			_tmp5_ = _listener_index;
			_listener_index = _tmp5_ + 1;
			_tmp6_ = _listener_index;
			_tmp7_ = _listener_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _listener_list;
			_tmp9_ = _listener_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			listener = (EntitasGroupChangedListener*) _tmp10_;
			_tmp11_ = listener;
			_tmp12_ = entitas_group_changed_listener_get_event (_tmp11_, &_tmp12__target);
			_tmp13_ = _tmp12_;
			_tmp13__target = _tmp12__target;
			_tmp14_ = event;
			_tmp14__target = event_target;
			if (_tmp13_ == _tmp14_) {
				GeeArrayList* _tmp15_ = NULL;
				EntitasGroupChangedListener* _tmp16_ = NULL;
				_tmp15_ = self->priv->_listeners;
				_tmp16_ = listener;
				gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp15_, _tmp16_);
				_g_object_unref0 (listener);
				_g_object_unref0 (_listener_list);
				return;
			}
			_g_object_unref0 (listener);
		}
		_g_object_unref0 (_listener_list);
	}
}


void entitas_group_changed_clear (EntitasGroupChanged* self) {
	GeeArrayList* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gee_array_list_new (ENTITAS_GROUP_CHANGED_TYPE_LISTENER, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->_listeners);
	self->priv->_listeners = _tmp0_;
}


void entitas_group_changed_dispatch (EntitasGroupChanged* self, EntitasGroup* g, EntitasEntity* e, gint i, EntitasIComponent* c) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (g != NULL);
	g_return_if_fail (e != NULL);
	g_return_if_fail (c != NULL);
	{
		GeeArrayList* _listener_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _listener_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _listener_index = 0;
		_tmp0_ = self->priv->_listeners;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_listener_list = _tmp1_;
		_tmp2_ = _listener_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_listener_size = _tmp4_;
		_listener_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			EntitasGroupChangedListener* listener = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			EntitasGroupChangedListener* _tmp11_ = NULL;
			EntitasOnGroupChanged _tmp12_ = NULL;
			void* _tmp12__target = NULL;
			EntitasOnGroupChanged _tmp13_ = NULL;
			void* _tmp13__target = NULL;
			EntitasGroup* _tmp14_ = NULL;
			EntitasEntity* _tmp15_ = NULL;
			gint _tmp16_ = 0;
			EntitasIComponent* _tmp17_ = NULL;
			_tmp5_ = _listener_index;
			_listener_index = _tmp5_ + 1;
			_tmp6_ = _listener_index;
			_tmp7_ = _listener_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _listener_list;
			_tmp9_ = _listener_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			listener = (EntitasGroupChangedListener*) _tmp10_;
			_tmp11_ = listener;
			_tmp12_ = entitas_group_changed_listener_get_event (_tmp11_, &_tmp12__target);
			_tmp13_ = _tmp12_;
			_tmp13__target = _tmp12__target;
			_tmp14_ = g;
			_tmp15_ = e;
			_tmp16_ = i;
			_tmp17_ = c;
			_tmp13_ (_tmp14_, _tmp15_, _tmp16_, _tmp17_, _tmp13__target);
			_g_object_unref0 (listener);
		}
		_g_object_unref0 (_listener_list);
	}
}


EntitasGroupChanged* entitas_group_changed_construct (GType object_type) {
	EntitasGroupChanged * self = NULL;
	self = (EntitasGroupChanged*) g_object_new (object_type, NULL);
	return self;
}


EntitasGroupChanged* entitas_group_changed_new (void) {
	return entitas_group_changed_construct (ENTITAS_TYPE_GROUP_CHANGED);
}


EntitasGroupChangedListener* entitas_group_changed_listener_construct (GType object_type, EntitasOnGroupChanged event, void* event_target) {
	EntitasGroupChangedListener * self = NULL;
	EntitasOnGroupChanged _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	self = (EntitasGroupChangedListener*) g_object_new (object_type, NULL);
	_tmp0_ = event;
	_tmp0__target = event_target;
	self->priv->_event = _tmp0_;
	self->priv->_event_target = _tmp0__target;
	return self;
}


EntitasGroupChangedListener* entitas_group_changed_listener_new (EntitasOnGroupChanged event, void* event_target) {
	return entitas_group_changed_listener_construct (ENTITAS_GROUP_CHANGED_TYPE_LISTENER, event, event_target);
}


EntitasOnGroupChanged entitas_group_changed_listener_get_event (EntitasGroupChangedListener* self, gpointer* result_target) {
	EntitasOnGroupChanged result;
	EntitasOnGroupChanged _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	EntitasOnGroupChanged _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_event;
	_tmp0__target = self->priv->_event_target;
	_tmp1_ = _tmp0_;
	_tmp1__target = _tmp0__target;
	*result_target = _tmp1__target;
	result = _tmp1_;
	return result;
}


void entitas_group_changed_listener_set_event (EntitasGroupChangedListener* self, EntitasOnGroupChanged value, gpointer value_target) {
	EntitasOnGroupChanged _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__target = value_target;
	self->priv->_event = _tmp0_;
	self->priv->_event_target = _tmp0__target;
}


static void entitas_group_changed_listener_class_init (EntitasGroupChangedListenerClass * klass) {
	entitas_group_changed_listener_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (EntitasGroupChangedListenerPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_entitas_group_changed_listener_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_entitas_group_changed_listener_set_property;
	G_OBJECT_CLASS (klass)->finalize = entitas_group_changed_listener_finalize;
}


static void entitas_group_changed_listener_instance_init (EntitasGroupChangedListener * self) {
	self->priv = ENTITAS_GROUP_CHANGED_LISTENER_GET_PRIVATE (self);
}


static void entitas_group_changed_listener_finalize (GObject* obj) {
	EntitasGroupChangedListener * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENTITAS_GROUP_CHANGED_TYPE_LISTENER, EntitasGroupChangedListener);
	G_OBJECT_CLASS (entitas_group_changed_listener_parent_class)->finalize (obj);
}


GType entitas_group_changed_listener_get_type (void) {
	static volatile gsize entitas_group_changed_listener_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_group_changed_listener_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasGroupChangedListenerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) entitas_group_changed_listener_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EntitasGroupChangedListener), 0, (GInstanceInitFunc) entitas_group_changed_listener_instance_init, NULL };
		GType entitas_group_changed_listener_type_id;
		entitas_group_changed_listener_type_id = g_type_register_static (G_TYPE_OBJECT, "EntitasGroupChangedListener", &g_define_type_info, 0);
		g_once_init_leave (&entitas_group_changed_listener_type_id__volatile, entitas_group_changed_listener_type_id);
	}
	return entitas_group_changed_listener_type_id__volatile;
}


static void _vala_entitas_group_changed_listener_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	EntitasGroupChangedListener * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENTITAS_GROUP_CHANGED_TYPE_LISTENER, EntitasGroupChangedListener);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_entitas_group_changed_listener_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	EntitasGroupChangedListener * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENTITAS_GROUP_CHANGED_TYPE_LISTENER, EntitasGroupChangedListener);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void entitas_group_changed_class_init (EntitasGroupChangedClass * klass) {
	entitas_group_changed_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (EntitasGroupChangedPrivate));
	G_OBJECT_CLASS (klass)->finalize = entitas_group_changed_finalize;
}


static void entitas_group_changed_instance_init (EntitasGroupChanged * self) {
	GeeArrayList* _tmp0_ = NULL;
	self->priv = ENTITAS_GROUP_CHANGED_GET_PRIVATE (self);
	_tmp0_ = gee_array_list_new (ENTITAS_GROUP_CHANGED_TYPE_LISTENER, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	self->priv->_listeners = _tmp0_;
}


static void entitas_group_changed_finalize (GObject* obj) {
	EntitasGroupChanged * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENTITAS_TYPE_GROUP_CHANGED, EntitasGroupChanged);
	_g_object_unref0 (self->priv->_listeners);
	G_OBJECT_CLASS (entitas_group_changed_parent_class)->finalize (obj);
}


GType entitas_group_changed_get_type (void) {
	static volatile gsize entitas_group_changed_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_group_changed_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EntitasGroupChangedClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) entitas_group_changed_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EntitasGroupChanged), 0, (GInstanceInitFunc) entitas_group_changed_instance_init, NULL };
		GType entitas_group_changed_type_id;
		entitas_group_changed_type_id = g_type_register_static (G_TYPE_OBJECT, "EntitasGroupChanged", &g_define_type_info, 0);
		g_once_init_leave (&entitas_group_changed_type_id__volatile, entitas_group_changed_type_id);
	}
	return entitas_group_changed_type_id__volatile;
}



